package org.food.repositories.MeatRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class BirdsRepository {
    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food chickenBreast = Food.builder()
                .name("Chicken Breast")
                .calories(new BigDecimal("165"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("10.6"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("14"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.3"))
                .Calcium(new BigDecimal("1"))
                .Phosphorus(new BigDecimal("210"))
                .Magnesium(new BigDecimal("25"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.9"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("24.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("31"))
                .Fat(new BigDecimal("3.6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.9"))
                .MonounsaturatedFat(new BigDecimal("1.5"))
                .build();

        foodRepository.addFood(chickenBreast);
        Food chickenThighs = Food.builder()
                .name("Chicken Thighs")
                .calories(new BigDecimal("209"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("6.2"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("17"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("204"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.3"))
                .Zinc(new BigDecimal("1.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("28.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("26"))
                .Fat(new BigDecimal("15"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.3"))
                .SaturatedFat(new BigDecimal("3.9"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("3.5"))
                .MonounsaturatedFat(new BigDecimal("6.4"))
                .build();

        foodRepository.addFood(chickenThighs);
        Food chickenDrumsticks = Food.builder()
                .name("Chicken Drumsticks")
                .calories(new BigDecimal("172"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.1"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("6.4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("14"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.5"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("204"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.3"))
                .Zinc(new BigDecimal("1.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("26.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("13"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.3"))
                .SaturatedFat(new BigDecimal("3.6"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2.8"))
                .MonounsaturatedFat(new BigDecimal("6"))
                .build();

        foodRepository.addFood(chickenDrumsticks);
        Food chickenWings = Food.builder()
                .name("Chicken Wings")
                .calories(new BigDecimal("290"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.8"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("6.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("14"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.5"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("195"))
                .Magnesium(new BigDecimal("19"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.5"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("27.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("24"))
                .Fat(new BigDecimal("20"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.5"))
                .SaturatedFat(new BigDecimal("5.6"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("4.4"))
                .MonounsaturatedFat(new BigDecimal("7.7"))
                .build();

        foodRepository.addFood(chickenWings);
        Food chickenLiver = Food.builder()
                .name("Chicken Liver")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("3296")) // Very high in Vitamin A
                .D(new BigDecimal("0.8"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0.3"))
                .C(new BigDecimal("10"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("4.3"))
                .B3(new BigDecimal("13.5"))
                .B5(new BigDecimal("6"))
                .B6(new BigDecimal("0.7"))
                .B7(new BigDecimal("83"))
                .B9(new BigDecimal("588"))
                .B12(new BigDecimal("16.8"))
                .Calcium(new BigDecimal("8"))
                .Phosphorus(new BigDecimal("476"))
                .Magnesium(new BigDecimal("18"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("313"))
                .Chloride(new BigDecimal("55"))
                .Iron(new BigDecimal("8.8"))
                .Zinc(new BigDecimal("5.3"))
                .Copper(new BigDecimal("12"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0.1"))
                .Selenium(new BigDecimal("73.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2.1"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8.6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.4"))
                .SaturatedFat(new BigDecimal("2.7"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3.4"))
                .build();

        foodRepository.addFood(chickenLiver);
        Food chickenGizzards = Food.builder()
                .name("Chicken Gizzards")
                .calories(new BigDecimal("154"))
                .A(new BigDecimal("14"))
                .D(new BigDecimal("0.7"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("2.8"))
                .C(new BigDecimal("5"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("2.6"))
                .B5(new BigDecimal("2.2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("1"))
                .B9(new BigDecimal("35"))
                .B12(new BigDecimal("1.7"))
                .Calcium(new BigDecimal("14"))
                .Phosphorus(new BigDecimal("276"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("94"))
                .Potassium(new BigDecimal("223"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.1"))
                .Zinc(new BigDecimal("2.4"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0.1"))
                .Selenium(new BigDecimal("30.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("29"))
                .Fat(new BigDecimal("9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.4"))
                .SaturatedFat(new BigDecimal("2.6"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3.3"))
                .build();

        foodRepository.addFood(chickenGizzards);
        Food chickenFeet = Food.builder()
                .name("Chicken Feet")
                .calories(new BigDecimal("450")) // Approximation, can vary
                .A(new BigDecimal("500")) // Vitamin A can be significant
                .D(new BigDecimal("0.5")) // Estimate
                .E(new BigDecimal("1")) // Estimate
                .K(new BigDecimal("0.1")) // Estimate
                .C(new BigDecimal("1")) // Estimate
                .B1(new BigDecimal("0.1")) // Estimate
                .B2(new BigDecimal("0.2")) // Estimate
                .B3(new BigDecimal("2")) // Estimate
                .B5(new BigDecimal("0.5")) // Estimate
                .B6(new BigDecimal("0.2")) // Estimate
                .B7(new BigDecimal("10")) // Estimate
                .B9(new BigDecimal("30")) // Estimate
                .B12(new BigDecimal("0.1")) // Estimate
                .Calcium(new BigDecimal("200")) // Estimate
                .Phosphorus(new BigDecimal("150")) // Estimate
                .Magnesium(new BigDecimal("20")) // Estimate
                .Sodium(new BigDecimal("100")) // Estimate
                .Potassium(new BigDecimal("180")) // Estimate
                .Chloride(new BigDecimal("0")) // Estimate
                .Iron(new BigDecimal("2")) // Estimate
                .Zinc(new BigDecimal("1")) // Estimate
                .Copper(new BigDecimal("0.1")) // Estimate
                .Manganese(new BigDecimal("0.1")) // Estimate
                .Iodine(new BigDecimal("0")) // Estimate
                .Selenium(new BigDecimal("0.1")) // Estimate
                .Fluoride(new BigDecimal("0")) // Estimate
                .Chromium(new BigDecimal("0")) // Estimate
                .Molybdenum(new BigDecimal("0")) // Estimate
                .Carbohydrates(new BigDecimal("0")) // Negligible
                .Protein(new BigDecimal("14")) // Estimate
                .Fat(new BigDecimal("40")) // Estimate
                .Fiber(new BigDecimal("0")) // Negligible
                .TransFat(new BigDecimal("0")) // Estimate
                .SaturatedFat(new BigDecimal("10")) // Estimate
                .Sugar(new BigDecimal("0")) // Negligible
                .PolyunsaturatedFat(new BigDecimal("10")) // Estimate
                .MonounsaturatedFat(new BigDecimal("15")) // Estimate
                .build();

        foodRepository.addFood(chickenFeet);
        Food chickenSkin = Food.builder()
                .name("Chicken Skin")
                .calories(new BigDecimal("500")) // Approximation, can vary
                .A(new BigDecimal("0")) // Minimal Vitamin A
                .D(new BigDecimal("0")) // Minimal Vitamin D
                .E(new BigDecimal("1")) // Estimate
                .K(new BigDecimal("0.1")) // Estimate
                .C(new BigDecimal("0")) // Negligible
                .B1(new BigDecimal("0")) // Negligible
                .B2(new BigDecimal("0")) // Negligible
                .B3(new BigDecimal("0")) // Negligible
                .B5(new BigDecimal("0")) // Negligible
                .B6(new BigDecimal("0")) // Negligible
                .B7(new BigDecimal("0")) // Negligible
                .B9(new BigDecimal("0")) // Negligible
                .B12(new BigDecimal("0")) // Negligible
                .Calcium(new BigDecimal("1")) // Minimal
                .Phosphorus(new BigDecimal("50")) // Estimate
                .Magnesium(new BigDecimal("5")) // Estimate
                .Sodium(new BigDecimal("70")) // Estimate
                .Potassium(new BigDecimal("80")) // Estimate
                .Chloride(new BigDecimal("0")) // Estimate
                .Iron(new BigDecimal("1")) // Estimate
                .Zinc(new BigDecimal("0.5")) // Estimate
                .Copper(new BigDecimal("0")) // Negligible
                .Manganese(new BigDecimal("0")) // Negligible
                .Iodine(new BigDecimal("0")) // Negligible
                .Selenium(new BigDecimal("0.5")) // Estimate
                .Fluoride(new BigDecimal("0")) // Negligible
                .Chromium(new BigDecimal("0")) // Negligible
                .Molybdenum(new BigDecimal("0")) // Negligible
                .Carbohydrates(new BigDecimal("0")) // Negligible
                .Protein(new BigDecimal("10")) // Estimate
                .Fat(new BigDecimal("50")) // Estimate
                .Fiber(new BigDecimal("0")) // Negligible
                .TransFat(new BigDecimal("5")) // Estimate
                .SaturatedFat(new BigDecimal("15")) // Estimate
                .Sugar(new BigDecimal("0")) // Negligible
                .PolyunsaturatedFat(new BigDecimal("15")) // Estimate
                .MonounsaturatedFat(new BigDecimal("20")) // Estimate
                .build();

        foodRepository.addFood(chickenSkin);
        Food turkeyBreast = Food.builder()
                .name("Turkey Breast")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("7.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.6"))
                .B7(new BigDecimal("48"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("271"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("259"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.6"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("30"))
                .Fat(new BigDecimal("1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(turkeyBreast);
        Food turkeyLegs = Food.builder()
                .name("Turkey Legs")
                .calories(new BigDecimal("208"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("9"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("80"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("1.3"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("238"))
                .Magnesium(new BigDecimal("23"))
                .Sodium(new BigDecimal("69"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.3"))
                .Zinc(new BigDecimal("2.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("25"))
                .Fat(new BigDecimal("14"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.5"))
                .SaturatedFat(new BigDecimal("3.9"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("4"))
                .MonounsaturatedFat(new BigDecimal("5.8"))
                .build();

        foodRepository.addFood(turkeyLegs);
        Food turkeyWings = Food.builder()
                .name("Turkey Wings")
                .calories(new BigDecimal("238"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("6.4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("35"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("0.8"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("205"))
                .Magnesium(new BigDecimal("24"))
                .Sodium(new BigDecimal("65"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.7"))
                .Zinc(new BigDecimal("1.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("25"))
                .Fat(new BigDecimal("18"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.5"))
                .SaturatedFat(new BigDecimal("4.7"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("5.5"))
                .MonounsaturatedFat(new BigDecimal("7.4"))
                .build();

        foodRepository.addFood(turkeyWings);
        Food turkeyGroundMeat = Food.builder()
                .name("Turkey Ground Meat")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("7.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("30"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("0.9"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("194"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("67"))
                .Potassium(new BigDecimal("239"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.4"))
                .Zinc(new BigDecimal("1.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("33.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("21"))
                .Fat(new BigDecimal("10"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.4"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("4.3"))
                .build();

        foodRepository.addFood(turkeyGroundMeat);
        Food turkeyNeck = Food.builder()
                .name("Turkey Neck")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("2.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("18"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0.6"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("167"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("67"))
                .Potassium(new BigDecimal("209"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.1"))
                .Zinc(new BigDecimal("1.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("22.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("10"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.3"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2.5"))
                .MonounsaturatedFat(new BigDecimal("4.5"))
                .build();

        foodRepository.addFood(turkeyNeck);
        Food turkeyGizzard = Food.builder()
                .name("Turkey Gizzard")
                .calories(new BigDecimal("154"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("2.6"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("17"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("204"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.2"))
                .Zinc(new BigDecimal("1.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("26.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("26"))
                .Fat(new BigDecimal("10"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.2"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2.5"))
                .MonounsaturatedFat(new BigDecimal("4.5"))
                .build();

        foodRepository.addFood(turkeyGizzard);
        Food turkeyLiver = Food.builder()
                .name("Turkey Liver")
                .calories(new BigDecimal("136"))
                .A(new BigDecimal("6000")) // High in Vitamin A
                .D(new BigDecimal("0.7"))
                .E(new BigDecimal("1.6"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("30"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("2.5"))
                .B3(new BigDecimal("10.5"))
                .B5(new BigDecimal("4.7"))
                .B6(new BigDecimal("1.1"))
                .B7(new BigDecimal("12"))
                .B9(new BigDecimal("690"))
                .B12(new BigDecimal("16"))
                .Calcium(new BigDecimal("8"))
                .Phosphorus(new BigDecimal("431"))
                .Magnesium(new BigDecimal("23"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("259"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.7"))
                .Zinc(new BigDecimal("3.6"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0.1"))
                .Selenium(new BigDecimal("73.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.6"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("4.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.4"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("1.8"))
                .build();

        foodRepository.addFood(turkeyLiver);
        Food turkeyHeart = Food.builder()
                .name("Turkey Heart")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.1"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("1"))
                .B3(new BigDecimal("9"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.7"))
                .B7(new BigDecimal("65"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("2.4"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("227"))
                .Magnesium(new BigDecimal("15"))
                .Sodium(new BigDecimal("78"))
                .Potassium(new BigDecimal("167"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.6"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("33.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("4"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.4"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("1.5"))
                .build();

        foodRepository.addFood(turkeyHeart);
        Food turkeyKidneys = Food.builder()
                .name("Turkey Kidneys")
                .calories(new BigDecimal("101"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.1"))
                .K(new BigDecimal("2.7"))
                .C(new BigDecimal("16"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("1.4"))
                .B3(new BigDecimal("3.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("16"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("2.3"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("209"))
                .Magnesium(new BigDecimal("13"))
                .Sodium(new BigDecimal("110"))
                .Potassium(new BigDecimal("322"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.1"))
                .Zinc(new BigDecimal("4"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("38.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("1.7"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.3"))
                .SaturatedFat(new BigDecimal("1.8"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.1"))
                .MonounsaturatedFat(new BigDecimal("1.8"))
                .build();

        foodRepository.addFood(turkeyKidneys);
        Food duckBreast = Food.builder()
                .name("Duck Breast")
                .calories(new BigDecimal("337"))
                .A(new BigDecimal("0")) // Vitamin A content can vary
                .D(new BigDecimal("1.5"))
                .E(new BigDecimal("2.3"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("1"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("1.4"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("1.7"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("249"))
                .Magnesium(new BigDecimal("16"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("348"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.1"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("26.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("16"))
                .Fat(new BigDecimal("30"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.7"))
                .SaturatedFat(new BigDecimal("10"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("5.4"))
                .MonounsaturatedFat(new BigDecimal("12"))
                .build();

        foodRepository.addFood(duckBreast);
        Food duckLegs = Food.builder()
                .name("Duck Legs")
                .calories(new BigDecimal("383"))
                .A(new BigDecimal("0")) // Vitamin A content can vary
                .D(new BigDecimal("3.5"))
                .E(new BigDecimal("1.7"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("2.2"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("34"))
                .B9(new BigDecimal("13"))
                .B12(new BigDecimal("1.8"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("238"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("78"))
                .Potassium(new BigDecimal("290"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.6"))
                .Zinc(new BigDecimal("2.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("31.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("33"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("1.5"))
                .SaturatedFat(new BigDecimal("10"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("6.1"))
                .MonounsaturatedFat(new BigDecimal("15"))
                .build();

        foodRepository.addFood(duckLegs);
        Food duckFoieGras = Food.builder()
                .name("Duck Foie Gras")
                .calories(new BigDecimal("467"))
                .A(new BigDecimal("2812")) // High in Vitamin A
                .D(new BigDecimal("3.8"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.5"))
                .B3(new BigDecimal("4"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("9.6"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("19"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("159"))
                .Magnesium(new BigDecimal("5"))
                .Sodium(new BigDecimal("800"))
                .Potassium(new BigDecimal("157"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.2"))
                .Zinc(new BigDecimal("5.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("13"))
                .Fat(new BigDecimal("41"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("7.2"))
                .SaturatedFat(new BigDecimal("12"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("7"))
                .MonounsaturatedFat(new BigDecimal("17"))
                .build();

        foodRepository.addFood(duckFoieGras);
        Food duckGizzard = Food.builder()
                .name("Duck Gizzard")
                .calories(new BigDecimal("131"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.2"))
                .K(new BigDecimal("2.8"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.5"))
                .B3(new BigDecimal("2.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("7.8"))
                .B9(new BigDecimal("2"))
                .B12(new BigDecimal("4.1"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("227"))
                .Magnesium(new BigDecimal("19"))
                .Sodium(new BigDecimal("94"))
                .Potassium(new BigDecimal("271"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.4"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("23"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.4"))
                .SaturatedFat(new BigDecimal("2.6"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2.1"))
                .MonounsaturatedFat(new BigDecimal("3.6"))
                .build();

        foodRepository.addFood(duckGizzard);
        Food duckLiver = Food.builder()
                .name("Duck Liver")
                .calories(new BigDecimal("136"))
                .A(new BigDecimal("2990")) // High in Vitamin A
                .D(new BigDecimal("2.7"))
                .E(new BigDecimal("1.7"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("5.7"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("1.5"))
                .B3(new BigDecimal("9.4"))
                .B5(new BigDecimal("1.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("18"))
                .B9(new BigDecimal("14"))
                .B12(new BigDecimal("22"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("479"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("74"))
                .Potassium(new BigDecimal("298"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("7.5"))
                .Zinc(new BigDecimal("4.6"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("52.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("11"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("2.8"))
                .SaturatedFat(new BigDecimal("3.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("5.1"))
                .build();

        foodRepository.addFood(duckLiver);
        Food duckHeart = Food.builder()
                .name("Duck Heart")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.4"))
                .K(new BigDecimal("1.5"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("4.7"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("25"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("2.4"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("221"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("72"))
                .Potassium(new BigDecimal("237"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.4"))
                .Zinc(new BigDecimal("5.2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("31.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("11"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0.6"))
                .SaturatedFat(new BigDecimal("3.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2.1"))
                .MonounsaturatedFat(new BigDecimal("4.1"))
                .build();

        foodRepository.addFood(duckHeart);
        Food duckFeet = Food.builder()
                .name("Duck Feet")
                .calories(new BigDecimal("280"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("1.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("14"))
                .Phosphorus(new BigDecimal("216"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("60"))
                .Potassium(new BigDecimal("198"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1.7"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("24"))
                .Fat(new BigDecimal("24"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("7.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("5.7"))
                .MonounsaturatedFat(new BigDecimal("8.3"))
                .build();

        foodRepository.addFood(duckFeet);
        Food duckWebs = Food.builder()
                .name("Duck Webs")
                .calories(new BigDecimal("100")) // Approximate value
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("150"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("60"))
                .Potassium(new BigDecimal("100"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(duckWebs);
        Food duckTongues = Food.builder()
                .name("Duck Tongues")
                .calories(new BigDecimal("80")) // Approximate value
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.2"))
                .K(new BigDecimal("0.8"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("100"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("80"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(duckTongues);
        // Replace "Goose Breast" with the actual name of the food
        String foodName = "Goose Breast";

        Food gooseBreast = Food.builder()
                .name(foodName)
                .calories(new BigDecimal("165")) // Approximate value
                .A(new BigDecimal("375")) // IU (International Units)
                .D(new BigDecimal("0")) // IU
                .E(new BigDecimal("0.72")) // mg
                .K(new BigDecimal("1.2")) // mcg
                .C(new BigDecimal("0")) // mg
                .B1(new BigDecimal("0.05")) // mg
                .B2(new BigDecimal("0.21")) // mg
                .B3(new BigDecimal("1.9")) // mg
                .B5(new BigDecimal("0.3")) // mg
                .B6(new BigDecimal("0.07")) // mg
                .B7(new BigDecimal("0")) // mcg
                .B9(new BigDecimal("7")) // mcg
                .B12(new BigDecimal("1.9")) // mcg
                .Calcium(new BigDecimal("11")) // mg
                .Phosphorus(new BigDecimal("231")) // mg
                .Magnesium(new BigDecimal("24")) // mg
                .Sodium(new BigDecimal("74")) // mg
                .Potassium(new BigDecimal("264")) // mg
                .Chloride(new BigDecimal("0")) // mg
                .Iron(new BigDecimal("1.9")) // mg
                .Zinc(new BigDecimal("2.7")) // mg
                .Copper(new BigDecimal("0.1")) // mg
                .Manganese(new BigDecimal("0")) // mg
                .Iodine(new BigDecimal("0")) // mcg
                .Selenium(new BigDecimal("24.5")) // mcg
                .Fluoride(new BigDecimal("0")) // mg
                .Chromium(new BigDecimal("0")) // mcg
                .Molybdenum(new BigDecimal("0")) // mcg
                .Carbohydrates(new BigDecimal("0")) // g
                .Protein(new BigDecimal("22")) // g
                .Fat(new BigDecimal("13")) // g
                .Fiber(new BigDecimal("0")) // g
                .TransFat(new BigDecimal("0")) // g
                .SaturatedFat(new BigDecimal("4")) // g
                .Sugar(new BigDecimal("0")) // g
                .PolyunsaturatedFat(new BigDecimal("3")) // g
                .MonounsaturatedFat(new BigDecimal("5")) // g
                .build();

        // Assuming foodRepository is an instance of your FoodRepository class
        foodRepository.addFood(gooseBreast);
        // Replace "Goose Legs" with the actual name of the food
        Food gooseLegs = Food.builder()
                .name("Goose Legs")
                .calories(new BigDecimal("300")) // Approximate value
                .A(new BigDecimal("450")) // IU (International Units)
                .D(new BigDecimal("0")) // IU
                .E(new BigDecimal("1.5")) // mg
                .K(new BigDecimal("0")) // mcg
                .C(new BigDecimal("0")) // mg
                .B1(new BigDecimal("0.2")) // mg
                .B2(new BigDecimal("0.6")) // mg
                .B3(new BigDecimal("4")) // mg
                .B5(new BigDecimal("0.7")) // mg
                .B6(new BigDecimal("0.3")) // mg
                .B7(new BigDecimal("0")) // mcg
                .B9(new BigDecimal("8")) // mcg
                .B12(new BigDecimal("2.4")) // mcg
                .Calcium(new BigDecimal("20")) // mg
                .Phosphorus(new BigDecimal("250")) // mg
                .Magnesium(new BigDecimal("25")) // mg
                .Sodium(new BigDecimal("80")) // mg
                .Potassium(new BigDecimal("300")) // mg
                .Chloride(new BigDecimal("0")) // mg
                .Iron(new BigDecimal("2")) // mg
                .Zinc(new BigDecimal("2.5")) // mg
                .Copper(new BigDecimal("0.1")) // mg
                .Manganese(new BigDecimal("0")) // mg
                .Iodine(new BigDecimal("0")) // mcg
                .Selenium(new BigDecimal("30")) // mcg
                .Fluoride(new BigDecimal("0")) // mg
                .Chromium(new BigDecimal("0")) // mcg
                .Molybdenum(new BigDecimal("0")) // mcg
                .Carbohydrates(new BigDecimal("0")) // g
                .Protein(new BigDecimal("20")) // g
                .Fat(new BigDecimal("25")) // g
                .Fiber(new BigDecimal("0")) // g
                .TransFat(new BigDecimal("0")) // g
                .SaturatedFat(new BigDecimal("8")) // g
                .Sugar(new BigDecimal("0")) // g
                .PolyunsaturatedFat(new BigDecimal("6")) // g
                .MonounsaturatedFat(new BigDecimal("10")) // g
                .build();

        // Assuming foodRepository is an instance of your FoodRepository class
        foodRepository.addFood(gooseLegs);

        Food gooseLiver = Food.builder()
                .name("Goose Liver")
                .calories(new BigDecimal("500"))
                .A(new BigDecimal("10000"))
                .D(new BigDecimal("60"))
                .E(new BigDecimal("5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("1.5"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("50"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("100"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("5"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("40"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("1"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("45"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("15"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("5"))
                .MonounsaturatedFat(new BigDecimal("20"))
                .build();

        foodRepository.addFood(gooseLiver);

        Food gooseHeart = Food.builder()
                .name("Goose Heart")
                .calories(new BigDecimal("135"))
                .A(new BigDecimal("790"))
                .D(new BigDecimal("3"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("2"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.8"))
                .B12(new BigDecimal("2.3"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("100"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("65"))
                .Potassium(new BigDecimal("215"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.5"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("24"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("16"))
                .Fat(new BigDecimal("11"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.5"))
                .MonounsaturatedFat(new BigDecimal("4.5"))
                .build();

        foodRepository.addFood(gooseHeart);

        Food gooseGizzards = Food.builder()
                .name("Goose Gizzards")
                .calories(new BigDecimal("150"))
                .A(new BigDecimal("20"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("1"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("270"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("40"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(gooseGizzards);

        Food gooseNeck = Food.builder()
                .name("Goose Neck")
                .calories(new BigDecimal("80"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("100"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("80"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(gooseNeck);

        Food gooseWings = Food.builder()
                .name("Goose Wings")
                .calories(new BigDecimal("200"))
                .A(new BigDecimal("100"))
                .D(new BigDecimal("5"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("100"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("80"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(gooseWings);

        Food gooseFat = Food.builder()
                .name("Goose Fat")
                .calories(new BigDecimal("900"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("50"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0"))
                .B3(new BigDecimal("0"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("1"))
                .Phosphorus(new BigDecimal("1"))
                .Magnesium(new BigDecimal("0"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("0"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0"))
                .Zinc(new BigDecimal("0"))
                .Copper(new BigDecimal("0"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("0"))
                .Fat(new BigDecimal("100"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("30"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("20"))
                .MonounsaturatedFat(new BigDecimal("50"))
                .build();

        foodRepository.addFood(gooseFat);

        Food pigeonBreast = Food.builder()
                .name("Pigeon Breast")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("20"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("0.6"))
                .Calcium(new BigDecimal("0"))
                .Phosphorus(new BigDecimal("170"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("65"))
                .Potassium(new BigDecimal("170"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("17"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("24"))
                .Fat(new BigDecimal("4"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(pigeonBreast);

        Food pigeonThigh = Food.builder()
                .name("Pigeon Thigh")
                .calories(new BigDecimal("150"))
                .A(new BigDecimal("25"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("6"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("0.8"))
                .Calcium(new BigDecimal("0"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("20"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("22"))
                .Fat(new BigDecimal("6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(pigeonThigh);

        Food pigeonLegs = Food.builder()
                .name("Pigeon Legs")
                .calories(new BigDecimal("160"))
                .A(new BigDecimal("30"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("7"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("0"))
                .Phosphorus(new BigDecimal("230"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("23"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(pigeonLegs);

        Food pigeonLiver = Food.builder()
                .name("Pigeon Liver")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("1600"))
                .D(new BigDecimal("6"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("4"))
                .B3(new BigDecimal("6"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("50"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("4"))
                .Phosphorus(new BigDecimal("190"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("3.5"))
                .build();

        foodRepository.addFood(pigeonLiver);

        Food pigeonHeart = Food.builder()
                .name("Pigeon Heart")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("1"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("30"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0.3"))
                .Calcium(new BigDecimal("0"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("23"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(pigeonHeart);

        Food pigeonKidneys = Food.builder()
                .name("Pigeon Kidneys")
                .calories(new BigDecimal("70"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("0.3"))
                .Calcium(new BigDecimal("2"))
                .Phosphorus(new BigDecimal("150"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("60"))
                .Potassium(new BigDecimal("160"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("1.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("22"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("13"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(pigeonKidneys);

        Food pigeonCarcass = Food.builder()
                .name("Pigeon Carcass")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("100"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("4"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("20"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("100"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("4"))
                .build();

        foodRepository.addFood(pigeonCarcass);

    }
}
