package org.food.repositories.MeatRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class ReptileRepository {
    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food snakeMeat = Food.builder()
                .name("Snake Meat")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("10"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("0.8"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("120"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("60"))
                .Potassium(new BigDecimal("250"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("20"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.5"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(snakeMeat);
        Food snakeLiver = Food.builder()
                .name("Snake Liver")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("1500"))
                .D(new BigDecimal("5"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("4"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("50"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("4"))
                .Phosphorus(new BigDecimal("190"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("3.5"))
                .build();

        foodRepository.addFood(snakeLiver);
        Food snakeEggs = Food.builder()
                .name("Snake Eggs")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("7"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("10"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("23"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(snakeEggs);
        Food snakeSkin = Food.builder()
                .name("Snake Skin")
                .calories(new BigDecimal("10"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0"))
                .B3(new BigDecimal("0"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("0"))
                .Phosphorus(new BigDecimal("0"))
                .Magnesium(new BigDecimal("0"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("0"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0"))
                .Zinc(new BigDecimal("0"))
                .Copper(new BigDecimal("0"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("0"))
                .Fat(new BigDecimal("0"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(snakeSkin);
        Food snakeFat = Food.builder()
                .name("Snake Fat")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("10"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("0.8"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("120"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("60"))
                .Potassium(new BigDecimal("250"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("20"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.5"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(snakeFat);
        Food turtleMeat = Food.builder()
                .name("Turtle Meat")
                .calories(new BigDecimal("80"))
                .A(new BigDecimal("100"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("8"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("170"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("160"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("22"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(turtleMeat);
        Food turtleEggs = Food.builder()
                .name("Turtle Eggs")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("7"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("10"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23"))
                .Protein(new BigDecimal("12"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(turtleEggs);
        Food crocodileTail = Food.builder()
                .name("Crocodile Tail")
                .calories(new BigDecimal("100"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("21"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(crocodileTail);
        Food crocodileLegs = Food.builder()
                .name("Crocodile Legs")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("60"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.3"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("1.5"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("220"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("23"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(crocodileLegs);
        Food crocodileBelly = Food.builder()
                .name("Crocodile Belly")
                .calories(new BigDecimal("110"))
                .A(new BigDecimal("40"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("220"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("22"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(crocodileBelly);
        Food crocodileLiver = Food.builder()
                .name("Crocodile Liver")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("300"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.3"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("4"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("50"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("4"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("3.5"))
                .build();

        foodRepository.addFood(crocodileLiver);
        Food crocodileHeart = Food.builder()
                .name("Crocodile Heart")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("60"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(crocodileHeart);
        Food crocodileKidneys = Food.builder()
                .name("Crocodile Kidneys")
                .calories(new BigDecimal("80"))
                .A(new BigDecimal("40"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(crocodileKidneys);
        Food alligatorMeat = Food.builder()
                .name("Alligator Meat")
                .calories(new BigDecimal("110"))
                .A(new BigDecimal("80"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("190"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("22"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(alligatorMeat);
        Food alligatorTail = Food.builder()
                .name("Alligator Tail")
                .calories(new BigDecimal("100"))
                .A(new BigDecimal("60"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("21"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(alligatorTail);
        Food alligatorRibs = Food.builder()
                .name("Alligator Ribs")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.3"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("220"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("21"))
                .Fat(new BigDecimal("9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("4"))
                .build();

        foodRepository.addFood(alligatorRibs);
        Food alligatorOffal = Food.builder()
                .name("Alligator Offal")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("40"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(alligatorOffal);
        Food alligatorLiver = Food.builder()
                .name("Alligator Liver")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("400"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0.3"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("4"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("15"))
                .B9(new BigDecimal("50"))
                .B12(new BigDecimal("0.4"))
                .Calcium(new BigDecimal("4"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("30"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("3.5"))
                .build();

        foodRepository.addFood(alligatorLiver);
        Food alligatorHeart = Food.builder()
                .name("Alligator Heart")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("60"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(alligatorHeart);
        Food alligatorKidneys = Food.builder()
                .name("Alligator Kidneys")
                .calories(new BigDecimal("80"))
                .A(new BigDecimal("40"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(alligatorKidneys);
        Food alligatorTongue = Food.builder()
                .name("Alligator Tongue")
                .calories(new BigDecimal("95"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0.2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("6"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("2"))
                .MonounsaturatedFat(new BigDecimal("3"))
                .build();

        foodRepository.addFood(alligatorTongue);

    }
}
