const chromium = {
    description:"Chromium is a mineral present in various foods whose exact role in the body remains partially understood by researchers. However, it is believed to potentially aid in the metabolism of carbohydrates, fats, and proteins. There are primarily two forms of chromium: chromium (III), which is naturally occurring in foods and certain supplements, and chromium (VI), also known as hexavalent chromium, which is a toxic byproduct of industrial processes. This summary focuses on chromium (III), emphasizing its presence in the diet and its speculated functions in human metabolism.",
    functions: {
        "Carbohydrate, lipid, and protein metabolism regulation": "Chromium, particularly in its trivalent form, may enhance insulin action, potentially influencing carbohydrate, lipid, and protein metabolism. The exact mechanism remains unclear, but it's suggested that chromium binds to an oligopeptide to form chromodulin, which activates insulin receptors, thus promoting insulin action.",
        "Antioxidant effects": "Chromium may exhibit antioxidant properties, although the extent and mechanism of this effect are not fully understood.",
    },
    sources: {
        "Food" : "Chromium is naturally present in a variety of foods, including meats, grains, fruits, vegetables, nuts, spices, brewer’s yeast, beer, and wine. However, the chromium content in these foods varies widely due to factors such as local soil and water conditions, agricultural practices, and manufacturing processes. Some chromium can also be introduced into foods from stainless steel equipment during processing and cooking. Dairy products and foods high in sugar tend to be low in chromium. Dietary absorption of chromium is relatively low, influenced by factors like ascorbic acid and prostaglandin inhibitors enhancing absorption, while oxalate and antacids inhibit it.",
        "Dietary Supplements" : "Most multivitamin/mineral supplements contain chromium, typically ranging from 35 to 120 mcg. There are also standalone chromium supplements available, offering doses of 200 mcg to 1,000 mcg. These supplements come in various forms such as chromium picolinate, chromium nicotinate, chromium polynicotinate, chromium chloride, and chromium histidinate. The absorption rates of these forms are similar, with chromium picolinate typically absorbed at about 1.2% and chromium chloride at about 0.4%. Chromium compounds vary in their elemental chromium content, with labels on dietary supplements indicating the amount of elemental chromium present."
    },
    dailyIntake: "Scientists previously considered chromium to be an essential nutrient, setting recommended daily amounts based on evidence available in 2001. However, current understanding suggests that chromium may not be necessary for good health, as deficiency hasn't been reported in healthy individuals. Chromium intake recommendations vary across different life stages, with infants needing as little as 0.2 micrograms per day and breastfeeding women requiring up to 45 micrograms daily. These recommendations reflect the average daily amounts established in 2001, indicating the diverse needs for chromium intake throughout various stages of life.",
    deficiency: "Not found from the sources.",
    res: ['https://ods.od.nih.gov/factsheets/chromium-Consumer/' , 'https://ods.od.nih.gov/factsheets/Chromium-HealthProfessional/']
};

export default chromium;
