const iodine = {
    description: "Iodine is a mineral essential for producing thyroid hormones, which regulate metabolism and various bodily functions. It plays a crucial role in bone and brain development, particularly during pregnancy and infancy. Adequate iodine intake is vital for overall health, particularly for pregnant women and infants.",
    functions: {
        "Thyroid Hormone Synthesis and Regulation": "Iodine is an essential component of thyroid hormones thyroxine (T4) and triiodothyronine (T3), which play a crucial role in regulating biochemical reactions, protein synthesis, enzymatic activity, and metabolic processes. These hormones are vital for proper skeletal and central nervous system development in fetuses and infants.",
        "Thyroid-Stimulating Hormone (TSH) Regulation": "The pituitary gland secretes thyroid-stimulating hormone (TSH) to control thyroid hormone production and secretion. Elevated TSH levels in response to insufficient iodine intake lead to goiter, indicating the body's attempt to increase iodine uptake and thyroid hormone synthesis.",
        "Immune Response and Other Physiological Functions": "Iodine may have additional physiological functions beyond thyroid hormone synthesis, including immune response modulation and potential benefits for mammary dysplasia and fibrocystic breast disease.",
        "Soil Composition and Food Iodine Content": "Varying iodine levels in the earth's soils affect the iodine content of crops, posing risks of iodine deficiency in regions with iodine-deficient soils. Salt iodization programs have significantly reduced iodine deficiency globally."
    },
    sources: {
        "Food": "Seaweed, fish, seafood, eggs, and dairy products are among the best food sources of iodine. While seaweed contains high levels of iodine, the iodine content in dairy products varies depending on factors like feed supplements and cleaning agents used in milk processing. Bread, particularly when made with iodate dough conditioners, contributes significantly to iodine intake. However, fruits, vegetables, and most plant-based beverages have lower iodine content unless grown in iodine-rich soil or processed with iodized salt.",
        "Salt Iodization Programs": "Many countries, including the United States and Canada, have implemented salt iodization programs to combat iodine deficiency. Iodine is added to table salt to ensure adequate intake, with potassium iodide and potassium iodate being common additives. However, iodized salt usage in processed foods varies, and specialty salts like sea salt are typically not iodized.",
        "Dietary Supplements": "Iodine is commonly found in dietary supplements as potassium iodide or sodium iodide, with some supplements containing kelp extracts rich in iodine. Multivitamin/mineral supplements often include iodine at recommended doses, while prenatal supplements may contain higher amounts to support maternal and fetal health. However, some dietary supplements may exceed the tolerable upper intake level (UL) for iodine, emphasizing the importance of moderation and adherence to recommended dosages."
    },
    dailyIntake: "The daily recommended intake of iodine varies depending on age and life stage. For infants, it ranges from 110 to 130 mcg per day during the first year. Children aged 1 to 8 years require about 90 mcg, while those aged 9 to 13 need around 120 mcg. Teenagers aged 14 to 18 should aim for 150 mcg daily. Adults, including pregnant and breastfeeding women, require 150 mcg, except for pregnant teens and women who need 220 mcg and breastfeeding teens and women who need 290 mcg.",
    deficiency: "Can lead to insufficient production of thyroid hormone. This deficiency can result in various complications. In pregnant women, severe iodine deficiency can harm the fetus, leading to stunted growth, intellectual disability, and delayed sexual development. Even mild deficiency can lower IQ in infants and children and impair cognitive function in adults, affecting their ability to work and think clearly. Additionally, goiter, characterized by an enlarged thyroid gland, is a common sign of iodine deficiency.",
    res: ['https://ods.od.nih.gov/factsheets/Iodine-Consumer/', 'https://ods.od.nih.gov/factsheets/Iodine-HealthProfessional/']
};

export default iodine;
