const iron = {
    description:"Iron is an essential mineral vital for the body's growth and development. It plays a crucial role in producing hemoglobin, a protein within red blood cells responsible for transporting oxygen from the lungs to tissues, and myoglobin, which delivers oxygen to muscles. Additionally, iron is necessary for synthesizing certain hormones, highlighting its importance in various physiological processes.",
    functions: {
        "Hemoglobin Production": "Iron is an essential component of hemoglobin, the protein in red blood cells responsible for transporting oxygen from the lungs to tissues.",
        "Muscle Metabolism" : "As a component of myoglobin, iron supports muscle metabolism by providing oxygen and contributes to healthy connective tissue.",
        "Neurological Development" : "Iron is necessary for neurological development, aiding in cognitive function and overall brain health.",
        "Cellular Functioning" : "Iron plays a crucial role in cellular functioning, facilitating various biochemical processes within cells.",
        "Hormone Synthesis" : "Iron is involved in the synthesis of certain hormones, contributing to hormonal balance and regulation in the body."
    },
    sources: {
        "Food": "Iron is naturally present in a variety of foods and is added to some fortified products. Rich sources of heme iron include lean meats and seafood, while nonheme iron is found in nuts, beans, vegetables, and fortified grain products. Wheat and other flours, as well as infant formulas, are commonly fortified with iron. Heme iron has higher bioavailability than nonheme iron, with dietary factors such as vitamin C enhancing absorption. Despite some plant-based foods being rich in iron, their bioavailability may be limited due to the presence of iron absorption inhibitors.",
        "Dietary Supplements" : "Iron is available in various dietary supplements, including multivitamin/mineral supplements and iron-only supplements. These supplements typically provide different forms of iron salts, such as ferrous sulfate, ferrous gluconate, and ferric citrate, with varying levels of elemental iron. High doses of supplemental iron may cause gastrointestinal side effects, and some forms of iron supplements might have fewer side effects than others. The simultaneous intake of calcium and iron supplements may interfere with iron absorption, leading to recommendations for separate timing of intake."
    },
    dailyIntake: "The recommended daily intake of iron varies based on factors like age, gender, and dietary preferences. For instance, infants aged 7-12 months require 11 mg, while teenage girls aged 14-18 need 15 mg. Adult men aged 19-50 typically need 8 mg, whereas women in the same age range require more at 18 mg due to menstrual losses. Pregnant and breastfeeding individuals have higher iron needs, with pregnant teens and women needing 27 mg and breastfeeding teens and women needing 10 mg and 9 mg, respectively. Vegetarians may require additional iron as nonheme iron from plant sources isn't as easily absorbed as heme iron from animal products.",
    deficiency: "When the body doesn't receive enough iron, especially over time, it can lead to iron deficiency anemia, a condition where red blood cells lack sufficient hemoglobin. This results in reduced oxygen transportation throughout the body, leading to symptoms like fatigue, weakness, and difficulty concentrating. Individuals with iron deficiency anemia may also experience decreased immunity, making them more susceptible to infections, and may struggle with physical activities and temperature regulation. Infants and children are particularly vulnerable, with potential impacts on learning and development. Iron deficiency is common, particularly among certain demographics like young children, women of childbearing age, and pregnant women, as well as those with dietary restrictions or underlying health conditions affecting nutrient absorption.",
    res: ['https://ods.od.nih.gov/factsheets/Iron-Consumer/' , 'https://ods.od.nih.gov/factsheets/Iron-HealthProfessional/']
};

export default iron;
