const nutritionUnits = {
  "Carbohydrate": "g",
  "Protein": "g",
  "Fat": "g",
  "Fiber": "g",
  "Sugar": "g",
  "Linoleic Acid": "g",
  "α-Linolenic Acid": "g",
  "Cholesterol": "mg",
  "Water": "ml",
  "Saturated Fat": "g",
  "Trans Fat": "g",
  "Vitamin A": "µg",
  "Vitamin D (D2 + D3)": "µg",
  "Vitamin E": "mg",
  "Vitamin K": "µg",
  "Vitamin C": "mg",
  "Vitamin B1 (Thiamin)": "mg",
  "Vitamin B2 (Riboflavin)": "mg",
  "Vitamin B3 (Niacin)": "mg",
  "Vitamin B5 (Pantothenic acid)": "mg",
  "Vitamin B6": "mg",
  "Vitamin B7 (Biotin)": "µg",
  "Vitamin B9 (Folate)": "µg",
  "Vitamin B12": "µg",
  "Choline": "mg",
  "Calcium , Ca": "mg",
  "Chromium , Cr": "µg",
  "Phosphorus , P": "mg",
  "Fluoride": "mg",
  "Chloride": "mg",
  "Magnesium , Mg": "mg",
  "Sodium , Na": "mg",
  "Potassium , K": "mg",
  "Iron , Fe": "mg",
  "Zinc , Zn": "mg",
  "Copper , Cu": "mg",
  "Manganese , Mn": "mg",
  "Iodine , I": "µg",
  "Selenium , Se": "µg",
  "Molybdenum , Mo": "µg"
};

export { nutritionUnits };