package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class FruitRepository {

    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food banana = Food.builder()
                .name("Banana")
                .calories(new BigDecimal("89"))
                .A(new BigDecimal("1"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("8.7"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.7"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("22"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("358"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1"))
                .Fluoride(new BigDecimal("2.2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("12"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(banana);
        Food apple = Food.builder()
                .name("Apple")
                .calories(new BigDecimal("52"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.18"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("0.5"))
                .B1(new BigDecimal("0.017"))
                .B2(new BigDecimal("0.026"))
                .B3(new BigDecimal("0.091"))
                .B5(new BigDecimal("0.043"))
                .B6(new BigDecimal("0.041"))
                .B7(new BigDecimal("0.009"))
                .B9(new BigDecimal("0.003"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("5"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("107"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.12"))
                .Zinc(new BigDecimal("0.05"))
                .Copper(new BigDecimal("0.05"))
                .Manganese(new BigDecimal("0.035"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14"))
                .Protein(new BigDecimal("0.3"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("10"))
                .PolyunsaturatedFat(new BigDecimal("0.03"))
                .MonounsaturatedFat(new BigDecimal("0.01"))
                .build();

        foodRepository.addFood(apple);
        Food grapes = Food.builder()
                .name("Grapes")
                .calories(new BigDecimal("69"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0.9"))
                .C(new BigDecimal("10.8"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.09"))
                .B9(new BigDecimal("2"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("20"))
                .Magnesium(new BigDecimal("7"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("191"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18"))
                .Protein(new BigDecimal("0.6"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("0.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("16"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(grapes);
        Food strawberries = Food.builder()
                .name("Strawberries")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0.9"))
                .C(new BigDecimal("58.8"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0.02"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("13"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("153"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("7.7"))
                .Protein(new BigDecimal("0.7"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("4.9"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(strawberries);
        Food melons = Food.builder()
                .name("Melons (Average)")
                .calories(new BigDecimal("34"))
                .A(new BigDecimal("28"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0.8"))
                .C(new BigDecimal("8.3"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.9"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("3"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("267"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.2"))
                .Protein(new BigDecimal("0.8"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("0.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("8.1"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(melons);
        Food avocados = Food.builder()
                .name("Avocado")
                .calories(new BigDecimal("160"))
                .A(new BigDecimal("7"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.1"))
                .K(new BigDecimal("14"))
                .C(new BigDecimal("9"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.7"))
                .B5(new BigDecimal("1"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0.09"))
                .B9(new BigDecimal("81"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("52"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("485"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.5"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("14.7"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.1"))
                .Sugar(new BigDecimal("0.7"))
                .PolyunsaturatedFat(new BigDecimal("1.8"))
                .MonounsaturatedFat(new BigDecimal("9.8"))
                .build();

        foodRepository.addFood(avocados);
        Food blueberries = Food.builder()
                .name("Blueberries")
                .calories(new BigDecimal("57"))
                .A(new BigDecimal("54"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("19"))
                .C(new BigDecimal("9.7"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0.02"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("12"))
                .Magnesium(new BigDecimal("6"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("77"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14.5"))
                .Protein(new BigDecimal("0.7"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("9.7"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(blueberries);
        Food mandarins = Food.builder()
                .name("Mandarins")
                .calories(new BigDecimal("53"))
                .A(new BigDecimal("34"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("13.3"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("43"))
                .Phosphorus(new BigDecimal("20"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("166"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13.3"))
                .Protein(new BigDecimal("1"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.03"))
                .Sugar(new BigDecimal("9.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(mandarins);
        Food oranges = Food.builder()
                .name("Oranges")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("11"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("53.2"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("30"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("43"))
                .Phosphorus(new BigDecimal("23"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("181"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.1"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.3"))
                .Protein(new BigDecimal("1"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2.2"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("8.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(oranges);
        Food peachesNectarinesPlums = Food.builder()
                .name("Peaches, Nectarines, Plums (Combined)")
                .calories(new BigDecimal("39"))
                .A(new BigDecimal("54"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("6"))
                .C(new BigDecimal("9.5"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0.02"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("16"))
                .Magnesium(new BigDecimal("7"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("157"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("9.9"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("1.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.01"))
                .Sugar(new BigDecimal("8.4"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(peachesNectarinesPlums);
        Food pineapples = Food.builder()
                .name("Pineapples")
                .calories(new BigDecimal("50"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("47.8"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("18"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("8"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("109"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("6"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13.1"))
                .Protein(new BigDecimal("0.5"))
                .Fat(new BigDecimal("0.1"))
                .Fiber(new BigDecimal("1.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("9.9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(pineapples);
        Food raspberries = Food.builder()
                .name("Raspberries")
                .calories(new BigDecimal("52"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("1.2"))
                .C(new BigDecimal("26.2"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("25"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("151"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("5"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("11.9"))
                .Protein(new BigDecimal("1.2"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("6.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("4.4"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(raspberries);
        Food cherries = Food.builder()
                .name("Cherries")
                .calories(new BigDecimal("63"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("2.1"))
                .C(new BigDecimal("12.5"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0.04"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("15"))
                .Magnesium(new BigDecimal("11"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("173"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.1"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2.1"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.03"))
                .Sugar(new BigDecimal("8.1"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(cherries);
        Food blackberries = Food.builder()
                .name("Blackberries")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.2"))
                .K(new BigDecimal("29"))
                .C(new BigDecimal("9.7"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("21"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("22"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("214"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("9.6"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("5.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("4.5"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(blackberries);
        Food kiwifruit = Food.builder()
                .name("Kiwifruit")
                .calories(new BigDecimal("61"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("92"))
                .C(new BigDecimal("92.7"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.03"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.06"))
                .B7(new BigDecimal("0.03"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("312"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14.6"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("8.9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(kiwifruit);
        Food watermelon = Food.builder()
                .name("Watermelon")
                .calories(new BigDecimal("30"))
                .A(new BigDecimal("569"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0.1"))
                .C(new BigDecimal("8.1"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("3"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("112"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("7.6"))
                .Protein(new BigDecimal("0.6"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("0.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.05"))
                .Sugar(new BigDecimal("6.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(watermelon);
        Food mangoes = Food.builder()
                .name("Mangoes")
                .calories(new BigDecimal("60"))
                .A(new BigDecimal("54"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("11"))
                .C(new BigDecimal("36.4"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.09"))
                .B9(new BigDecimal("43"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("14"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("168"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("5"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14.98"))
                .Protein(new BigDecimal("0.82"))
                .Fat(new BigDecimal("0.38"))
                .Fiber(new BigDecimal("1.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.092"))
                .Sugar(new BigDecimal("13.66"))
                .PolyunsaturatedFat(new BigDecimal("0.07"))
                .MonounsaturatedFat(new BigDecimal("0.09"))
                .build();

        foodRepository.addFood(mangoes);
        Food lemons = Food.builder()
                .name("Lemons")
                .calories(new BigDecimal("29"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("53"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("26"))
                .Phosphorus(new BigDecimal("16"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("138"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("9.3"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.04"))
                .Sugar(new BigDecimal("2.5"))
                .PolyunsaturatedFat(new BigDecimal("0.08"))
                .MonounsaturatedFat(new BigDecimal("0.03"))
                .build();

        foodRepository.addFood(lemons);
        Food limes = Food.builder()
                .name("Limes")
                .calories(new BigDecimal("30"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0.6"))
                .C(new BigDecimal("30.7"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("33"))
                .Phosphorus(new BigDecimal("18"))
                .Magnesium(new BigDecimal("6"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("102"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10.5"))
                .Protein(new BigDecimal("0.6"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.01"))
                .Sugar(new BigDecimal("1.7"))
                .PolyunsaturatedFat(new BigDecimal("0.07"))
                .MonounsaturatedFat(new BigDecimal("0.03"))
                .build();

        foodRepository.addFood(limes);
        Food grapefruits = Food.builder()
                .name("Grapefruits")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("25"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("16"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("8"))
                .Magnesium(new BigDecimal("6"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("135"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.1"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.1"))
                .Protein(new BigDecimal("0.6"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("1.1"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.01"))
                .Sugar(new BigDecimal("6.9"))
                .PolyunsaturatedFat(new BigDecimal("0.05"))
                .MonounsaturatedFat(new BigDecimal("0.03"))
                .build();

        foodRepository.addFood(grapefruits);
        Food pears = Food.builder()
                .name("Pears")
                .calories(new BigDecimal("57"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("4"))
                .C(new BigDecimal("12.1"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.04"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("1"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("12"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("119"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14.9"))
                .Protein(new BigDecimal("0.4"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("3.1"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.03"))
                .Sugar(new BigDecimal("9.8"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(pears);
        Food papaya = Food.builder()
                .name("Papaya")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("47"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("60.9"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.04"))
                .B7(new BigDecimal("0.01"))
                .B9(new BigDecimal("38"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("20"))
                .Phosphorus(new BigDecimal("5"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("8"))
                .Potassium(new BigDecimal("182"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10.8"))
                .Protein(new BigDecimal("0.5"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("1.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.08"))
                .Sugar(new BigDecimal("8.3"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.05"))
                .build();

        foodRepository.addFood(papaya);
        Food figs = Food.builder()
                .name("Figs")
                .calories(new BigDecimal("74"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("4.7"))
                .C(new BigDecimal("19.2"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.03"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0.02"))
                .B9(new BigDecimal("3"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("35"))
                .Phosphorus(new BigDecimal("67"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("232"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("2"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("19.2"))
                .Protein(new BigDecimal("0.8"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("16.3"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(figs);
        Food durian = Food.builder()
                .name("Durian")
                .calories(new BigDecimal("149"))
                .A(new BigDecimal("44"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.1"))
                .K(new BigDecimal("6"))
                .C(new BigDecimal("19.7"))
                .B1(new BigDecimal("0.37"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0.2"))
                .B9(new BigDecimal("36"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("39"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("436"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("3"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("27.1"))
                .Protein(new BigDecimal("2.2"))
                .Fat(new BigDecimal("5.3"))
                .Fiber(new BigDecimal("3.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("14.8"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("1.5"))
                .build();

        foodRepository.addFood(durian);
        Food dragonFruit = Food.builder()
                .name("Dragon Fruit")
                .calories(new BigDecimal("60"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.87"))
                .K(new BigDecimal("3.9"))
                .C(new BigDecimal("9"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.9"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("8"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("9"))
                .Potassium(new BigDecimal("229"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13"))
                .Protein(new BigDecimal("1.2"))
                .Fat(new BigDecimal("0.6"))
                .Fiber(new BigDecimal("3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("9"))
                .PolyunsaturatedFat(new BigDecimal("0.04"))
                .MonounsaturatedFat(new BigDecimal("0.15"))
                .build();

        foodRepository.addFood(dragonFruit);
        Food starfruit = Food.builder()
                .name("Starfruit")
                .calories(new BigDecimal("31"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("2.8"))
                .C(new BigDecimal("34"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.01"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.01"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("3"))
                .Phosphorus(new BigDecimal("12"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("133"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.1"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("6.3"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.02"))
                .Sugar(new BigDecimal("3.9"))
                .PolyunsaturatedFat(new BigDecimal("0.02"))
                .MonounsaturatedFat(new BigDecimal("0.04"))
                .build();

        foodRepository.addFood(starfruit);
        Food rambutan = Food.builder()
                .name("Rambutan")
                .calories(new BigDecimal("68"))
                .A(new BigDecimal("20"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.35"))
                .K(new BigDecimal("42.2"))
                .C(new BigDecimal("20.9"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.35"))
                .B5(new BigDecimal("0.35"))
                .B6(new BigDecimal("0.02"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("21"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("20"))
                .Magnesium(new BigDecimal("42"))
                .Sodium(new BigDecimal("11"))
                .Potassium(new BigDecimal("42"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.35"))
                .Zinc(new BigDecimal("0.35"))
                .Copper(new BigDecimal("0.35"))
                .Manganese(new BigDecimal("0.35"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.5"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("0.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.03"))
                .Sugar(new BigDecimal("9.6"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.04"))
                .build();

        foodRepository.addFood(rambutan);
        Food jackfruit = Food.builder()
                .name("Jackfruit")
                .calories(new BigDecimal("95"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.34"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("23"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.11"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("24"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("21"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("448"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("10"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("24"))
                .Protein(new BigDecimal("2.5"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.07"))
                .Sugar(new BigDecimal("19"))
                .PolyunsaturatedFat(new BigDecimal("0.09"))
                .MonounsaturatedFat(new BigDecimal("0.03"))
                .build();

        foodRepository.addFood(jackfruit);
        Food mangosteen = Food.builder()
                .name("Mangosteen")
                .calories(new BigDecimal("73"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("12"))
                .C(new BigDecimal("2.9"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("0.25"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.02"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("13"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("9"))
                .Magnesium(new BigDecimal("13"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("48"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.35"))
                .Zinc(new BigDecimal("0.12"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.16"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.8"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("16.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(mangosteen);
        Food lychee = Food.builder()
                .name("Lychee")
                .calories(new BigDecimal("66"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0.4"))
                .C(new BigDecimal("136"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.01"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("14"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("31"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("171"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.5"))
                .Protein(new BigDecimal("0.8"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("1.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("9.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(lychee);
        Food guava = Food.builder()
                .name("Guava")
                .calories(new BigDecimal("68"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("2.6"))
                .C(new BigDecimal("228"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("49"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("18"))
                .Phosphorus(new BigDecimal("22"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("417"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("5.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(guava);
        Food custardApple = Food.builder()
                .name("Custard Apple")
                .calories(new BigDecimal("101"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("23"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.11"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("27"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("4"))
                .Potassium(new BigDecimal("247"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("9"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("25.2"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("0.6"))
                .Fiber(new BigDecimal("3.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("20.8"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(custardApple);
        Food soursop = Food.builder()
                .name("Soursop")
                .calories(new BigDecimal("66"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("20.6"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.07"))
                .B6(new BigDecimal("0.06"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("14"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("14"))
                .Phosphorus(new BigDecimal("27"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("14"))
                .Potassium(new BigDecimal("278"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("9"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.8"))
                .Protein(new BigDecimal("2.1"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("3.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("13.5"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(soursop);
        Food cherimoya = Food.builder()
                .name("Cherimoya")
                .calories(new BigDecimal("75"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("15.7"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("23"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("7"))
                .Phosphorus(new BigDecimal("26"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("287"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("8"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("17.7"))
                .Protein(new BigDecimal("1.7"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("9.5"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(cherimoya);
        Food atemoya = Food.builder()
                .name("Atemoya")
                .calories(new BigDecimal("73"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("21"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("17"))
                .Phosphorus(new BigDecimal("21"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("287"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("9"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("17.7"))
                .Protein(new BigDecimal("1.7"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("9.5"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(atemoya);
        Food breadfruit = Food.builder()
                .name("Breadfruit")
                .calories(new BigDecimal("103"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("17"))
                .C(new BigDecimal("29"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("17"))
                .Phosphorus(new BigDecimal("30"))
                .Magnesium(new BigDecimal("25"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("490"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("9"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("27.1"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("4.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("11.3"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(breadfruit);
        Food passionFruit = Food.builder()
                .name("Passion Fruit")
                .calories(new BigDecimal("97"))
                .A(new BigDecimal("1270"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("2.2"))
                .C(new BigDecimal("30"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("14"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("68"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("28"))
                .Potassium(new BigDecimal("348"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("10"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23.4"))
                .Protein(new BigDecimal("2.2"))
                .Fat(new BigDecimal("5.4"))
                .Fiber(new BigDecimal("10.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.4"))
                .Sugar(new BigDecimal("11.2"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("2.2"))
                .build();

        foodRepository.addFood(passionFruit);
        Food gooseberries = Food.builder()
                .name("Gooseberries")
                .calories(new BigDecimal("44"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("41"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.05"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("25"))
                .Phosphorus(new BigDecimal("46"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("198"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.6"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10.2"))
                .Protein(new BigDecimal("1.6"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("4.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("7.7"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(gooseberries);
        Food pomegranate = Food.builder()
                .name("Pomegranate")
                .calories(new BigDecimal("83"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("16.4"))
                .C(new BigDecimal("10.2"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("10"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("236"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.7"))
                .Protein(new BigDecimal("1.7"))
                .Fat(new BigDecimal("1.2"))
                .Fiber(new BigDecimal("4.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("9.2"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(pomegranate);
        Food persimmon = Food.builder()
                .name("Persimmon")
                .calories(new BigDecimal("81"))
                .A(new BigDecimal("81"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("2.0"))
                .C(new BigDecimal("66"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("8"))
                .Phosphorus(new BigDecimal("17"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("310"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("5"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.6"))
                .Protein(new BigDecimal("0.6"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("3.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("12.5"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(persimmon);
        Food kiwiberry = Food.builder()
                .name("Kiwiberry")
                .calories(new BigDecimal("61"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("6"))
                .C(new BigDecimal("92"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("25"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("312"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("5"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14.6"))
                .Protein(new BigDecimal("1.1"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("5.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("8.9"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(kiwiberry);
        Food kumquat = Food.builder()
                .name("Kumquat")
                .calories(new BigDecimal("71"))
                .A(new BigDecimal("135"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("43.9"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("16"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("62"))
                .Phosphorus(new BigDecimal("19"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("10"))
                .Potassium(new BigDecimal("186"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.9"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("15.9"))
                .Protein(new BigDecimal("1.9"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("6.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("9.4"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(kumquat);
        Food noni = Food.builder()
                .name("Noni")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("620"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("8.3"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("70"))
                .Phosphorus(new BigDecimal("20"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("10"))
                .Potassium(new BigDecimal("350"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0"))
                .Sugar(new BigDecimal("8"))
                .PolyunsaturatedFat(new BigDecimal("0"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(noni);
        Food physalis = Food.builder()
                .name("Physalis")
                .calories(new BigDecimal("50"))
                .A(new BigDecimal("54"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("43"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("34"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("421"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("10"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("11"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("4.4"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(physalis);
        Food carambola = Food.builder()
                .name("Carambola")
                .calories(new BigDecimal("31"))
                .A(new BigDecimal("3"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("2.8"))
                .C(new BigDecimal("6.7"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.02"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("3"))
                .Phosphorus(new BigDecimal("12"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("133"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.1"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("6.3"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("3.9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(carambola);
        Food tamarind = Food.builder()
                .name("Tamarind")
                .calories(new BigDecimal("239"))
                .A(new BigDecimal("18"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("3.5"))
                .C(new BigDecimal("36"))
                .B1(new BigDecimal("0.43"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("14"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("74"))
                .Phosphorus(new BigDecimal("28"))
                .Magnesium(new BigDecimal("92"))
                .Sodium(new BigDecimal("28"))
                .Potassium(new BigDecimal("628"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.9"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("62.5"))
                .Protein(new BigDecimal("2.8"))
                .Fat(new BigDecimal("0.6"))
                .Fiber(new BigDecimal("5.1"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.6"))
                .Sugar(new BigDecimal("57.9"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(tamarind);
        Food kaffirLime = Food.builder()
                .name("Kaffir Lime")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("43.9"))
                .C(new BigDecimal("8.5"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("33"))
                .Phosphorus(new BigDecimal("34"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("4"))
                .Potassium(new BigDecimal("80"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.4"))
                .Protein(new BigDecimal("1.0"))
                .Fat(new BigDecimal("0.6"))
                .Fiber(new BigDecimal("1.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(kaffirLime);
        Food bitterMelon = Food.builder()
                .name("Bitter Melon")
                .calories(new BigDecimal("17"))
                .A(new BigDecimal("471"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("93"))
                .C(new BigDecimal("33"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("19"))
                .Phosphorus(new BigDecimal("21"))
                .Magnesium(new BigDecimal("18"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("296"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.8"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.7"))
                .Protein(new BigDecimal("1.0"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("2.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.9"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(bitterMelon);

        Food lucuma = Food.builder()
                .name("Lucuma")
                .calories(new BigDecimal("87"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("2"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("19"))
                .Phosphorus(new BigDecimal("42"))
                .Magnesium(new BigDecimal("31"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("186"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("14"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("22"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("1.4"))
                .Fiber(new BigDecimal("2.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("3.6"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(lucuma);

    }
}
