package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class GrainRepository {

    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        // Rice
        Food rice = Food.builder()
                .name("Rice")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("1.1"))
                .B6(new BigDecimal("0.16"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("1"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("108"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("35"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.2"))
                .Protein(new BigDecimal("2.7"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("0.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.07"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.12"))
                .MonounsaturatedFat(new BigDecimal("0.07"))
                .build();

        foodRepository.addFood(rice);

        // Wheat
        Food wheat = Food.builder()
                .name("Wheat")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.41"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.11"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("28"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("123"))
                .Magnesium(new BigDecimal("138"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("363"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.9"))
                .Zinc(new BigDecimal("3.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("3.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("70.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.2"))
                .Protein(new BigDecimal("11.3"))
                .Fat(new BigDecimal("1.7"))
                .Fiber(new BigDecimal("12.2"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.28"))
                .Sugar(new BigDecimal("1.5"))
                .PolyunsaturatedFat(new BigDecimal("0.8"))
                .MonounsaturatedFat(new BigDecimal("0.21"))
                .build();

        foodRepository.addFood(wheat);
        // Corn
        Food corn = Food.builder()
                .name("Corn")
                .calories(new BigDecimal("96"))
                .A(new BigDecimal("9"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.54"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("9.7"))
                .B1(new BigDecimal("0.28"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("2.3"))
                .B5(new BigDecimal("1.1"))
                .B6(new BigDecimal("0.31"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("27"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("2"))
                .Phosphorus(new BigDecimal("89"))
                .Magnesium(new BigDecimal("37"))
                .Sodium(new BigDecimal("15"))
                .Potassium(new BigDecimal("270"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("19.7"))
                .Protein(new BigDecimal("2.7"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("2.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.18"))
                .Sugar(new BigDecimal("6.3"))
                .PolyunsaturatedFat(new BigDecimal("0.65"))
                .MonounsaturatedFat(new BigDecimal("0.36"))
                .build();

        foodRepository.addFood(corn);

        // Sorghum
        Food sorghum = Food.builder()
                .name("Sorghum")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.29"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("8.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.38"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("27"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("26"))
                .Phosphorus(new BigDecimal("287"))
                .Magnesium(new BigDecimal("165"))
                .Sodium(new BigDecimal("6"))
                .Potassium(new BigDecimal("350"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.4"))
                .Zinc(new BigDecimal("2.7"))
                .Copper(new BigDecimal("0.5"))
                .Manganese(new BigDecimal("3.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("23.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("72.1"))
                .Protein(new BigDecimal("11"))
                .Fat(new BigDecimal("3.3"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("0.6"))
                .PolyunsaturatedFat(new BigDecimal("1.2"))
                .MonounsaturatedFat(new BigDecimal("1"))
                .build();

        foodRepository.addFood(sorghum);
        // Barley
        Food barley = Food.builder()
                .name("Barley")
                .calories(new BigDecimal("354"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.63"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("17.3"))
                .B1(new BigDecimal("0.24"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.6"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("19"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("221"))
                .Magnesium(new BigDecimal("79"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("280"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.6"))
                .Zinc(new BigDecimal("2.8"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.8"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("22.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.5"))
                .Protein(new BigDecimal("12.5"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("17.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.36"))
                .Sugar(new BigDecimal("0.6"))
                .PolyunsaturatedFat(new BigDecimal("0.82"))
                .MonounsaturatedFat(new BigDecimal("0.47"))
                .build();

        foodRepository.addFood(barley);

        // Oats
        Food oats = Food.builder()
                .name("Oats")
                .calories(new BigDecimal("389"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.54"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.76"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.9"))
                .B5(new BigDecimal("1.3"))
                .B6(new BigDecimal("0.12"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("56"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("54"))
                .Phosphorus(new BigDecimal("523"))
                .Magnesium(new BigDecimal("177"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("429"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.7"))
                .Zinc(new BigDecimal("4"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("4.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("34"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("66.3"))
                .Protein(new BigDecimal("16.9"))
                .Fat(new BigDecimal("6.9"))
                .Fiber(new BigDecimal("10.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.23"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("3.4"))
                .MonounsaturatedFat(new BigDecimal("1.4"))
                .build();

        foodRepository.addFood(oats);
        // Millet
        Food millet = Food.builder()
                .name("Millet")
                .calories(new BigDecimal("378"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.09"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("8.7"))
                .B1(new BigDecimal("0.09"))
                .B2(new BigDecimal("0.18"))
                .B3(new BigDecimal("1.8"))
                .B5(new BigDecimal("0.8"))
                .B6(new BigDecimal("0.38"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("8"))
                .Phosphorus(new BigDecimal("285"))
                .Magnesium(new BigDecimal("114"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("195"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.9"))
                .Zinc(new BigDecimal("1.9"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("1.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.6"))
                .Protein(new BigDecimal("11"))
                .Fat(new BigDecimal("4"))
                .Fiber(new BigDecimal("8.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.7"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("1.5"))
                .MonounsaturatedFat(new BigDecimal("1.3"))
                .build();

        foodRepository.addFood(millet);

        // Rye
        Food rye = Food.builder()
                .name("Rye")
                .calories(new BigDecimal("338"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.63"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("19.5"))
                .B1(new BigDecimal("0.06"))
                .B2(new BigDecimal("0.16"))
                .B3(new BigDecimal("3.9"))
                .B5(new BigDecimal("0.8"))
                .B6(new BigDecimal("0.21"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("24"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("332"))
                .Magnesium(new BigDecimal("121"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.7"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("5.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("21.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("72"))
                .Protein(new BigDecimal("9.4"))
                .Fat(new BigDecimal("1.6"))
                .Fiber(new BigDecimal("15.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.23"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.79"))
                .MonounsaturatedFat(new BigDecimal("0.27"))
                .build();

        foodRepository.addFood(rye);
        // Amaranth
        Food amaranth = Food.builder()
                .name("Amaranth")
                .calories(new BigDecimal("371"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.46"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("29"))
                .B1(new BigDecimal("0.09"))
                .B2(new BigDecimal("0.14"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.12"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("82"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("159"))
                .Phosphorus(new BigDecimal("557"))
                .Magnesium(new BigDecimal("248"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("508"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("15.7"))
                .Zinc(new BigDecimal("2.7"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("2.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("65"))
                .Protein(new BigDecimal("14"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("1.7"))
                .PolyunsaturatedFat(new BigDecimal("2.6"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(amaranth);

        // Quinoa
        Food quinoa = Food.builder()
                .name("Quinoa")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.49"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("23.9"))
                .B1(new BigDecimal("0.18"))
                .B2(new BigDecimal("0.18"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.12"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("49"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("47"))
                .Phosphorus(new BigDecimal("457"))
                .Magnesium(new BigDecimal("197"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("563"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.6"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("2.8"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("21.3"))
                .Protein(new BigDecimal("4.4"))
                .Fat(new BigDecimal("1.9"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.23"))
                .Sugar(new BigDecimal("0.9"))
                .PolyunsaturatedFat(new BigDecimal("1.67"))
                .MonounsaturatedFat(new BigDecimal("0.59"))
                .build();

        foodRepository.addFood(quinoa);
        // Teff
        Food teff = Food.builder()
                .name("Teff")
                .calories(new BigDecimal("367"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.09"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("73"))
                .B1(new BigDecimal("0.13"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.12"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("51"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("180"))
                .Phosphorus(new BigDecimal("369"))
                .Magnesium(new BigDecimal("184"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("427"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("7.6"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.7"))
                .Manganese(new BigDecimal("2.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73"))
                .Protein(new BigDecimal("13.3"))
                .Fat(new BigDecimal("2.4"))
                .Fiber(new BigDecimal("8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.1"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(teff);

        // Buckwheat
        Food buckwheat = Food.builder()
                .name("Buckwheat")
                .calories(new BigDecimal("343"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("18"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.01"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.19"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("54"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("18"))
                .Phosphorus(new BigDecimal("347"))
                .Magnesium(new BigDecimal("231"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("460"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.5"))
                .Protein(new BigDecimal("13.3"))
                .Fat(new BigDecimal("3.4"))
                .Fiber(new BigDecimal("10"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.6"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("1.1"))
                .build();

        foodRepository.addFood(buckwheat);
        // Spelt
        Food spelt = Food.builder()
                .name("Spelt")
                .calories(new BigDecimal("338"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.77"))
                .K(new BigDecimal("6"))
                .C(new BigDecimal("71.2"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("28"))
                .Phosphorus(new BigDecimal("401"))
                .Magnesium(new BigDecimal("136"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("374"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.2"))
                .Zinc(new BigDecimal("2.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.2"))
                .Protein(new BigDecimal("14.6"))
                .Fat(new BigDecimal("2.4"))
                .Fiber(new BigDecimal("10.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(spelt);

        // Freekeh
        Food freekeh = Food.builder()
                .name("Freekeh")
                .calories(new BigDecimal("347"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.32"))
                .K(new BigDecimal("210"))
                .C(new BigDecimal("71"))
                .B1(new BigDecimal("0.26"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("1.9"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.13"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("36"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("37"))
                .Phosphorus(new BigDecimal("427"))
                .Magnesium(new BigDecimal("130"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("560"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.4"))
                .Zinc(new BigDecimal("2.6"))
                .Copper(new BigDecimal("0.5"))
                .Manganese(new BigDecimal("3.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("6.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.5"))
                .Protein(new BigDecimal("16.5"))
                .Fat(new BigDecimal("2.7"))
                .Fiber(new BigDecimal("13.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("1.3"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(freekeh);
        // Farro
        Food farro = Food.builder()
                .name("Farro")
                .calories(new BigDecimal("340"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("20"))
                .C(new BigDecimal("73"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("28"))
                .Phosphorus(new BigDecimal("401"))
                .Magnesium(new BigDecimal("136"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("374"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.2"))
                .Zinc(new BigDecimal("2.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.2"))
                .Protein(new BigDecimal("14.6"))
                .Fat(new BigDecimal("2.4"))
                .Fiber(new BigDecimal("10.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(farro);

        // Triticale
        Food triticale = Food.builder()
                .name("Triticale")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.63"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("19.5"))
                .B1(new BigDecimal("0.06"))
                .B2(new BigDecimal("0.16"))
                .B3(new BigDecimal("3.9"))
                .B5(new BigDecimal("0.8"))
                .B6(new BigDecimal("0.21"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("24"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("332"))
                .Magnesium(new BigDecimal("121"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.7"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("5.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("21.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("72"))
                .Protein(new BigDecimal("9.4"))
                .Fat(new BigDecimal("1.6"))
                .Fiber(new BigDecimal("15.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.23"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.79"))
                .MonounsaturatedFat(new BigDecimal("0.27"))
                .build();

        foodRepository.addFood(triticale);
        // Kamut
        Food kamut = Food.builder()
                .name("Kamut")
                .calories(new BigDecimal("337"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.86"))
                .K(new BigDecimal("12"))
                .C(new BigDecimal("71"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("451"))
                .Magnesium(new BigDecimal("122"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("405"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.5"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(kamut);

        // Einkorn
        Food einkorn = Food.builder()
                .name("Einkorn")
                .calories(new BigDecimal("320"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.57"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("68"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.07"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("49"))
                .Phosphorus(new BigDecimal("297"))
                .Magnesium(new BigDecimal("44"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("298"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("3.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("14.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.5"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(einkorn);
        // Khorasan Wheat
        Food khorasanWheat = Food.builder()
                .name("Khorasan Wheat")
                .calories(new BigDecimal("337"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.56"))
                .K(new BigDecimal("23"))
                .C(new BigDecimal("70"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("451"))
                .Magnesium(new BigDecimal("122"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("405"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.5"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(khorasanWheat);

        // Durum Wheat
        Food durumWheat = Food.builder()
                .name("Durum Wheat")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.63"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("19.5"))
                .B1(new BigDecimal("0.06"))
                .B2(new BigDecimal("0.16"))
                .B3(new BigDecimal("3.9"))
                .B5(new BigDecimal("0.8"))
                .B6(new BigDecimal("0.21"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("24"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("332"))
                .Magnesium(new BigDecimal("121"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.7"))
                .Zinc(new BigDecimal("3.2"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("5.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("21.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("72"))
                .Protein(new BigDecimal("9.4"))
                .Fat(new BigDecimal("1.6"))
                .Fiber(new BigDecimal("15.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.23"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.79"))
                .MonounsaturatedFat(new BigDecimal("0.27"))
                .build();

        foodRepository.addFood(durumWheat);
        // Semolina
        Food semolina = Food.builder()
                .name("Semolina")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.11"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("73"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("451"))
                .Magnesium(new BigDecimal("122"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("405"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.5"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(semolina);

        // Bulgur Wheat
        Food bulgurWheat = Food.builder()
                .name("Bulgur Wheat")
                .calories(new BigDecimal("83"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.09"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("18.6"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.08"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("33"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("77"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.6"))
                .Protein(new BigDecimal("3"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("4.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.05"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(bulgurWheat);
        // Brown Rice
        Food brownRice = Food.builder()
                .name("Brown Rice")
                .calories(new BigDecimal("111"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.42"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("23"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1.8"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("23"))
                .Phosphorus(new BigDecimal("208"))
                .Magnesium(new BigDecimal("43"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("143"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1.2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11"))
                .Fluoride(new BigDecimal("1.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23.5"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("1.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(brownRice);

        // Basmati Rice
        Food basmatiRice = Food.builder()
                .name("Basmati Rice")
                .calories(new BigDecimal("121"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.07"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("25"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("115"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("76"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11"))
                .Fluoride(new BigDecimal("0.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("25.2"))
                .Protein(new BigDecimal("2.2"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("0.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(basmatiRice);
        // Jasmine Rice
        Food jasmineRice = Food.builder()
                .name("Jasmine Rice")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.07"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("28"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1.2"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("68"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("35"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11"))
                .Fluoride(new BigDecimal("0.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.2"))
                .Protein(new BigDecimal("2.2"))
                .Fat(new BigDecimal("0.1"))
                .Fiber(new BigDecimal("0.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(jasmineRice);

        // Arborio Rice
        Food arborioRice = Food.builder()
                .name("Arborio Rice")
                .calories(new BigDecimal("130"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.07"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("28"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1.2"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("68"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("35"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11"))
                .Fluoride(new BigDecimal("0.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.2"))
                .Protein(new BigDecimal("2.2"))
                .Fat(new BigDecimal("0.1"))
                .Fiber(new BigDecimal("0.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(arborioRice);
        // Wild Rice
        Food wildRice = Food.builder()
                .name("Wild Rice")
                .calories(new BigDecimal("101"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.07"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("21"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("155"))
                .Magnesium(new BigDecimal("26"))
                .Sodium(new BigDecimal("6"))
                .Potassium(new BigDecimal("166"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.7"))
                .Fluoride(new BigDecimal("0.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("21.3"))
                .Protein(new BigDecimal("3.9"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(wildRice);

        // Black Rice
        Food blackRice = Food.builder()
                .name("Black Rice")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.11"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("73"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("4.4"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.32"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("40"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("451"))
                .Magnesium(new BigDecimal("122"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("405"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.5"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(blackRice);
        // Red Rice
        Food redRice = Food.builder()
                .name("Red Rice")
                .calories(new BigDecimal("110"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.13"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("23"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("4"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("5"))
                .Phosphorus(new BigDecimal("111"))
                .Magnesium(new BigDecimal("44"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("139"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("12.7"))
                .Fluoride(new BigDecimal("0.1"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("22.5"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(redRice);

        // Wild Oats
        Food wildOats = Food.builder()
                .name("Wild Oats")
                .calories(new BigDecimal("389"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.53"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("66"))
                .B1(new BigDecimal("0.76"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("3.9"))
                .B5(new BigDecimal("1.3"))
                .B6(new BigDecimal("0.12"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("56"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("54"))
                .Phosphorus(new BigDecimal("177"))
                .Magnesium(new BigDecimal("177"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("429"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.7"))
                .Zinc(new BigDecimal("4.9"))
                .Copper(new BigDecimal("0.7"))
                .Manganese(new BigDecimal("4.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("6.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("67"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("10"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.4"))
                .Sugar(new BigDecimal("1.1"))
                .PolyunsaturatedFat(new BigDecimal("2.7"))
                .MonounsaturatedFat(new BigDecimal("1.9"))
                .build();

        foodRepository.addFood(wildOats);
        // Steel-Cut Oats
        Food steelCutOats = Food.builder()
                .name("Steel-Cut Oats")
                .calories(new BigDecimal("68"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.48"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("14"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("1.3"))
                .B6(new BigDecimal("0.06"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("54"))
                .Phosphorus(new BigDecimal("101"))
                .Magnesium(new BigDecimal("37"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("69"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.4"))
                .Zinc(new BigDecimal("1.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("7.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("12.5"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("1.4"))
                .Fiber(new BigDecimal("1.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.5"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(steelCutOats);

        // Pearl Barley
        Food pearlBarley = Food.builder()
                .name("Pearl Barley")
                .calories(new BigDecimal("123"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.24"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("28"))
                .B1(new BigDecimal("0.09"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("19"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("93"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("155"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.3"))
                .Protein(new BigDecimal("2.3"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("4.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.2"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(pearlBarley);
        // Rolled Barley
        Food rolledBarley = Food.builder()
                .name("Rolled Barley")
                .calories(new BigDecimal("82"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.25"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("17"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("1"))
                .B6(new BigDecimal("0.07"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("26"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("77"))
                .Magnesium(new BigDecimal("33"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("152"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.3"))
                .Zinc(new BigDecimal("0.7"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("9.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.6"))
                .Protein(new BigDecimal("2.3"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("3.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(rolledBarley);

        // Cracked Barley
        Food crackedBarley = Food.builder()
                .name("Cracked Barley")
                .calories(new BigDecimal("123"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.24"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("28"))
                .B1(new BigDecimal("0.09"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("19"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("93"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("155"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11.5"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.3"))
                .Protein(new BigDecimal("2.3"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("4.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.2"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(crackedBarley);
        // Amaranth Flakes
        Food amaranthFlakes = Food.builder()
                .name("Amaranth Flakes")
                .calories(new BigDecimal("375"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("65"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("0.7"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("65"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("159"))
                .Phosphorus(new BigDecimal("265"))
                .Magnesium(new BigDecimal("84"))
                .Sodium(new BigDecimal("19"))
                .Potassium(new BigDecimal("508"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.5"))
                .Zinc(new BigDecimal("3.3"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("2.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("69.4"))
                .Protein(new BigDecimal("14.5"))
                .Fat(new BigDecimal("7.0"))
                .Fiber(new BigDecimal("7.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.2"))
                .Sugar(new BigDecimal("1.3"))
                .PolyunsaturatedFat(new BigDecimal("2.9"))
                .MonounsaturatedFat(new BigDecimal("1.8"))
                .build();

        foodRepository.addFood(amaranthFlakes);

        // Quinoa Flakes
        Food quinoaFlakes = Food.builder()
                .name("Quinoa Flakes")
                .calories(new BigDecimal("370"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("4.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("64"))
                .B1(new BigDecimal("0.4"))
                .B2(new BigDecimal("0.18"))
                .B3(new BigDecimal("1.1"))
                .B5(new BigDecimal("0.7"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("184"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("45"))
                .Phosphorus(new BigDecimal("410"))
                .Magnesium(new BigDecimal("197"))
                .Sodium(new BigDecimal("11"))
                .Potassium(new BigDecimal("563"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.6"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("2.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("6.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("68.9"))
                .Protein(new BigDecimal("14.1"))
                .Fat(new BigDecimal("6.1"))
                .Fiber(new BigDecimal("7.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.6"))
                .Sugar(new BigDecimal("1.1"))
                .PolyunsaturatedFat(new BigDecimal("3.0"))
                .MonounsaturatedFat(new BigDecimal("1.9"))
                .build();

        foodRepository.addFood(quinoaFlakes);
        // Teff Flour
        Food teffFlour = Food.builder()
                .name("Teff Flour")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("3.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("71"))
                .B1(new BigDecimal("0.4"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("57"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("180"))
                .Phosphorus(new BigDecimal("175"))
                .Magnesium(new BigDecimal("184"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("427"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("7.6"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("2.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.5"))
                .Protein(new BigDecimal("13.3"))
                .Fat(new BigDecimal("2.4"))
                .Fiber(new BigDecimal("8.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("2.2"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("0.6"))
                .build();

        foodRepository.addFood(teffFlour);

        // Buckwheat Flour
        Food buckwheatFlour = Food.builder()
                .name("Buckwheat Flour")
                .calories(new BigDecimal("335"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("71"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("30"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("18"))
                .Phosphorus(new BigDecimal("298"))
                .Magnesium(new BigDecimal("231"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("460"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.3"))
                .Zinc(new BigDecimal("2.0"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("1.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("5.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.6"))
                .Protein(new BigDecimal("12.6"))
                .Fat(new BigDecimal("3.1"))
                .Fiber(new BigDecimal("10.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.7"))
                .Sugar(new BigDecimal("0.6"))
                .PolyunsaturatedFat(new BigDecimal("1.0"))
                .MonounsaturatedFat(new BigDecimal("0.6"))
                .build();

        foodRepository.addFood(buckwheatFlour);
        // Spelt Flour
        Food speltFlour = Food.builder()
                .name("Spelt Flour")
                .calories(new BigDecimal("338"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("70"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("28"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("30"))
                .Phosphorus(new BigDecimal("194"))
                .Magnesium(new BigDecimal("71"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("401"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.4"))
                .Zinc(new BigDecimal("2.4"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("3.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.2"))
                .Protein(new BigDecimal("15.6"))
                .Fat(new BigDecimal("1.7"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(speltFlour);

        // Freekeh Flour
        Food freekehFlour = Food.builder()
                .name("Freekeh Flour")
                .calories(new BigDecimal("340"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.49"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("63"))
                .B1(new BigDecimal("0.13"))
                .B2(new BigDecimal("0.08"))
                .B3(new BigDecimal("1.5"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.11"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("37"))
                .Phosphorus(new BigDecimal("294"))
                .Magnesium(new BigDecimal("79"))
                .Sodium(new BigDecimal("17"))
                .Potassium(new BigDecimal("384"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.3"))
                .Zinc(new BigDecimal("2.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("1.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.4"))
                .Protein(new BigDecimal("15.5"))
                .Fat(new BigDecimal("1.7"))
                .Fiber(new BigDecimal("12.9"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.8"))
                .PolyunsaturatedFat(new BigDecimal("0.8"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(freekehFlour);

    }
}
