package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class LegumeRepository {
    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        // Lentils
Food lentils = Food.builder()
        .name("Lentils")
        .calories(new BigDecimal("116"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("7.9"))
        .B1(new BigDecimal("0.5"))
        .B2(new BigDecimal("0.2"))
        .B3(new BigDecimal("1.1"))
        .B5(new BigDecimal("1.5"))
        .B6(new BigDecimal("0.4"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("40"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("451"))
        .Magnesium(new BigDecimal("36"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("369"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("3.3"))
        .Zinc(new BigDecimal("2.5"))
        .Copper(new BigDecimal("0.5"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.5"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("20.1"))
        .Protein(new BigDecimal("9"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("7.9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.8"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(lentils);

// Chickpeas
Food chickpeas = Food.builder()
        .name("Chickpeas")
        .calories(new BigDecimal("164"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.6"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("27.4"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("1.5"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("71"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("49"))
        .Phosphorus(new BigDecimal("168"))
        .Magnesium(new BigDecimal("48"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("291"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.9"))
        .Zinc(new BigDecimal("1.5"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("1.7"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("4.8"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("27.4"))
        .Protein(new BigDecimal("8.9"))
        .Fat(new BigDecimal("2.6"))
        .Fiber(new BigDecimal("7.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.3"))
        .Sugar(new BigDecimal("4.8"))
        .PolyunsaturatedFat(new BigDecimal("1"))
        .MonounsaturatedFat(new BigDecimal("0.5"))
        .build();

foodRepository.addFood(chickpeas);
// Kidney Beans
Food kidneyBeans = Food.builder()
        .name("Kidney Beans")
        .calories(new BigDecimal("127"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("8.9"))
        .C(new BigDecimal("24"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.6"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("49"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("26"))
        .Phosphorus(new BigDecimal("38"))
        .Magnesium(new BigDecimal("35"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("406"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.5"))
        .Zinc(new BigDecimal("1"))
        .Copper(new BigDecimal("0.3"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("22.8"))
        .Protein(new BigDecimal("8.7"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("6.4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.3"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(kidneyBeans);

// Pinto Beans
Food pintoBeans = Food.builder()
        .name("Pinto Beans")
        .calories(new BigDecimal("143"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("10"))
        .C(new BigDecimal("21"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.8"))
        .B5(new BigDecimal("0.6"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("55"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("143"))
        .Magnesium(new BigDecimal("43"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("436"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.4"))
        .Zinc(new BigDecimal("1"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("0.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("26.2"))
        .Protein(new BigDecimal("9"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.3"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(pintoBeans);
// Black Beans
Food blackBeans = Food.builder()
        .name("Black Beans")
        .calories(new BigDecimal("339"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("1"))
        .C(new BigDecimal("63"))
        .B1(new BigDecimal("0.4"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.7"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("45"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("160"))
        .Phosphorus(new BigDecimal("119"))
        .Magnesium(new BigDecimal("171"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("1406"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("8.7"))
        .Zinc(new BigDecimal("2.5"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("1.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("62.4"))
        .Protein(new BigDecimal("21.6"))
        .Fat(new BigDecimal("1.4"))
        .Fiber(new BigDecimal("16.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.4"))
        .Sugar(new BigDecimal("0.3"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.4"))
        .build();

foodRepository.addFood(blackBeans);

// Navy Beans
Food navyBeans = Food.builder()
        .name("Navy Beans")
        .calories(new BigDecimal("96"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("5"))
        .C(new BigDecimal("25"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("32"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("140"))
        .Magnesium(new BigDecimal("64"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("561"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.6"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.3"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("19.7"))
        .Protein(new BigDecimal("8.7"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("10.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.3"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(navyBeans);
// Lima Beans
Food limaBeans = Food.builder()
        .name("Lima Beans")
        .calories(new BigDecimal("338"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("7"))
        .C(new BigDecimal("63"))
        .B1(new BigDecimal("0.4"))
        .B2(new BigDecimal("0.2"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("24"))
        .Phosphorus(new BigDecimal("63"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("508"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.4"))
        .Zinc(new BigDecimal("1"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("63.3"))
        .Protein(new BigDecimal("7.8"))
        .Fat(new BigDecimal("0.6"))
        .Fiber(new BigDecimal("7.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.4"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(limaBeans);

// Fava Beans
Food favaBeans = Food.builder()
        .name("Fava Beans")
        .calories(new BigDecimal("88"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("58"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("33"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("106"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("13"))
        .Potassium(new BigDecimal("299"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("14.8"))
        .Protein(new BigDecimal("5.4"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("5.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("2.6"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(favaBeans);
// Green Beans
Food greenBeans = Food.builder()
        .name("Green Beans")
        .calories(new BigDecimal("31"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("14"))
        .C(new BigDecimal("7.7"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("33"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("31"))
        .Magnesium(new BigDecimal("25"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("211"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.03"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7.9"))
        .Protein(new BigDecimal("1.8"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.3"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(greenBeans);

// Mung Beans
Food mungBeans = Food.builder()
        .name("Mung Beans")
        .calories(new BigDecimal("347"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("46"))
        .B1(new BigDecimal("0.4"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("50"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("27"))
        .Phosphorus(new BigDecimal("54"))
        .Magnesium(new BigDecimal("48"))
        .Sodium(new BigDecimal("15"))
        .Potassium(new BigDecimal("436"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.8"))
        .Zinc(new BigDecimal("0.9"))
        .Copper(new BigDecimal("0.3"))
        .Manganese(new BigDecimal("0.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("62.6"))
        .Protein(new BigDecimal("23.9"))
        .Fat(new BigDecimal("1.2"))
        .Fiber(new BigDecimal("16.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.4"))
        .Sugar(new BigDecimal("6.6"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.3"))
        .build();

foodRepository.addFood(mungBeans);
// Adzuki Beans
Food adzukiBeans = Food.builder()
        .name("Adzuki Beans")
        .calories(new BigDecimal("329"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("19"))
        .C(new BigDecimal("64"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("55"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("50"))
        .Phosphorus(new BigDecimal("127"))
        .Magnesium(new BigDecimal("36"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("1224"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("5.2"))
        .Zinc(new BigDecimal("2.1"))
        .Copper(new BigDecimal("0.6"))
        .Manganese(new BigDecimal("1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("63.5"))
        .Protein(new BigDecimal("19.9"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("12.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.7"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(adzukiBeans);

// Black-eyed Peas
Food blackEyedPeas = Food.builder()
        .name("Black-eyed Peas")
        .calories(new BigDecimal("91"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("3"))
        .C(new BigDecimal("17"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("128"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("62"))
        .Magnesium(new BigDecimal("45"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("278"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("19.9"))
        .Protein(new BigDecimal("3.2"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("4.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("4.1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(blackEyedPeas);
// Garbanzo Beans (Chickpeas)
Food garbanzoBeans = Food.builder()
        .name("Garbanzo Beans (Chickpeas)")
        .calories(new BigDecimal("164"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.6"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("27.4"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("1.5"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("71"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("49"))
        .Phosphorus(new BigDecimal("168"))
        .Magnesium(new BigDecimal("48"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("291"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.9"))
        .Zinc(new BigDecimal("1.5"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("1.7"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("4.8"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("27.4"))
        .Protein(new BigDecimal("8.9"))
        .Fat(new BigDecimal("2.6"))
        .Fiber(new BigDecimal("7.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.3"))
        .Sugar(new BigDecimal("4.8"))
        .PolyunsaturatedFat(new BigDecimal("1"))
        .MonounsaturatedFat(new BigDecimal("0.5"))
        .build();

foodRepository.addFood(garbanzoBeans);

// Split Peas
Food splitPeas = Food.builder()
        .name("Split Peas")
        .calories(new BigDecimal("116"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("6"))
        .C(new BigDecimal("20"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("39"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("12"))
        .Phosphorus(new BigDecimal("101"))
        .Magnesium(new BigDecimal("48"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("382"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.2"))
        .Zinc(new BigDecimal("0.8"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.8"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("20"))
        .Protein(new BigDecimal("8.3"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("8.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.4"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(splitPeas);
// Pigeon Peas
Food pigeonPeas = Food.builder()
        .name("Pigeon Peas")
        .calories(new BigDecimal("343"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("35"))
        .C(new BigDecimal("21"))
        .B1(new BigDecimal("0.4"))
        .B2(new BigDecimal("0.2"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("90"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("43"))
        .Phosphorus(new BigDecimal("108"))
        .Magnesium(new BigDecimal("45"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("1080"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.6"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("63.3"))
        .Protein(new BigDecimal("21.7"))
        .Fat(new BigDecimal("1.2"))
        .Fiber(new BigDecimal("15.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.2"))
        .Sugar(new BigDecimal("8.3"))
        .PolyunsaturatedFat(new BigDecimal("0.5"))
        .MonounsaturatedFat(new BigDecimal("0.3"))
        .build();

foodRepository.addFood(pigeonPeas);

// Cowpeas
Food cowpeas = Food.builder()
        .name("Cowpeas")
        .calories(new BigDecimal("336"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("24"))
        .C(new BigDecimal("21"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("74"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("49"))
        .Phosphorus(new BigDecimal("109"))
        .Magnesium(new BigDecimal("43"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("715"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("4.2"))
        .Zinc(new BigDecimal("2.2"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("1.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("4.9"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("62.6"))
        .Protein(new BigDecimal("24.5"))
        .Fat(new BigDecimal("1.4"))
        .Fiber(new BigDecimal("10.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.3"))
        .Sugar(new BigDecimal("3.1"))
        .PolyunsaturatedFat(new BigDecimal("0.6"))
        .MonounsaturatedFat(new BigDecimal("0.3"))
        .build();

foodRepository.addFood(cowpeas);
// Broad Beans
Food broadBeans = Food.builder()
        .name("Broad Beans")
        .calories(new BigDecimal("341"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("53"))
        .C(new BigDecimal("25"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("106"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("47"))
        .Phosphorus(new BigDecimal("172"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("620"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.7"))
        .Zinc(new BigDecimal("2"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("0.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("58.3"))
        .Protein(new BigDecimal("26.1"))
        .Fat(new BigDecimal("1.5"))
        .Fiber(new BigDecimal("25"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.4"))
        .Sugar(new BigDecimal("9.3"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.3"))
        .build();

foodRepository.addFood(broadBeans);

// Horse Gram
Food horseGram = Food.builder()
        .name("Horse Gram")
        .calories(new BigDecimal("321"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("5"))
        .C(new BigDecimal("30"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("187"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("287"))
        .Phosphorus(new BigDecimal("311"))
        .Magnesium(new BigDecimal("287"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("1246"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("6.8"))
        .Zinc(new BigDecimal("4.5"))
        .Copper(new BigDecimal("1.3"))
        .Manganese(new BigDecimal("5.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("7.1"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("57"))
        .Protein(new BigDecimal("22"))
        .Fat(new BigDecimal("0.7"))
        .Fiber(new BigDecimal("16"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.2"))
        .Sugar(new BigDecimal("3.7"))
        .PolyunsaturatedFat(new BigDecimal("0.3"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(horseGram);
// Lathyrus (Lentils)
Food lathyrus = Food.builder()
        .name("Lathyrus (Lentils)")
        .calories(new BigDecimal("353"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("7"))
        .C(new BigDecimal("63"))
        .B1(new BigDecimal("0.5"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("479"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("281"))
        .Magnesium(new BigDecimal("36"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("955"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("7.5"))
        .Zinc(new BigDecimal("3.6"))
        .Copper(new BigDecimal("0.8"))
        .Manganese(new BigDecimal("1.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("8.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("60"))
        .Protein(new BigDecimal("26"))
        .Fat(new BigDecimal("1.1"))
        .Fiber(new BigDecimal("30"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.8"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.2"))
        .build();

foodRepository.addFood(lathyrus);

// Lupins
Food lupins = Food.builder()
        .name("Lupins")
        .calories(new BigDecimal("371"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("7"))
        .C(new BigDecimal("17"))
        .B1(new BigDecimal("0.5"))
        .B2(new BigDecimal("0.2"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("440"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("150"))
        .Phosphorus(new BigDecimal("194"))
        .Magnesium(new BigDecimal("101"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("681"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("4.9"))
        .Zinc(new BigDecimal("4.9"))
        .Copper(new BigDecimal("0.7"))
        .Manganese(new BigDecimal("1.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("5.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("40"))
        .Protein(new BigDecimal("36"))
        .Fat(new BigDecimal("9.6"))
        .Fiber(new BigDecimal("37"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("1.3"))
        .Sugar(new BigDecimal("2.3"))
        .PolyunsaturatedFat(new BigDecimal("4.1"))
        .MonounsaturatedFat(new BigDecimal("2.2"))
        .build();

foodRepository.addFood(lupins);
// Moth Beans
Food mothBeans = Food.builder()
        .name("Moth Beans")
        .calories(new BigDecimal("349"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("64"))
        .B1(new BigDecimal("0.6"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.6"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("186"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("28"))
        .Phosphorus(new BigDecimal("367"))
        .Magnesium(new BigDecimal("99"))
        .Sodium(new BigDecimal("15"))
        .Potassium(new BigDecimal("1477"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("5.3"))
        .Zinc(new BigDecimal("2.2"))
        .Copper(new BigDecimal("0.7"))
        .Manganese(new BigDecimal("1.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("6.1"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("61.8"))
        .Protein(new BigDecimal("23.9"))
        .Fat(new BigDecimal("1.7"))
        .Fiber(new BigDecimal("16.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.6"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.4"))
        .build();

foodRepository.addFood(mothBeans);

// Sword Beans
Food swordBeans = Food.builder()
        .name("Sword Beans")
        .calories(new BigDecimal("106"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("23"))
        .C(new BigDecimal("9"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("20"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("19"))
        .Phosphorus(new BigDecimal("50"))
        .Magnesium(new BigDecimal("40"))
        .Sodium(new BigDecimal("7"))
        .Potassium(new BigDecimal("311"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.2"))
        .Zinc(new BigDecimal("0.7"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("19.5"))
        .Protein(new BigDecimal("7.6"))
        .Fat(new BigDecimal("0.6"))
        .Fiber(new BigDecimal("4.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.5"))
        .PolyunsaturatedFat(new BigDecimal("0.3"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(swordBeans);
// Velvet Beans
Food velvetBeans = Food.builder()
        .name("Velvet Beans")
        .calories(new BigDecimal("336"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.6"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("14"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.2"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("103"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("215"))
        .Phosphorus(new BigDecimal("140"))
        .Magnesium(new BigDecimal("184"))
        .Sodium(new BigDecimal("8"))
        .Potassium(new BigDecimal("1500"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("6.9"))
        .Zinc(new BigDecimal("5.4"))
        .Copper(new BigDecimal("0.6"))
        .Manganese(new BigDecimal("2.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("7.3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("57.3"))
        .Protein(new BigDecimal("25"))
        .Fat(new BigDecimal("1.7"))
        .Fiber(new BigDecimal("18.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.4"))
        .Sugar(new BigDecimal("2.9"))
        .PolyunsaturatedFat(new BigDecimal("0.6"))
        .MonounsaturatedFat(new BigDecimal("0.4"))
        .build();

foodRepository.addFood(velvetBeans);

// Winged Beans
Food wingedBeans = Food.builder()
        .name("Winged Beans")
        .calories(new BigDecimal("49"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("15"))
        .C(new BigDecimal("19"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("40"))
        .Phosphorus(new BigDecimal("60"))
        .Magnesium(new BigDecimal("65"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("370"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.6"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("8.6"))
        .Protein(new BigDecimal("4.9"))
        .Fat(new BigDecimal("0.6"))
        .Fiber(new BigDecimal("4.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("2.1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.2"))
        .build();

foodRepository.addFood(wingedBeans);
// Lablab Beans
Food lablabBeans = Food.builder()
        .name("Lablab Beans")
        .calories(new BigDecimal("106"))
        .A(new BigDecimal("1"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("24"))
        .C(new BigDecimal("15"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("40"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("81"))
        .Phosphorus(new BigDecimal("40"))
        .Magnesium(new BigDecimal("24"))
        .Sodium(new BigDecimal("4"))
        .Potassium(new BigDecimal("291"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.7"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("20.7"))
        .Protein(new BigDecimal("7.6"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("3.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.5"))
        .PolyunsaturatedFat(new BigDecimal("0.3"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(lablabBeans);

// Hyacinth Beans
Food hyacinthBeans = Food.builder()
        .name("Hyacinth Beans")
        .calories(new BigDecimal("43"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("24"))
        .C(new BigDecimal("10"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("12"))
        .Phosphorus(new BigDecimal("26"))
        .Magnesium(new BigDecimal("20"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("179"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.7"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7.6"))
        .Protein(new BigDecimal("2.5"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.1"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(hyacinthBeans);
// Bambara Groundnut
Food bambaraGroundnut = Food.builder()
        .name("Bambara Groundnut")
        .calories(new BigDecimal("327"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("8"))
        .C(new BigDecimal("65"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("85"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("165"))
        .Magnesium(new BigDecimal("184"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("670"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("6.5"))
        .Zinc(new BigDecimal("3.4"))
        .Copper(new BigDecimal("0.5"))
        .Manganese(new BigDecimal("1.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("2.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("63"))
        .Protein(new BigDecimal("19.3"))
        .Fat(new BigDecimal("5.8"))
        .Fiber(new BigDecimal("8.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.9"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("2"))
        .MonounsaturatedFat(new BigDecimal("2.3"))
        .build();

foodRepository.addFood(bambaraGroundnut);

// Kersting's Groundnut
Food kerstingsGroundnut = Food.builder()
        .name("Kersting's Groundnut")
        .calories(new BigDecimal("347"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("25"))
        .C(new BigDecimal("23"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("26"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("51"))
        .Phosphorus(new BigDecimal("98"))
        .Magnesium(new BigDecimal("97"))
        .Sodium(new BigDecimal("9"))
        .Potassium(new BigDecimal("593"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("4.8"))
        .Zinc(new BigDecimal("4"))
        .Copper(new BigDecimal("0.8"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("3.9"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("63"))
        .Protein(new BigDecimal("18.7"))
        .Fat(new BigDecimal("1.5"))
        .Fiber(new BigDecimal("14"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.4"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.3"))
        .build();

foodRepository.addFood(kerstingsGroundnut);
// Peanut
Food peanut = Food.builder()
        .name("Peanut")
        .calories(new BigDecimal("567"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("9"))
        .K(new BigDecimal("25"))
        .C(new BigDecimal("8"))
        .B1(new BigDecimal("0.6"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("1.8"))
        .B5(new BigDecimal("0.7"))
        .B6(new BigDecimal("0.4"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("240"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("92"))
        .Phosphorus(new BigDecimal("336"))
        .Magnesium(new BigDecimal("168"))
        .Sodium(new BigDecimal("18"))
        .Potassium(new BigDecimal("705"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("4.6"))
        .Zinc(new BigDecimal("3.3"))
        .Copper(new BigDecimal("1.1"))
        .Manganese(new BigDecimal("2.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("7.1"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("16"))
        .Protein(new BigDecimal("26"))
        .Fat(new BigDecimal("49.2"))
        .Fiber(new BigDecimal("8.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("6.3"))
        .Sugar(new BigDecimal("4.7"))
        .PolyunsaturatedFat(new BigDecimal("15.6"))
        .MonounsaturatedFat(new BigDecimal("24.4"))
        .build();

foodRepository.addFood(peanut);

// Soybean
Food soybean = Food.builder()
        .name("Soybean")
        .calories(new BigDecimal("446"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("8.9"))
        .K(new BigDecimal("36"))
        .C(new BigDecimal("30"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("2.1"))
        .B5(new BigDecimal("1.1"))
        .B6(new BigDecimal("0.4"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("375"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("277"))
        .Phosphorus(new BigDecimal("704"))
        .Magnesium(new BigDecimal("280"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("1797"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("15.7"))
        .Zinc(new BigDecimal("4.9"))
        .Copper(new BigDecimal("0.8"))
        .Manganese(new BigDecimal("2.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("8.9"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("30.2"))
        .Protein(new BigDecimal("36.5"))
        .Fat(new BigDecimal("19.9"))
        .Fiber(new BigDecimal("9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("2.7"))
        .Sugar(new BigDecimal("7.3"))
        .PolyunsaturatedFat(new BigDecimal("11.2"))
        .MonounsaturatedFat(new BigDecimal("4.4"))
        .build();

foodRepository.addFood(soybean);
// Vetch
Food vetch = Food.builder()
        .name("Vetch")
        .calories(new BigDecimal("68"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("11"))
        .C(new BigDecimal("11"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("27"))
        .Phosphorus(new BigDecimal("49"))
        .Magnesium(new BigDecimal("18"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("191"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("11.5"))
        .Protein(new BigDecimal("9"))
        .Fat(new BigDecimal("0.6"))
        .Fiber(new BigDecimal("4.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.2"))
        .build();

foodRepository.addFood(vetch);

// Alfalfa
Food alfalfa = Food.builder()
        .name("Alfalfa")
        .calories(new BigDecimal("23"))
        .A(new BigDecimal("50"))
        .D(new BigDecimal("1"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("8.2"))
        .B1(new BigDecimal("0"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.5"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("5"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("32"))
        .Phosphorus(new BigDecimal("27"))
        .Magnesium(new BigDecimal("8"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("79"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.9"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("2.1"))
        .Protein(new BigDecimal("3.9"))
        .Fat(new BigDecimal("0.7"))
        .Fiber(new BigDecimal("1.9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.2"))
        .PolyunsaturatedFat(new BigDecimal("0.3"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(alfalfa);
// Clover
Food clover = Food.builder()
        .name("Clover")
        .calories(new BigDecimal("23"))
        .A(new BigDecimal("473"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("90"))
        .B1(new BigDecimal("0"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("5"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("40"))
        .Phosphorus(new BigDecimal("30"))
        .Magnesium(new BigDecimal("8"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("79"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.7"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("2.9"))
        .Protein(new BigDecimal("2.1"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("1.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.2"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(clover);

// Lespedeza
Food lespedeza = Food.builder()
        .name("Lespedeza")
        .calories(new BigDecimal("74"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("13"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("112"))
        .Phosphorus(new BigDecimal("70"))
        .Magnesium(new BigDecimal("29"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("209"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("6.1"))
        .Zinc(new BigDecimal("1.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.8"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("14"))
        .Protein(new BigDecimal("3.4"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("4.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("4.5"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(lespedeza);
// Lupin
Food lupin = Food.builder()
        .name("Lupin")
        .calories(new BigDecimal("371"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("15"))
        .C(new BigDecimal("9"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("181"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("97"))
        .Phosphorus(new BigDecimal("97"))
        .Magnesium(new BigDecimal("53"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("383"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("5.4"))
        .Zinc(new BigDecimal("2.4"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("0.9"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("3.5"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("40.7"))
        .Protein(new BigDecimal("36"))
        .Fat(new BigDecimal("9.7"))
        .Fiber(new BigDecimal("9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("1.1"))
        .Sugar(new BigDecimal("1.2"))
        .PolyunsaturatedFat(new BigDecimal("2.5"))
        .MonounsaturatedFat(new BigDecimal("3.2"))
        .build();

foodRepository.addFood(lupin);

// Safflower
Food safflower = Food.builder()
        .name("Safflower")
        .calories(new BigDecimal("718"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("5.8"))
        .K(new BigDecimal("9"))
        .C(new BigDecimal("0"))
        .B1(new BigDecimal("0"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("17"))
        .Phosphorus(new BigDecimal("66"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("0"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.5"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("11.6"))
        .Protein(new BigDecimal("12.8"))
        .Fat(new BigDecimal("75"))
        .Fiber(new BigDecimal("0"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("7.2"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("3.7"))
        .MonounsaturatedFat(new BigDecimal("0.4"))
        .build();

foodRepository.addFood(safflower);
// Sesame
Food sesame = Food.builder()
        .name("Sesame")
        .calories(new BigDecimal("573"))
        .A(new BigDecimal("9"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("13"))
        .C(new BigDecimal("0"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("1.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.8"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("97"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("975"))
        .Phosphorus(new BigDecimal("362"))
        .Magnesium(new BigDecimal("351"))
        .Sodium(new BigDecimal("11"))
        .Potassium(new BigDecimal("468"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("14.6"))
        .Zinc(new BigDecimal("7.8"))
        .Copper(new BigDecimal("4.1"))
        .Manganese(new BigDecimal("2.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("34.4"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("23.5"))
        .Protein(new BigDecimal("17"))
        .Fat(new BigDecimal("49.7"))
        .Fiber(new BigDecimal("11.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("7.0"))
        .Sugar(new BigDecimal("0.3"))
        .PolyunsaturatedFat(new BigDecimal("22.9"))
        .MonounsaturatedFat(new BigDecimal("18.8"))
        .build();

foodRepository.addFood(sesame);

// Sunflower
Food sunflower = Food.builder()
        .name("Sunflower")
        .calories(new BigDecimal("584"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("35.1"))
        .K(new BigDecimal("1"))
        .C(new BigDecimal("0"))
        .B1(new BigDecimal("0.4"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("1.5"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("1.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("227"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("78"))
        .Phosphorus(new BigDecimal("660"))
        .Magnesium(new BigDecimal("325"))
        .Sodium(new BigDecimal("9"))
        .Potassium(new BigDecimal("850"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("5.2"))
        .Zinc(new BigDecimal("5.2"))
        .Copper(new BigDecimal("1.8"))
        .Manganese(new BigDecimal("1.9"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("53.0"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("20.0"))
        .Protein(new BigDecimal("20.8"))
        .Fat(new BigDecimal("51.5"))
        .Fiber(new BigDecimal("8.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("4.5"))
        .Sugar(new BigDecimal("2.6"))
        .PolyunsaturatedFat(new BigDecimal("23.0"))
        .MonounsaturatedFat(new BigDecimal("18.5"))
        .build();

foodRepository.addFood(sunflower);

// Mustard
Food mustard = Food.builder()
        .name("Mustard")
        .calories(new BigDecimal("66"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("8"))
        .C(new BigDecimal("70"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("162"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("60"))
        .Phosphorus(new BigDecimal("70"))
        .Magnesium(new BigDecimal("29"))
        .Sodium(new BigDecimal("67"))
        .Potassium(new BigDecimal("152"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.7"))
        .Zinc(new BigDecimal("0.6"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.7"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("3.9"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6"))
        .Protein(new BigDecimal("5.7"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("2.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.5"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(mustard);
// Rapeseed
Food rapeseed = Food.builder()
        .name("Rapeseed")
        .calories(new BigDecimal("884"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("14.8"))
        .K(new BigDecimal("7"))
        .C(new BigDecimal("0"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("2.5"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("29"))
        .Phosphorus(new BigDecimal("318"))
        .Magnesium(new BigDecimal("110"))
        .Sodium(new BigDecimal("9"))
        .Potassium(new BigDecimal("933"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("4.1"))
        .Zinc(new BigDecimal("2.4"))
        .Copper(new BigDecimal("0.5"))
        .Manganese(new BigDecimal("0.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.9"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("0.6"))
        .Protein(new BigDecimal("34.1"))
        .Fat(new BigDecimal("87.4"))
        .Fiber(new BigDecimal("21.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("5.9"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("25.9"))
        .MonounsaturatedFat(new BigDecimal("53.8"))
        .build();

foodRepository.addFood(rapeseed);

// Castor Bean
Food castorBean = Food.builder()
        .name("Castor Bean")
        .calories(new BigDecimal("486"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("1.9"))
        .K(new BigDecimal("6"))
        .C(new BigDecimal("3"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("1.1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("54"))
        .Phosphorus(new BigDecimal("52"))
        .Magnesium(new BigDecimal("32"))
        .Sodium(new BigDecimal("8"))
        .Potassium(new BigDecimal("407"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("8.5"))
        .Zinc(new BigDecimal("1.4"))
        .Copper(new BigDecimal("0.4"))
        .Manganese(new BigDecimal("0.9"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("1.8"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("28.4"))
        .Protein(new BigDecimal("22.3"))
        .Fat(new BigDecimal("38.4"))
        .Fiber(new BigDecimal("5.4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("6.4"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("14.6"))
        .MonounsaturatedFat(new BigDecimal("13.4"))
        .build();

foodRepository.addFood(castorBean);
// Borage
Food borage = Food.builder()
        .name("Borage")
        .calories(new BigDecimal("21"))
        .A(new BigDecimal("264"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("18"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("80"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("24"))
        .Sodium(new BigDecimal("10"))
        .Potassium(new BigDecimal("470"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.1"))
        .Protein(new BigDecimal("1.8"))
        .Fat(new BigDecimal("0.7"))
        .Fiber(new BigDecimal("3.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(borage);

// Chayote
Food chayote = Food.builder()
        .name("Chayote")
        .calories(new BigDecimal("19"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("18"))
        .C(new BigDecimal("7.7"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("12"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("125"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.1"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("4.5"))
        .Protein(new BigDecimal("0.8"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(chayote);
// Luffa
Food luffa = Food.builder()
        .name("Luffa")
        .calories(new BigDecimal("20"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("2"))
        .C(new BigDecimal("36.7"))
        .B1(new BigDecimal("0"))
        .B2(new BigDecimal("0"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("16"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("26"))
        .Phosphorus(new BigDecimal("20"))
        .Magnesium(new BigDecimal("13"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("140"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("4.3"))
        .Protein(new BigDecimal("0.9"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("0.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("2.1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(luffa);

// Momordica
Food momordica = Food.builder()
        .name("Momordica")
        .calories(new BigDecimal("18"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("33.5"))
        .B1(new BigDecimal("0.01"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("5"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("36"))
        .Phosphorus(new BigDecimal("30"))
        .Magnesium(new BigDecimal("16"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("296"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.1"))
        .Protein(new BigDecimal("0.8"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1.9"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(momordica);
// Okra
Food okra = Food.builder()
        .name("Okra")
        .calories(new BigDecimal("33"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("31"))
        .C(new BigDecimal("23"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("46"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("82"))
        .Phosphorus(new BigDecimal("30"))
        .Magnesium(new BigDecimal("57"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("299"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7"))
        .Protein(new BigDecimal("2"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("1.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(okra);

// Pumpkin
Food pumpkin = Food.builder()
        .name("Pumpkin")
        .calories(new BigDecimal("26"))
        .A(new BigDecimal("426"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("1"))
        .C(new BigDecimal("9.8"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("16"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("21"))
        .Phosphorus(new BigDecimal("12"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("1"))
        .Potassium(new BigDecimal("340"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.8"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6.5"))
        .Protein(new BigDecimal("1"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("0.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("1.6"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(pumpkin);
// Squash
Food squash = Food.builder()
        .name("Squash")
        .calories(new BigDecimal("16"))
        .A(new BigDecimal("1"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("6.9"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("12"))
        .Magnesium(new BigDecimal("14"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("262"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.3"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.4"))
        .Protein(new BigDecimal("0.6"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("0.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("1.6"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(squash);

// Watermelon
Food watermelon = Food.builder()
        .name("Watermelon")
        .calories(new BigDecimal("30"))
        .A(new BigDecimal("28"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("8.1"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("3"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("7"))
        .Phosphorus(new BigDecimal("11"))
        .Magnesium(new BigDecimal("10"))
        .Sodium(new BigDecimal("1"))
        .Potassium(new BigDecimal("112"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.1"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.2"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7.6"))
        .Protein(new BigDecimal("0.6"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("0.4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("6.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(watermelon);

    }
}
