package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class NutsAndSeedsRepository {

    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food almonds = Food.builder()
                .name("Almonds")
                .calories(new BigDecimal("576"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("26.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("12.5"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0"))
                .B3(new BigDecimal("3.7"))
                .B5(new BigDecimal("1.0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("269"))
                .Phosphorus(new BigDecimal("481"))
                .Magnesium(new BigDecimal("76"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("705"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.7"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.8"))
                .Manganese(new BigDecimal("2.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("21.7"))
                .Protein(new BigDecimal("21.2"))
                .Fat(new BigDecimal("49.9"))
                .Fiber(new BigDecimal("12.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.7"))
                .Sugar(new BigDecimal("4.2"))
                .PolyunsaturatedFat(new BigDecimal("12.3"))
                .MonounsaturatedFat(new BigDecimal("31.5"))
                .build();

        foodRepository.addFood(almonds);
        Food peanuts = Food.builder()
                .name("Peanuts")
                .calories(new BigDecimal("567"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("8.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.6"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("12.1"))
                .B5(new BigDecimal("1.8"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("240"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("92"))
                .Phosphorus(new BigDecimal("376"))
                .Magnesium(new BigDecimal("168"))
                .Sodium(new BigDecimal("18"))
                .Potassium(new BigDecimal("705"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.6"))
                .Zinc(new BigDecimal("3.3"))
                .Copper(new BigDecimal("1.1"))
                .Manganese(new BigDecimal("2.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("7.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.1"))
                .Protein(new BigDecimal("25.8"))
                .Fat(new BigDecimal("49.2"))
                .Fiber(new BigDecimal("8.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("6.3"))
                .Sugar(new BigDecimal("4.7"))
                .PolyunsaturatedFat(new BigDecimal("15.6"))
                .MonounsaturatedFat(new BigDecimal("24.4"))
                .build();

        foodRepository.addFood(peanuts);
        Food cashews = Food.builder()
                .name("Cashews")
                .calories(new BigDecimal("553"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0.5"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("1.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("37"))
                .Phosphorus(new BigDecimal("593"))
                .Magnesium(new BigDecimal("292"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("660"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.7"))
                .Zinc(new BigDecimal("5.8"))
                .Copper(new BigDecimal("2.2"))
                .Manganese(new BigDecimal("1.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("19.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("30.2"))
                .Protein(new BigDecimal("18.2"))
                .Fat(new BigDecimal("43.9"))
                .Fiber(new BigDecimal("3.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("7.8"))
                .Sugar(new BigDecimal("5.9"))
                .PolyunsaturatedFat(new BigDecimal("7.8"))
                .MonounsaturatedFat(new BigDecimal("23.5"))
                .build();

        foodRepository.addFood(cashews);
        Food walnuts = Food.builder()
                .name("Walnuts")
                .calories(new BigDecimal("654"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1.7"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.7"))
                .B5(new BigDecimal("0.5"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("28"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("98"))
                .Phosphorus(new BigDecimal("346"))
                .Magnesium(new BigDecimal("158"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("441"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.9"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("1.9"))
                .Manganese(new BigDecimal("3.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.3"))
                .Protein(new BigDecimal("15.2"))
                .Fat(new BigDecimal("65.2"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("6.1"))
                .Sugar(new BigDecimal("1.0"))
                .PolyunsaturatedFat(new BigDecimal("47.2"))
                .MonounsaturatedFat(new BigDecimal("8.9"))
                .build();

        foodRepository.addFood(walnuts);
        Food hazelnuts = Food.builder()
                .name("Hazelnuts")
                .calories(new BigDecimal("628"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("15.0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("6.3"))
                .B1(new BigDecimal("0.6"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1.8"))
                .B5(new BigDecimal("2.3"))
                .B6(new BigDecimal("0.6"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("68"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("114"))
                .Phosphorus(new BigDecimal("290"))
                .Magnesium(new BigDecimal("163"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("680"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.7"))
                .Zinc(new BigDecimal("2.5"))
                .Copper(new BigDecimal("1.3"))
                .Manganese(new BigDecimal("6.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("16.7"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("60.8"))
                .Fiber(new BigDecimal("9.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("4.5"))
                .Sugar(new BigDecimal("4.3"))
                .PolyunsaturatedFat(new BigDecimal("46.0"))
                .MonounsaturatedFat(new BigDecimal("7.6"))
                .build();

        foodRepository.addFood(hazelnuts);
        Food pistachios = Food.builder()
                .name("Pistachios")
                .calories(new BigDecimal("562"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("21.4"))
                .B1(new BigDecimal("0.6"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.7"))
                .B6(new BigDecimal("1.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("107"))
                .Phosphorus(new BigDecimal("485"))
                .Magnesium(new BigDecimal("121"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("1025"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.9"))
                .Zinc(new BigDecimal("2.2"))
                .Copper(new BigDecimal("0.8"))
                .Manganese(new BigDecimal("1.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("7.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("27.5"))
                .Protein(new BigDecimal("20.2"))
                .Fat(new BigDecimal("45.4"))
                .Fiber(new BigDecimal("10.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("5.8"))
                .Sugar(new BigDecimal("7.7"))
                .PolyunsaturatedFat(new BigDecimal("10.4"))
                .MonounsaturatedFat(new BigDecimal("26.0"))
                .build();

        foodRepository.addFood(pistachios);
        Food pecans = Food.builder()
                .name("Pecans")
                .calories(new BigDecimal("691"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("4.0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1.1"))
                .B1(new BigDecimal("0.4"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.7"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("70"))
                .Phosphorus(new BigDecimal("277"))
                .Magnesium(new BigDecimal("121"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("410"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("4.5"))
                .Copper(new BigDecimal("1.2"))
                .Manganese(new BigDecimal("4.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("3.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13.9"))
                .Protein(new BigDecimal("9.2"))
                .Fat(new BigDecimal("71.9"))
                .Fiber(new BigDecimal("9.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("5.8"))
                .Sugar(new BigDecimal("4.3"))
                .PolyunsaturatedFat(new BigDecimal("6.1"))
                .MonounsaturatedFat(new BigDecimal("55.4"))
                .build();

        foodRepository.addFood(pecans);
        Food brazilNuts = Food.builder()
                .name("Brazil Nuts")
                .calories(new BigDecimal("656"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("5.7"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0.7"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("100"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("160"))
                .Phosphorus(new BigDecimal("376"))
                .Magnesium(new BigDecimal("376"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("659"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.4"))
                .Zinc(new BigDecimal("4.1"))
                .Copper(new BigDecimal("1.7"))
                .Manganese(new BigDecimal("0.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1917"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("12.3"))
                .Protein(new BigDecimal("14.3"))
                .Fat(new BigDecimal("66.4"))
                .Fiber(new BigDecimal("7.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("15.1"))
                .Sugar(new BigDecimal("2.3"))
                .PolyunsaturatedFat(new BigDecimal("19.0"))
                .MonounsaturatedFat(new BigDecimal("24.3"))
                .build();

        foodRepository.addFood(brazilNuts);
        Food pineNuts = Food.builder()
                .name("Pine Nuts")
                .calories(new BigDecimal("673"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("9.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("9.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("0.9"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("16"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("575"))
                .Magnesium(new BigDecimal("251"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("597"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.5"))
                .Zinc(new BigDecimal("6.5"))
                .Copper(new BigDecimal("1.3"))
                .Manganese(new BigDecimal("8.8"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13.1"))
                .Protein(new BigDecimal("13.7"))
                .Fat(new BigDecimal("68.4"))
                .Fiber(new BigDecimal("3.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("4.9"))
                .Sugar(new BigDecimal("3.6"))
                .PolyunsaturatedFat(new BigDecimal("17.1"))
                .MonounsaturatedFat(new BigDecimal("21.6"))
                .build();

        foodRepository.addFood(pineNuts);
        Food macadamiaNuts = Food.builder()
                .name("Macadamia Nuts")
                .calories(new BigDecimal("718"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("2.4"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("85"))
                .Phosphorus(new BigDecimal("188"))
                .Magnesium(new BigDecimal("130"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("368"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.7"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("3.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("13.8"))
                .Protein(new BigDecimal("7.9"))
                .Fat(new BigDecimal("75.8"))
                .Fiber(new BigDecimal("8.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("11.0"))
                .Sugar(new BigDecimal("4.6"))
                .PolyunsaturatedFat(new BigDecimal("1.6"))
                .MonounsaturatedFat(new BigDecimal("59.0"))
                .build();

        foodRepository.addFood(macadamiaNuts);
        Food sunflowerSeeds = Food.builder()
                .name("Sunflower Seeds")
                .calories(new BigDecimal("584"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("35.2"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("1.4"))
                .B1(new BigDecimal("1.5"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("8.4"))
                .B5(new BigDecimal("1.5"))
                .B6(new BigDecimal("1.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("227"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("78"))
                .Phosphorus(new BigDecimal("660"))
                .Magnesium(new BigDecimal("325"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("645"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.3"))
                .Zinc(new BigDecimal("5.0"))
                .Copper(new BigDecimal("1.8"))
                .Manganese(new BigDecimal("1.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("53.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("18.0"))
                .Protein(new BigDecimal("20.8"))
                .Fat(new BigDecimal("51.5"))
                .Fiber(new BigDecimal("8.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("4.5"))
                .Sugar(new BigDecimal("2.6"))
                .PolyunsaturatedFat(new BigDecimal("23.1"))
                .MonounsaturatedFat(new BigDecimal("18.5"))
                .build();

        foodRepository.addFood(sunflowerSeeds);
        Food pumpkinSeeds = Food.builder()
                .name("Pumpkin Seeds")
                .calories(new BigDecimal("559"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.6"))
                .K(new BigDecimal("7"))
                .C(new BigDecimal("1.3"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("58"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("46"))
                .Phosphorus(new BigDecimal("1233"))
                .Magnesium(new BigDecimal("592"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("919"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("8.8"))
                .Zinc(new BigDecimal("7.8"))
                .Copper(new BigDecimal("1.3"))
                .Manganese(new BigDecimal("4.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("17.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10.7"))
                .Protein(new BigDecimal("29.8"))
                .Fat(new BigDecimal("49.1"))
                .Fiber(new BigDecimal("6.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("8.7"))
                .Sugar(new BigDecimal("1.4"))
                .PolyunsaturatedFat(new BigDecimal("14.5"))
                .MonounsaturatedFat(new BigDecimal("24.4"))
                .build();

        foodRepository.addFood(pumpkinSeeds);
        Food flaxseeds = Food.builder()
                .name("Flaxseeds")
                .calories(new BigDecimal("534"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1.6"))
                .B1(new BigDecimal("0.4"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("3.1"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("87"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("255"))
                .Phosphorus(new BigDecimal("642"))
                .Magnesium(new BigDecimal("392"))
                .Sodium(new BigDecimal("30"))
                .Potassium(new BigDecimal("813"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.7"))
                .Zinc(new BigDecimal("4.3"))
                .Copper(new BigDecimal("1.2"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("25.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.9"))
                .Protein(new BigDecimal("18.3"))
                .Fat(new BigDecimal("42.2"))
                .Fiber(new BigDecimal("27.3"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.7"))
                .Sugar(new BigDecimal("1.6"))
                .PolyunsaturatedFat(new BigDecimal("29.4"))
                .MonounsaturatedFat(new BigDecimal("6.0"))
                .build();

        foodRepository.addFood(flaxseeds);
        Food chiaSeeds = Food.builder()
                .name("Chia Seeds")
                .calories(new BigDecimal("486"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("7.6"))
                .B1(new BigDecimal("0.6"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("3.5"))
                .B5(new BigDecimal("0.9"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("49"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("631"))
                .Phosphorus(new BigDecimal("948"))
                .Magnesium(new BigDecimal("335"))
                .Sodium(new BigDecimal("16"))
                .Potassium(new BigDecimal("407"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("7.7"))
                .Zinc(new BigDecimal("4.6"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("2.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("55.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("42.1"))
                .Protein(new BigDecimal("16.5"))
                .Fat(new BigDecimal("30.7"))
                .Fiber(new BigDecimal("34.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.3"))
                .Sugar(new BigDecimal("0.0"))
                .PolyunsaturatedFat(new BigDecimal("23.7"))
                .MonounsaturatedFat(new BigDecimal("2.3"))
                .build();

        foodRepository.addFood(chiaSeeds);
        Food sesameSeeds = Food.builder()
                .name("Sesame Seeds")
                .calories(new BigDecimal("573"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("13.6"))
                .C(new BigDecimal("0.2"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("98"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("975"))
                .Phosphorus(new BigDecimal("655"))
                .Magnesium(new BigDecimal("351"))
                .Sodium(new BigDecimal("11"))
                .Potassium(new BigDecimal("468"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("14.6"))
                .Zinc(new BigDecimal("7.8"))
                .Copper(new BigDecimal("4.1"))
                .Manganese(new BigDecimal("2.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("34.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23.5"))
                .Protein(new BigDecimal("17.7"))
                .Fat(new BigDecimal("49.7"))
                .Fiber(new BigDecimal("11.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("7.0"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("23.0"))
                .MonounsaturatedFat(new BigDecimal("16.5"))
                .build();

        foodRepository.addFood(sesameSeeds);
        Food hempSeeds = Food.builder()
                .name("Hemp Seeds")
                .calories(new BigDecimal("554"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.7"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1.0"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("2.4"))
                .B5(new BigDecimal("0.8"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("90"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("70"))
                .Phosphorus(new BigDecimal("1160"))
                .Magnesium(new BigDecimal("483"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("1200"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("14.6"))
                .Zinc(new BigDecimal("9.9"))
                .Copper(new BigDecimal("1.1"))
                .Manganese(new BigDecimal("7.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("14.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.0"))
                .Protein(new BigDecimal("31.6"))
                .Fat(new BigDecimal("48.8"))
                .Fiber(new BigDecimal("3.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("4.6"))
                .Sugar(new BigDecimal("1.5"))
                .PolyunsaturatedFat(new BigDecimal("33.3"))
                .MonounsaturatedFat(new BigDecimal("7.5"))
                .build();

        foodRepository.addFood(hempSeeds);
        Food poppySeeds = Food.builder()
                .name("Poppy Seeds")
                .calories(new BigDecimal("525"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("25.6"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("2.8"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("87"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("1438"))
                .Phosphorus(new BigDecimal("870"))
                .Magnesium(new BigDecimal("347"))
                .Sodium(new BigDecimal("16"))
                .Potassium(new BigDecimal("719"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("9.8"))
                .Zinc(new BigDecimal("7.9"))
                .Copper(new BigDecimal("1.3"))
                .Manganese(new BigDecimal("8.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.9"))
                .Protein(new BigDecimal("18.0"))
                .Fat(new BigDecimal("42.3"))
                .Fiber(new BigDecimal("19.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("4.5"))
                .Sugar(new BigDecimal("2.3"))
                .PolyunsaturatedFat(new BigDecimal("30.5"))
                .MonounsaturatedFat(new BigDecimal("4.5"))
                .build();

        foodRepository.addFood(poppySeeds);
        Food quinoa = Food.builder()
                .name("Quinoa")
                .calories(new BigDecimal("120"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("13"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("17"))
                .Phosphorus(new BigDecimal("152"))
                .Magnesium(new BigDecimal("64"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("172"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.5"))
                .Zinc(new BigDecimal("1.1"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("2.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("21.2"))
                .Protein(new BigDecimal("4.0"))
                .Fat(new BigDecimal("1.9"))
                .Fiber(new BigDecimal("2.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.9"))
                .PolyunsaturatedFat(new BigDecimal("1.7"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(quinoa);
        Food amaranth = Food.builder()
                .name("Amaranth")
                .calories(new BigDecimal("371"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("29.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("82"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("160"))
                .Phosphorus(new BigDecimal("557"))
                .Magnesium(new BigDecimal("248"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("508"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("15.7"))
                .Zinc(new BigDecimal("3.9"))
                .Copper(new BigDecimal("0.9"))
                .Manganese(new BigDecimal("2.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("5.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("65.2"))
                .Protein(new BigDecimal("14.7"))
                .Fat(new BigDecimal("7.0"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.6"))
                .Sugar(new BigDecimal("0.9"))
                .PolyunsaturatedFat(new BigDecimal("2.6"))
                .MonounsaturatedFat(new BigDecimal("1.7"))
                .build();

        foodRepository.addFood(amaranth);
        Food buckwheat = Food.builder()
                .name("Buckwheat")
                .calories(new BigDecimal("343"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("10.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("5.8"))
                .B5(new BigDecimal("0.9"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("54"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("18"))
                .Phosphorus(new BigDecimal("347"))
                .Magnesium(new BigDecimal("231"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("460"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("1.3"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.5"))
                .Protein(new BigDecimal("13.3"))
                .Fat(new BigDecimal("3.4"))
                .Fiber(new BigDecimal("10.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.6"))
                .Sugar(new BigDecimal("0.6"))
                .PolyunsaturatedFat(new BigDecimal("1.0"))
                .MonounsaturatedFat(new BigDecimal("1.1"))
                .build();

        foodRepository.addFood(buckwheat);
        Food teff = Food.builder()
                .name("Teff")
                .calories(new BigDecimal("367"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("123"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.9"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("50"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("180"))
                .Phosphorus(new BigDecimal("351"))
                .Magnesium(new BigDecimal("184"))
                .Sodium(new BigDecimal("12"))
                .Potassium(new BigDecimal("427"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("7.6"))
                .Zinc(new BigDecimal("3.1"))
                .Copper(new BigDecimal("0.7"))
                .Manganese(new BigDecimal("2.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("4.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.0"))
                .Protein(new BigDecimal("13.3"))
                .Fat(new BigDecimal("2.4"))
                .Fiber(new BigDecimal("8.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("1.8"))
                .PolyunsaturatedFat(new BigDecimal("0.8"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(teff);
        Food sorghum = Food.builder()
                .name("Sorghum")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("19.6"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("6.4"))
                .B5(new BigDecimal("1.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("32"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("28"))
                .Phosphorus(new BigDecimal("287"))
                .Magnesium(new BigDecimal("42"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("350"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.4"))
                .Zinc(new BigDecimal("2.5"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("1.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("72.0"))
                .Protein(new BigDecimal("11.3"))
                .Fat(new BigDecimal("3.3"))
                .Fiber(new BigDecimal("6.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.6"))
                .Sugar(new BigDecimal("0.6"))
                .PolyunsaturatedFat(new BigDecimal("1.3"))
                .MonounsaturatedFat(new BigDecimal("1.0"))
                .build();

        foodRepository.addFood(sorghum);
        Food millet = Food.builder()
                .name("Millet")
                .calories(new BigDecimal("378"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("22.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("4.7"))
                .B5(new BigDecimal("1.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("8"))
                .Phosphorus(new BigDecimal("285"))
                .Magnesium(new BigDecimal("114"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("195"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.9"))
                .Zinc(new BigDecimal("1.9"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("1.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.0"))
                .Protein(new BigDecimal("11.0"))
                .Fat(new BigDecimal("4.2"))
                .Fiber(new BigDecimal("8.5"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.7"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("2.0"))
                .MonounsaturatedFat(new BigDecimal("1.1"))
                .build();

        foodRepository.addFood(millet);
        Food freekeh = Food.builder()
                .name("Freekeh")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("54.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.9"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("36"))
                .Phosphorus(new BigDecimal("327"))
                .Magnesium(new BigDecimal("131"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("720"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.4"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("2.2"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1.9"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("13.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("1.0"))
                .PolyunsaturatedFat(new BigDecimal("1.2"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(freekeh);
        Food farro = Food.builder()
                .name("Farro")
                .calories(new BigDecimal("340"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("71.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.5"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("19"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("40"))
                .Phosphorus(new BigDecimal("332"))
                .Magnesium(new BigDecimal("68"))
                .Sodium(new BigDecimal("5"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("2.4"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("21.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.0"))
                .Protein(new BigDecimal("12.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("7.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(farro);
        Food triticale = Food.builder()
                .name("Triticale")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("55.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.8"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("16"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("37"))
                .Phosphorus(new BigDecimal("340"))
                .Magnesium(new BigDecimal("76"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("352"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.0"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.8"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("18.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("7.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(triticale);
        Food kamut = Food.builder()
                .name("Kamut")
                .calories(new BigDecimal("337"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("67.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1.7"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("26"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("403"))
                .Magnesium(new BigDecimal("136"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("388"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.6"))
                .Zinc(new BigDecimal("2.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("3.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("12.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("10.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.8"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(kamut);
        Food einkorn = Food.builder()
                .name("Einkorn")
                .calories(new BigDecimal("332"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("63.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1.5"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("40"))
                .Phosphorus(new BigDecimal("303"))
                .Magnesium(new BigDecimal("136"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("388"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.7"))
                .Zinc(new BigDecimal("2.7"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("3.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("10.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("71.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("10.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(einkorn);
        Food khorasanWheat = Food.builder()
                .name("Khorasan Wheat")
                .calories(new BigDecimal("337"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("67.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1.7"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("26"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("403"))
                .Magnesium(new BigDecimal("136"))
                .Sodium(new BigDecimal("3"))
                .Potassium(new BigDecimal("388"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.6"))
                .Zinc(new BigDecimal("2.9"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("3.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("12.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("10.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.8"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(khorasanWheat);
        Food durumWheat = Food.builder()
                .name("Durum Wheat")
                .calories(new BigDecimal("339"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("55.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("1.8"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("16"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("37"))
                .Phosphorus(new BigDecimal("340"))
                .Magnesium(new BigDecimal("76"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("352"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.0"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.8"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("18.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("70.0"))
                .Protein(new BigDecimal("14.0"))
                .Fat(new BigDecimal("2.0"))
                .Fiber(new BigDecimal("7.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.6"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(durumWheat);
        Food semolina = Food.builder()
                .name("Semolina")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("73.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.9"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("17"))
                .Phosphorus(new BigDecimal("94"))
                .Magnesium(new BigDecimal("32"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("95"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.1"))
                .Zinc(new BigDecimal("0.7"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("12.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.0"))
                .Protein(new BigDecimal("11.8"))
                .Fat(new BigDecimal("1.0"))
                .Fiber(new BigDecimal("2.7"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(semolina);
        Food bulgurWheat = Food.builder()
                .name("Bulgur Wheat")
                .calories(new BigDecimal("342"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("18.6"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("5.4"))
                .B5(new BigDecimal("0.9"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("34"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("25"))
                .Phosphorus(new BigDecimal("135"))
                .Magnesium(new BigDecimal("76"))
                .Sodium(new BigDecimal("6"))
                .Potassium(new BigDecimal("341"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.7"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("6.8"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("75.9"))
                .Protein(new BigDecimal("12.3"))
                .Fat(new BigDecimal("1.1"))
                .Fiber(new BigDecimal("8.2"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("1.0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(bulgurWheat);
        Food brownRice = Food.builder()
                .name("Brown Rice")
                .calories(new BigDecimal("111"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("23.0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("2.7"))
                .B5(new BigDecimal("1.8"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("23"))
                .Phosphorus(new BigDecimal("208"))
                .Magnesium(new BigDecimal("43"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("143"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1.2"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.7"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("23.0"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.4"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(brownRice);
        Food basmatiRice = Food.builder()
                .name("Basmati Rice")
                .calories(new BigDecimal("121"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("25.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("1.6"))
                .B5(new BigDecimal("1.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("76"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("43"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("25.0"))
                .Protein(new BigDecimal("2.0"))
                .Fat(new BigDecimal("0.2"))
                .Fiber(new BigDecimal("0.4"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.0"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(basmatiRice);
        Food jasmineRice = Food.builder()
                .name("Jasmine Rice")
                .calories(new BigDecimal("129"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("28.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("1.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("22"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("68"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("35"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.5"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("11.0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("28.0"))
                .Protein(new BigDecimal("2.3"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("0.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.1"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(jasmineRice);
        Food arborioRice = Food.builder()
                .name("Arborio Rice")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("76.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("1.1"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("98"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("30"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.0"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("76.0"))
                .Protein(new BigDecimal("6.7"))
                .Fat(new BigDecimal("1.0"))
                .Fiber(new BigDecimal("1.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(arborioRice);
        Food wildRice = Food.builder()
                .name("Wild Rice")
                .calories(new BigDecimal("101"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("21.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("1.0"))
                .B5(new BigDecimal("2.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("162"))
                .Magnesium(new BigDecimal("26"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("166"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("1.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("21.0"))
                .Protein(new BigDecimal("3.9"))
                .Fat(new BigDecimal("0.3"))
                .Fiber(new BigDecimal("1.8"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(wildRice);
        Food blackRice = Food.builder()
                .name("Black Rice")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("76.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("1.1"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("98"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("30"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.0"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("76.0"))
                .Protein(new BigDecimal("6.7"))
                .Fat(new BigDecimal("1.0"))
                .Fiber(new BigDecimal("1.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(blackRice);
        Food redRice = Food.builder()
                .name("Red Rice")
                .calories(new BigDecimal("360"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("76.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("1.1"))
                .B5(new BigDecimal("0.6"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("98"))
                .Magnesium(new BigDecimal("8"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("30"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.0"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("1.0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("8.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("76.0"))
                .Protein(new BigDecimal("6.7"))
                .Fat(new BigDecimal("1.0"))
                .Fiber(new BigDecimal("1.6"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0.0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(redRice);
        Food wildOats = Food.builder()
                .name("Wild Oats")
                .calories(new BigDecimal("389"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("66.3"))
                .B1(new BigDecimal("0.8"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("2.4"))
                .B5(new BigDecimal("1.5"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("56"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("54"))
                .Phosphorus(new BigDecimal("523"))
                .Magnesium(new BigDecimal("138"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("429"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4.7"))
                .Zinc(new BigDecimal("3.3"))
                .Copper(new BigDecimal("0.6"))
                .Manganese(new BigDecimal("4.9"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("34.2"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("66.3"))
                .Protein(new BigDecimal("16.9"))
                .Fat(new BigDecimal("6.9"))
                .Fiber(new BigDecimal("11.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.2"))
                .Sugar(new BigDecimal("1.1"))
                .PolyunsaturatedFat(new BigDecimal("2.4"))
                .MonounsaturatedFat(new BigDecimal("2.2"))
                .build();

        foodRepository.addFood(wildOats);
        Food steelCutOats = Food.builder()
                .name("Steel-Cut Oats")
                .calories(new BigDecimal("150"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("27.0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("1.0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("56"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("54"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("54"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("164"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("2.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("13.3"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("27.0"))
                .Protein(new BigDecimal("5.0"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("4.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0.0"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(steelCutOats);
        Food pearlBarley = Food.builder()
                .name("Pearl Barley")
                .calories(new BigDecimal("123"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("29.6"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.0"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("20"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("29"))
                .Phosphorus(new BigDecimal("111"))
                .Magnesium(new BigDecimal("33"))
                .Sodium(new BigDecimal("4"))
                .Potassium(new BigDecimal("270"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.9"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("16.7"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("73.5"))
                .Protein(new BigDecimal("2.3"))
                .Fat(new BigDecimal("0.4"))
                .Fiber(new BigDecimal("6.0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0.3"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(pearlBarley);

    }

}
