package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class SeaFoodsRepository {
    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food tuna = Food.builder()
                .name("Tuna")
                .calories(new BigDecimal("144"))
                .A(new BigDecimal("9"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("2.7"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("2.4"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("25"))
                .Sodium(new BigDecimal("38"))
                .Potassium(new BigDecimal("256"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("25"))
                .Selenium(new BigDecimal("46"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("7"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("29"))
                .Fat(new BigDecimal("6.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.4"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.3"))
                .MonounsaturatedFat(new BigDecimal("2.3"))
                .build();

        foodRepository.addFood(tuna);

        Food salmon = Food.builder()
                .name("Salmon")
                .calories(new BigDecimal("206"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("13"))
                .E(new BigDecimal("2.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.6"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("3"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("241"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("363"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("1"))
                .Selenium(new BigDecimal("40"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("4"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("25"))
                .Fat(new BigDecimal("13"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("3.1"))
                .MonounsaturatedFat(new BigDecimal("5.9"))
                .build();

        foodRepository.addFood(salmon);
        Food shrimp = Food.builder()
                .name("Shrimp")
                .calories(new BigDecimal("71"))
                .A(new BigDecimal("1"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("1"))
                .Calcium(new BigDecimal("38"))
                .Phosphorus(new BigDecimal("195"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("119"))
                .Potassium(new BigDecimal("259"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.3"))
                .Zinc(new BigDecimal("1.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("34"))
                .Selenium(new BigDecimal("34"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("3"))
                .Carbohydrates(new BigDecimal("0.9"))
                .Protein(new BigDecimal("14"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(shrimp);
        Food cod = Food.builder()
                .name("Cod")
                .calories(new BigDecimal("82"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("3"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.2"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("3"))
                .B12(new BigDecimal("1.8"))
                .Calcium(new BigDecimal("7"))
                .Phosphorus(new BigDecimal("157"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("439"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.3"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("99"))
                .Selenium(new BigDecimal("45"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("9"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(cod);
        Food crab = Food.builder()
                .name("Crab")
                .calories(new BigDecimal("83"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.8"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("9"))
                .Calcium(new BigDecimal("38"))
                .Phosphorus(new BigDecimal("170"))
                .Magnesium(new BigDecimal("38"))
                .Sodium(new BigDecimal("911"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.3"))
                .Zinc(new BigDecimal("2.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("31"))
                .Selenium(new BigDecimal("56"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("27"))
                .Carbohydrates(new BigDecimal("0.2"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("1.2"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(crab);
        Food lobster = Food.builder()
                .name("Lobster")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("6"))
                .Calcium(new BigDecimal("51"))
                .Phosphorus(new BigDecimal("274"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("270"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("2.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("34"))
                .Selenium(new BigDecimal("54"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("33"))
                .Carbohydrates(new BigDecimal("0.8"))
                .Protein(new BigDecimal("18.9"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(lobster);
        Food octopus = Food.builder()
                .name("Octopus")
                .calories(new BigDecimal("82"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("1.9"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("0.8"))
                .Calcium(new BigDecimal("34"))
                .Phosphorus(new BigDecimal("220"))
                .Magnesium(new BigDecimal("45"))
                .Sodium(new BigDecimal("450"))
                .Potassium(new BigDecimal("430"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("120"))
                .Selenium(new BigDecimal("82"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("10"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("16"))
                .Fat(new BigDecimal("1.1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(octopus);
        Food squid = Food.builder()
                .name("Squid")
                .calories(new BigDecimal("92"))
                .A(new BigDecimal("11"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("2.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("1.7"))
                .Calcium(new BigDecimal("44"))
                .Phosphorus(new BigDecimal("235"))
                .Magnesium(new BigDecimal("70"))
                .Sodium(new BigDecimal("44"))
                .Potassium(new BigDecimal("407"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.8"))
                .Zinc(new BigDecimal("0.8"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("350"))
                .Selenium(new BigDecimal("37"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("30"))
                .Carbohydrates(new BigDecimal("2.2"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(squid);
        Food mussels = Food.builder()
                .name("Mussels")
                .calories(new BigDecimal("172"))
                .A(new BigDecimal("600"))
                .D(new BigDecimal("10"))
                .E(new BigDecimal("3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.35"))
                .B3(new BigDecimal("3.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("25"))
                .B12(new BigDecimal("20"))
                .Calcium(new BigDecimal("59"))
                .Phosphorus(new BigDecimal("280"))
                .Magnesium(new BigDecimal("34"))
                .Sodium(new BigDecimal("616"))
                .Potassium(new BigDecimal("334"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6.7"))
                .Zinc(new BigDecimal("2.4"))
                .Copper(new BigDecimal("0.4"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("160"))
                .Selenium(new BigDecimal("75"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("130"))
                .Carbohydrates(new BigDecimal("4.4"))
                .Protein(new BigDecimal("24"))
                .Fat(new BigDecimal("6.1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.3"))
                .MonounsaturatedFat(new BigDecimal("1.4"))
                .build();

        foodRepository.addFood(mussels);
        Food oysters = Food.builder()
                .name("Oysters")
                .calories(new BigDecimal("68"))
                .A(new BigDecimal("600"))
                .D(new BigDecimal("8"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("6"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("5.6"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("49"))
                .B12(new BigDecimal("17"))
                .Calcium(new BigDecimal("92"))
                .Phosphorus(new BigDecimal("195"))
                .Magnesium(new BigDecimal("44"))
                .Sodium(new BigDecimal("100"))
                .Potassium(new BigDecimal("180"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("5.7"))
                .Zinc(new BigDecimal("7"))
                .Copper(new BigDecimal("5"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("96"))
                .Selenium(new BigDecimal("32"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("12"))
                .Carbohydrates(new BigDecimal("6"))
                .Protein(new BigDecimal("12"))
                .Fat(new BigDecimal("2"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(oysters);
        Food scallops = Food.builder()
                .name("Scallops")
                .calories(new BigDecimal("69"))
                .A(new BigDecimal("500"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1.2"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("120"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("161"))
                .Potassium(new BigDecimal("259"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("80"))
                .Selenium(new BigDecimal("18"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("25"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(scallops);
        Food tilapia = Food.builder()
                .name("Tilapia")
                .calories(new BigDecimal("96"))
                .A(new BigDecimal("17"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.09"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("2.3"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("127"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("42"))
                .Potassium(new BigDecimal("376"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("19"))
                .Selenium(new BigDecimal("31"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("9"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("2"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.7"))
                .build();

        foodRepository.addFood(tilapia);
        Food herring = Food.builder()
                .name("Herring")
                .calories(new BigDecimal("158"))
                .A(new BigDecimal("40"))
                .D(new BigDecimal("12"))
                .E(new BigDecimal("2.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("6"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("9.6"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("420"))
                .Magnesium(new BigDecimal("44"))
                .Sodium(new BigDecimal("56"))
                .Potassium(new BigDecimal("405"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("38"))
                .Selenium(new BigDecimal("41"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("12"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("2.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("3.7"))
                .MonounsaturatedFat(new BigDecimal("4.8"))
                .build();

        foodRepository.addFood(herring);
        Food sardines = Food.builder()
                .name("Sardines")
                .calories(new BigDecimal("208"))
                .A(new BigDecimal("500"))
                .D(new BigDecimal("10"))
                .E(new BigDecimal("2.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("8"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("19"))
                .B12(new BigDecimal("8.9"))
                .Calcium(new BigDecimal("382"))
                .Phosphorus(new BigDecimal("490"))
                .Magnesium(new BigDecimal("45"))
                .Sodium(new BigDecimal("505"))
                .Potassium(new BigDecimal("397"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.9"))
                .Zinc(new BigDecimal("1.3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("20"))
                .Selenium(new BigDecimal("55"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("25"))
                .Fat(new BigDecimal("18"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("3.7"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("5.1"))
                .MonounsaturatedFat(new BigDecimal("7.1"))
                .build();

        foodRepository.addFood(sardines);
        Food mackerel = Food.builder()
                .name("Mackerel")
                .calories(new BigDecimal("305"))
                .A(new BigDecimal("18"))
                .D(new BigDecimal("500"))
                .E(new BigDecimal("1.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.3"))
                .B3(new BigDecimal("10"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.5"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("19"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("307"))
                .Magnesium(new BigDecimal("60"))
                .Sodium(new BigDecimal("90"))
                .Potassium(new BigDecimal("500"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("37"))
                .Selenium(new BigDecimal("45"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("25"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("7"))
                .MonounsaturatedFat(new BigDecimal("11"))
                .build();

        foodRepository.addFood(mackerel);
        Food halibut = Food.builder()
                .name("Halibut")
                .calories(new BigDecimal("91"))
                .A(new BigDecimal("42"))
                .D(new BigDecimal("23"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("7"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.4"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("13"))
                .B12(new BigDecimal("2.8"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("70"))
                .Potassium(new BigDecimal("490"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.7"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("54"))
                .Selenium(new BigDecimal("43"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("1.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.4"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(halibut);
        Food swordfish = Food.builder()
                .name("Swordfish")
                .calories(new BigDecimal("144"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("2.5"))
                .Calcium(new BigDecimal("15"))
                .Phosphorus(new BigDecimal("241"))
                .Magnesium(new BigDecimal("35"))
                .Sodium(new BigDecimal("38"))
                .Potassium(new BigDecimal("485"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("69"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("3.1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.7"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("1.1"))
                .build();

        foodRepository.addFood(swordfish);
        Food seabass = Food.builder()
                .name("Seabass")
                .calories(new BigDecimal("97"))
                .A(new BigDecimal("70"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("5.6"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("220"))
                .Magnesium(new BigDecimal("51"))
                .Sodium(new BigDecimal("55"))
                .Potassium(new BigDecimal("530"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("5"))
                .Selenium(new BigDecimal("52"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("2.3"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.7"))
                .MonounsaturatedFat(new BigDecimal("0.7"))
                .build();

        foodRepository.addFood(seabass);
        Food grouper = Food.builder()
                .name("Grouper")
                .calories(new BigDecimal("92"))
                .A(new BigDecimal("50"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1.8"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("188"))
                .Magnesium(new BigDecimal("42"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("454"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("5"))
                .Selenium(new BigDecimal("48"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(grouper);
        Food mahiMahi = Food.builder()
                .name("Mahi-mahi")
                .calories(new BigDecimal("85"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("1.8"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("137"))
                .Magnesium(new BigDecimal("26"))
                .Sodium(new BigDecimal("90"))
                .Potassium(new BigDecimal("475"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("2"))
                .Selenium(new BigDecimal("32"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.5"))
                .build();

        foodRepository.addFood(mahiMahi);
        Food redSnapper = Food.builder()
                .name("Red Snapper")
                .calories(new BigDecimal("109"))
                .A(new BigDecimal("24"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("3"))
                .B12(new BigDecimal("5.8"))
                .Calcium(new BigDecimal("11"))
                .Phosphorus(new BigDecimal("130"))
                .Magnesium(new BigDecimal("32"))
                .Sodium(new BigDecimal("57"))
                .Potassium(new BigDecimal("375"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("6"))
                .Selenium(new BigDecimal("32"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("23"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(redSnapper);
        Food flounder = Food.builder()
                .name("Flounder")
                .calories(new BigDecimal("86"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("5"))
                .B12(new BigDecimal("1.2"))
                .Calcium(new BigDecimal("18"))
                .Phosphorus(new BigDecimal("160"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("75"))
                .Potassium(new BigDecimal("252"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("12"))
                .Selenium(new BigDecimal("38"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(flounder);
        Food haddock = Food.builder()
                .name("Haddock")
                .calories(new BigDecimal("88"))
                .A(new BigDecimal("38"))
                .D(new BigDecimal("7"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("2.1"))
                .Calcium(new BigDecimal("15"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("87"))
                .Potassium(new BigDecimal("309"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.9"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("24"))
                .Selenium(new BigDecimal("34"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(haddock);
        Food catfish = Food.builder()
                .name("Catfish")
                .calories(new BigDecimal("105"))
                .A(new BigDecimal("4"))
                .D(new BigDecimal("7"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("3.5"))
                .Calcium(new BigDecimal("10"))
                .Phosphorus(new BigDecimal("158"))
                .Magnesium(new BigDecimal("20"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("295"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("22"))
                .Selenium(new BigDecimal("30"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.2"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(catfish);
        Food clams = Food.builder()
                .name("Clams")
                .calories(new BigDecimal("86"))
                .A(new BigDecimal("22"))
                .D(new BigDecimal("12"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.3"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("15"))
                .B12(new BigDecimal("24"))
                .Calcium(new BigDecimal("33"))
                .Phosphorus(new BigDecimal("63"))
                .Magnesium(new BigDecimal("22"))
                .Sodium(new BigDecimal("49"))
                .Potassium(new BigDecimal("222"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("28"))
                .Zinc(new BigDecimal("1.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("27"))
                .Selenium(new BigDecimal("31"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("5"))
                .Protein(new BigDecimal("14"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.5"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(clams);
        Food periwinkles = Food.builder()
                .name("Periwinkles")
                .calories(new BigDecimal("90"))
                .A(new BigDecimal("24"))
                .D(new BigDecimal("20"))
                .E(new BigDecimal("0.4"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("4"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.09"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("10"))
                .B12(new BigDecimal("23"))
                .Calcium(new BigDecimal("45"))
                .Phosphorus(new BigDecimal("50"))
                .Magnesium(new BigDecimal("42"))
                .Sodium(new BigDecimal("165"))
                .Potassium(new BigDecimal("182"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("4"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("10"))
                .Selenium(new BigDecimal("24"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3"))
                .Protein(new BigDecimal("16"))
                .Fat(new BigDecimal("1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.4"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(periwinkles);
        Food seaUrchins = Food.builder()
                .name("Sea Urchins")
                .calories(new BigDecimal("89"))
                .A(new BigDecimal("90"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("10"))
                .Calcium(new BigDecimal("15"))
                .Phosphorus(new BigDecimal("40"))
                .Magnesium(new BigDecimal("55"))
                .Sodium(new BigDecimal("52"))
                .Potassium(new BigDecimal("252"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("50"))
                .Selenium(new BigDecimal("33"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.6"))
                .Protein(new BigDecimal("16"))
                .Fat(new BigDecimal("0.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(seaUrchins);
        Food seaCucumbers = Food.builder()
                .name("Sea Cucumbers")
                .calories(new BigDecimal("56"))
                .A(new BigDecimal("13"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0.01"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("8"))
                .Calcium(new BigDecimal("24"))
                .Phosphorus(new BigDecimal("180"))
                .Magnesium(new BigDecimal("62"))
                .Sodium(new BigDecimal("107"))
                .Potassium(new BigDecimal("429"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("20"))
                .Selenium(new BigDecimal("35"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("11"))
                .Protein(new BigDecimal("9"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("1"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(seaCucumbers);
        Food abalone = Food.builder()
                .name("Abalone")
                .calories(new BigDecimal("105"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("10"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("44"))
                .B12(new BigDecimal("9.5"))
                .Calcium(new BigDecimal("17"))
                .Phosphorus(new BigDecimal("188"))
                .Magnesium(new BigDecimal("27"))
                .Sodium(new BigDecimal("333"))
                .Potassium(new BigDecimal("606"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("1.5"))
                .Zinc(new BigDecimal("4.6"))
                .Copper(new BigDecimal("1.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("31"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.1"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("0.8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(abalone);
        Food geoduck = Food.builder()
                .name("Geoduck")
                .calories(new BigDecimal("92"))
                .A(new BigDecimal("10"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("3"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("2"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("9"))
                .B12(new BigDecimal("15"))
                .Calcium(new BigDecimal("59"))
                .Phosphorus(new BigDecimal("240"))
                .Magnesium(new BigDecimal("32"))
                .Sodium(new BigDecimal("377"))
                .Potassium(new BigDecimal("760"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("6"))
                .Zinc(new BigDecimal("5"))
                .Copper(new BigDecimal("2"))
                .Manganese(new BigDecimal("0.5"))
                .Iodine(new BigDecimal("15"))
                .Selenium(new BigDecimal("34"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2.8"))
                .Protein(new BigDecimal("15"))
                .Fat(new BigDecimal("1.5"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.3"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(geoduck);
        Food conch = Food.builder()
                .name("Conch")
                .calories(new BigDecimal("70"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("2"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("11"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("1.8"))
                .Calcium(new BigDecimal("38"))
                .Phosphorus(new BigDecimal("197"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("270"))
                .Potassium(new BigDecimal("242"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.3"))
                .Zinc(new BigDecimal("2"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("10"))
                .Selenium(new BigDecimal("24"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("6"))
                .Protein(new BigDecimal("17"))
                .Fat(new BigDecimal("0.8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.1"))
                .build();

        foodRepository.addFood(conch);
        Food seaScallops = Food.builder()
                .name("Sea Scallops")
                .calories(new BigDecimal("69"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("0.9"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("189"))
                .Magnesium(new BigDecimal("26"))
                .Sodium(new BigDecimal("161"))
                .Potassium(new BigDecimal("316"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("12"))
                .Selenium(new BigDecimal("18"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("1.5"))
                .Protein(new BigDecimal("14"))
                .Fat(new BigDecimal("1.1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(seaScallops);
        Food kingCrab = Food.builder()
                .name("King Crab")
                .calories(new BigDecimal("87"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.2"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("9.8"))
                .Calcium(new BigDecimal("56"))
                .Phosphorus(new BigDecimal("141"))
                .Magnesium(new BigDecimal("32"))
                .Sodium(new BigDecimal("990"))
                .Potassium(new BigDecimal("314"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("3.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("180"))
                .Selenium(new BigDecimal("51"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(kingCrab);
        Food dungenessCrab = Food.builder()
                .name("Dungeness Crab")
                .calories(new BigDecimal("82"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("4"))
                .Calcium(new BigDecimal("83"))
                .Phosphorus(new BigDecimal("200"))
                .Magnesium(new BigDecimal("40"))
                .Sodium(new BigDecimal("683"))
                .Potassium(new BigDecimal("294"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.9"))
                .Zinc(new BigDecimal("3.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("200"))
                .Selenium(new BigDecimal("51"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("1.2"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(dungenessCrab);
        Food stoneCrab = Food.builder()
                .name("Stone Crab")
                .calories(new BigDecimal("88"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("7"))
                .Calcium(new BigDecimal("62"))
                .Phosphorus(new BigDecimal("147"))
                .Magnesium(new BigDecimal("30"))
                .Sodium(new BigDecimal("556"))
                .Potassium(new BigDecimal("223"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("300"))
                .Selenium(new BigDecimal("38"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.1"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(stoneCrab);
        Food snowCrab = Food.builder()
                .name("Snow Crab")
                .calories(new BigDecimal("100"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("8"))
                .Calcium(new BigDecimal("76"))
                .Phosphorus(new BigDecimal("178"))
                .Magnesium(new BigDecimal("47"))
                .Sodium(new BigDecimal("634"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("160"))
                .Selenium(new BigDecimal("40"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("0.7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(snowCrab);
        Food spiderCrab = Food.builder()
                .name("Spider Crab")
                .calories(new BigDecimal("83"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.07"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("8"))
                .Calcium(new BigDecimal("76"))
                .Phosphorus(new BigDecimal("178"))
                .Magnesium(new BigDecimal("47"))
                .Sodium(new BigDecimal("634"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("160"))
                .Selenium(new BigDecimal("40"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(spiderCrab);
        Food blueCrab = Food.builder()
                .name("Blue Crab")
                .calories(new BigDecimal("83"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.3"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("8"))
                .B12(new BigDecimal("11"))
                .Calcium(new BigDecimal("76"))
                .Phosphorus(new BigDecimal("204"))
                .Magnesium(new BigDecimal("45"))
                .Sodium(new BigDecimal("387"))
                .Potassium(new BigDecimal("300"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("2.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("130"))
                .Selenium(new BigDecimal("53"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.2"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(blueCrab);
        Food brownCrab = Food.builder()
                .name("Brown Crab")
                .calories(new BigDecimal("88"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.2"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("9"))
                .Calcium(new BigDecimal("118"))
                .Phosphorus(new BigDecimal("247"))
                .Magnesium(new BigDecimal("46"))
                .Sodium(new BigDecimal("470"))
                .Potassium(new BigDecimal("293"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.8"))
                .Zinc(new BigDecimal("4"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("190"))
                .Selenium(new BigDecimal("35"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.8"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(brownCrab);
        Food horsehairCrab = Food.builder()
                .name("Horsehair Crab")
                .calories(new BigDecimal("85"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.9"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.06"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("11"))
                .B12(new BigDecimal("10"))
                .Calcium(new BigDecimal("90"))
                .Phosphorus(new BigDecimal("209"))
                .Magnesium(new BigDecimal("34"))
                .Sodium(new BigDecimal("520"))
                .Potassium(new BigDecimal("270"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("2.7"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("150"))
                .Selenium(new BigDecimal("27"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("18"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.3"))
                .MonounsaturatedFat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(horsehairCrab);
        Food alaskanKingCrab = Food.builder()
                .name("Alaskan King Crab")
                .calories(new BigDecimal("82"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("1"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.03"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("9.8"))
                .Calcium(new BigDecimal("56"))
                .Phosphorus(new BigDecimal("141"))
                .Magnesium(new BigDecimal("32"))
                .Sodium(new BigDecimal("990"))
                .Potassium(new BigDecimal("314"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("3.5"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("180"))
                .Selenium(new BigDecimal("51"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("0.9"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(alaskanKingCrab);
        Food japaneseSpiderCrab = Food.builder()
                .name("Japanese Spider Crab")
                .calories(new BigDecimal("69"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.6"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.1"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("7"))
                .B12(new BigDecimal("0.9"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("189"))
                .Magnesium(new BigDecimal("26"))
                .Sodium(new BigDecimal("161"))
                .Potassium(new BigDecimal("316"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.5"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("12"))
                .Selenium(new BigDecimal("18"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("1.5"))
                .Protein(new BigDecimal("14"))
                .Fat(new BigDecimal("1.1"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("0.1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("0.2"))
                .MonounsaturatedFat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(japaneseSpiderCrab);
        Food coconutCrab = Food.builder()
                .name("Coconut Crab")
                .calories(new BigDecimal("420"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.6"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("2"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("36"))
                .Phosphorus(new BigDecimal("98"))
                .Magnesium(new BigDecimal("42"))
                .Sodium(new BigDecimal("200"))
                .Potassium(new BigDecimal("354"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("3.6"))
                .Zinc(new BigDecimal("3"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("120"))
                .Selenium(new BigDecimal("28"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("3.3"))
                .Protein(new BigDecimal("19"))
                .Fat(new BigDecimal("34"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("19"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.6"))
                .MonounsaturatedFat(new BigDecimal("9"))
                .build();

        foodRepository.addFood(coconutCrab);
        Food mantisShrimp = Food.builder()
                .name("Mantis Shrimp")
                .calories(new BigDecimal("128"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2"))
                .K(new BigDecimal("1"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.05"))
                .B2(new BigDecimal("0.13"))
                .B3(new BigDecimal("0.5"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("12"))
                .B12(new BigDecimal("2.5"))
                .Calcium(new BigDecimal("44"))
                .Phosphorus(new BigDecimal("197"))
                .Magnesium(new BigDecimal("70"))
                .Sodium(new BigDecimal("140"))
                .Potassium(new BigDecimal("520"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("2.5"))
                .Zinc(new BigDecimal("1.4"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("20"))
                .Selenium(new BigDecimal("33"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("2"))
                .Protein(new BigDecimal("23"))
                .Fat(new BigDecimal("7"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1.5"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1.5"))
                .MonounsaturatedFat(new BigDecimal("2"))
                .build();

        foodRepository.addFood(mantisShrimp);
        Food sharkMeat = Food.builder()
                .name("Shark Meat")
                .calories(new BigDecimal("110"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0.5"))
                .E(new BigDecimal("0.5"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("0"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.2"))
                .B3(new BigDecimal("1"))
                .B5(new BigDecimal("0"))
                .B6(new BigDecimal("0.1"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("6"))
                .B12(new BigDecimal("3"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("145"))
                .Magnesium(new BigDecimal("24"))
                .Sodium(new BigDecimal("50"))
                .Potassium(new BigDecimal("480"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.9"))
                .Zinc(new BigDecimal("1.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0"))
                .Iodine(new BigDecimal("30"))
                .Selenium(new BigDecimal("38"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("0"))
                .Protein(new BigDecimal("20"))
                .Fat(new BigDecimal("4"))
                .Fiber(new BigDecimal("0"))
                .TransFat(new BigDecimal("0"))
                .SaturatedFat(new BigDecimal("1"))
                .Sugar(new BigDecimal("0"))
                .PolyunsaturatedFat(new BigDecimal("1"))
                .MonounsaturatedFat(new BigDecimal("1.5"))
                .build();

        foodRepository.addFood(sharkMeat);

    }
}
