package org.food.repositories.FoodRepos;

import java.math.BigDecimal;

import org.food.domain.dtos.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class VegetableRepository {
    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food potato = Food.builder()
        .name("Potato")
        .calories(new BigDecimal("77"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.01"))
        .K(new BigDecimal("14"))
        .C(new BigDecimal("19.7"))
        .B1(new BigDecimal("0.08"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("1.1"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("12"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("12"))
        .Phosphorus(new BigDecimal("57"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("429"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.8"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("17"))
        .Protein(new BigDecimal("2"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("2.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("0.9"))
        .PolyunsaturatedFat(new BigDecimal("0"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(potato);
Food tomato = Food.builder()
        .name("Tomato")
        .calories(new BigDecimal("18"))
        .A(new BigDecimal("42"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("10"))
        .C(new BigDecimal("5.8"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("11"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("11"))
        .Phosphorus(new BigDecimal("26"))
        .Magnesium(new BigDecimal("11"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("237"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.3"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.9"))
        .Protein(new BigDecimal("0.9"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("2.6"))
        .PolyunsaturatedFat(new BigDecimal("0.08"))
        .MonounsaturatedFat(new BigDecimal("0.03"))
        .build();

foodRepository.addFood(tomato);
Food onion = Food.builder()
        .name("Onion")
        .calories(new BigDecimal("40"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.02"))
        .K(new BigDecimal("0.5"))
        .C(new BigDecimal("9.3"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("19"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("23"))
        .Phosphorus(new BigDecimal("29"))
        .Magnesium(new BigDecimal("10"))
        .Sodium(new BigDecimal("4"))
        .Potassium(new BigDecimal("146"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("1"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("9.3"))
        .Protein(new BigDecimal("1.1"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("1.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0"))
        .Sugar(new BigDecimal("4.7"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(onion);

Food carrot = Food.builder()
        .name("Carrot")
        .calories(new BigDecimal("41"))
        .A(new BigDecimal("835"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("13"))
        .C(new BigDecimal("8.2"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0.004"))
        .B9(new BigDecimal("19"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("33"))
        .Phosphorus(new BigDecimal("35"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("69"))
        .Potassium(new BigDecimal("320"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.3"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.04"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("1"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("10"))
        .Protein(new BigDecimal("0.9"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("4.7"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(carrot);
Food garlic = Food.builder()
        .name("Garlic")
        .calories(new BigDecimal("149"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.08"))
        .K(new BigDecimal("1.7"))
        .C(new BigDecimal("31.2"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.01"))
        .B3(new BigDecimal("1.2"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("1.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("3"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("181"))
        .Phosphorus(new BigDecimal("153"))
        .Magnesium(new BigDecimal("25"))
        .Sodium(new BigDecimal("17"))
        .Potassium(new BigDecimal("401"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.7"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.3"))
        .Manganese(new BigDecimal("1.7"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("14.2"))
        .Fluoride(new BigDecimal("1"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("33.1"))
        .Protein(new BigDecimal("6.4"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("2.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(garlic);
Food broccoli = Food.builder()
        .name("Broccoli")
        .calories(new BigDecimal("55"))
        .A(new BigDecimal("31"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.78"))
        .K(new BigDecimal("101"))
        .C(new BigDecimal("89"))
        .B1(new BigDecimal("0.06"))
        .B2(new BigDecimal("0.07"))
        .B3(new BigDecimal("0.7"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0.01"))
        .B9(new BigDecimal("63"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("47"))
        .Phosphorus(new BigDecimal("66"))
        .Magnesium(new BigDecimal("21"))
        .Sodium(new BigDecimal("33"))
        .Potassium(new BigDecimal("316"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.7"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.05"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("11"))
        .Protein(new BigDecimal("3.7"))
        .Fat(new BigDecimal("0.6"))
        .Fiber(new BigDecimal("2.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(broccoli);
Food cucumber = Food.builder()
        .name("Cucumber")
        .calories(new BigDecimal("15"))
        .A(new BigDecimal("3"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.03"))
        .K(new BigDecimal("16"))
        .C(new BigDecimal("2.8"))
        .B1(new BigDecimal("0.04"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.0"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0.019"))
        .B9(new BigDecimal("7"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("13"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("147"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.04"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.002"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.6"))
        .Protein(new BigDecimal("0.6"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("0.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(cucumber);
Food cauliflower = Food.builder()
        .name("Cauliflower")
        .calories(new BigDecimal("25"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.08"))
        .K(new BigDecimal("15"))
        .C(new BigDecimal("48.2"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.06"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("57"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("22"))
        .Phosphorus(new BigDecimal("44"))
        .Magnesium(new BigDecimal("15"))
        .Sodium(new BigDecimal("30"))
        .Potassium(new BigDecimal("299"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.05"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.04"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("5"))
        .Protein(new BigDecimal("1.9"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(cauliflower);
Food greenBeans = Food.builder()
        .name("Green Beans")
        .calories(new BigDecimal("31"))
        .A(new BigDecimal("54"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.41"))
        .K(new BigDecimal("25"))
        .C(new BigDecimal("16.3"))
        .B1(new BigDecimal("0.07"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.7"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("33"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("37"))
        .Phosphorus(new BigDecimal("38"))
        .Magnesium(new BigDecimal("25"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("211"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7"))
        .Protein(new BigDecimal("1.8"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.3"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(greenBeans);
Food lettuce = Food.builder()
        .name("Lettuce")
        .calories(new BigDecimal("5"))
        .A(new BigDecimal("740"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.15"))
        .K(new BigDecimal("102"))
        .C(new BigDecimal("5.4"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0.01"))
        .B9(new BigDecimal("38"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("36"))
        .Phosphorus(new BigDecimal("29"))
        .Magnesium(new BigDecimal("13"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("194"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.9"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.04"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("1"))
        .Protein(new BigDecimal("0.5"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("1.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.01"))
        .Sugar(new BigDecimal("0.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(lettuce);
Food eggplant = Food.builder()
        .name("Eggplant")
        .calories(new BigDecimal("25"))
        .A(new BigDecimal("3"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("3"))
        .C(new BigDecimal("3.5"))
        .B1(new BigDecimal("0.03"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("9"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("14"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("229"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6"))
        .Protein(new BigDecimal("1"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("3.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.03"))
        .build();

foodRepository.addFood(eggplant);
Food bellPeppers = Food.builder()
        .name("Bell Peppers")
        .calories(new BigDecimal("31"))
        .A(new BigDecimal("3131"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.37"))
        .K(new BigDecimal("141"))
        .C(new BigDecimal("92"))
        .B1(new BigDecimal("0.08"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.5"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("23"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("10"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("4"))
        .Potassium(new BigDecimal("211"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.0008"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6"))
        .Protein(new BigDecimal("1"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("4.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.03"))
        .build();

foodRepository.addFood(bellPeppers);
Food corn = Food.builder()
        .name("Corn")
        .calories(new BigDecimal("86"))
        .A(new BigDecimal("31"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.54"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("19"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("2.9"))
        .B5(new BigDecimal("0.6"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0.04"))
        .B9(new BigDecimal("27"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("2"))
        .Phosphorus(new BigDecimal("89"))
        .Magnesium(new BigDecimal("37"))
        .Sodium(new BigDecimal("15"))
        .Potassium(new BigDecimal("270"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.5"))
        .Zinc(new BigDecimal("0.9"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("19"))
        .Protein(new BigDecimal("2.5"))
        .Fat(new BigDecimal("1.3"))
        .Fiber(new BigDecimal("2.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.2"))
        .Sugar(new BigDecimal("6.3"))
        .PolyunsaturatedFat(new BigDecimal("0.6"))
        .MonounsaturatedFat(new BigDecimal("0.5"))
        .build();

foodRepository.addFood(corn);
Food zucchini = Food.builder()
        .name("Zucchini")
        .calories(new BigDecimal("17"))
        .A(new BigDecimal("23"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.12"))
        .K(new BigDecimal("4"))
        .C(new BigDecimal("9.6"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("24"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("38"))
        .Magnesium(new BigDecimal("18"))
        .Sodium(new BigDecimal("8"))
        .Potassium(new BigDecimal("261"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.5"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.1"))
        .Protein(new BigDecimal("1.2"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.05"))
        .Sugar(new BigDecimal("2.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.03"))
        .build();

foodRepository.addFood(zucchini);
Food mushrooms = Food.builder()
        .name("Mushrooms")
        .calories(new BigDecimal("22"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0.5"))
        .C(new BigDecimal("2.1"))
        .B1(new BigDecimal("0.01"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.5"))
        .B5(new BigDecimal("0.5"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("3"))
        .Phosphorus(new BigDecimal("86"))
        .Magnesium(new BigDecimal("9"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("318"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.5"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.005"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.3"))
        .Protein(new BigDecimal("3.1"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("2.1"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(mushrooms);
Food brusselsSprouts = Food.builder()
        .name("Brussels Sprouts")
        .calories(new BigDecimal("43"))
        .A(new BigDecimal("38"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.9"))
        .K(new BigDecimal("177"))
        .C(new BigDecimal("85"))
        .B1(new BigDecimal("0.09"))
        .B2(new BigDecimal("0.06"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("61"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("42"))
        .Phosphorus(new BigDecimal("69"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("25"))
        .Potassium(new BigDecimal("389"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.4"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.004"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("8.9"))
        .Protein(new BigDecimal("3.4"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("3.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("2.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(brusselsSprouts);
Food spinach = Food.builder()
        .name("Spinach")
        .calories(new BigDecimal("23"))
        .A(new BigDecimal("469"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.6"))
        .K(new BigDecimal("482"))
        .C(new BigDecimal("47"))
        .B1(new BigDecimal("0.08"))
        .B2(new BigDecimal("0.19"))
        .B3(new BigDecimal("0.7"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("49"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("99"))
        .Phosphorus(new BigDecimal("49"))
        .Magnesium(new BigDecimal("79"))
        .Sodium(new BigDecimal("79"))
        .Potassium(new BigDecimal("558"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.7"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.9"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.04"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.6"))
        .Protein(new BigDecimal("2.9"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("2.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.4"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(spinach);
Food asparagus = Food.builder()
        .name("Asparagus")
        .calories(new BigDecimal("20"))
        .A(new BigDecimal("38"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("1.1"))
        .K(new BigDecimal("41"))
        .C(new BigDecimal("5.4"))
        .B1(new BigDecimal("0.14"))
        .B2(new BigDecimal("0.14"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0.1"))
        .B9(new BigDecimal("24"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("24"))
        .Phosphorus(new BigDecimal("52"))
        .Magnesium(new BigDecimal("14"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("202"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.1"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.7"))
        .Protein(new BigDecimal("2.2"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.04"))
        .Sugar(new BigDecimal("1.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(asparagus);
Food sweetPotatoes = Food.builder()
        .name("Sweet Potatoes")
        .calories(new BigDecimal("86"))
        .A(new BigDecimal("709"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("1.6"))
        .C(new BigDecimal("2.4"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0.029"))
        .B9(new BigDecimal("11"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("30"))
        .Phosphorus(new BigDecimal("47"))
        .Magnesium(new BigDecimal("30"))
        .Sodium(new BigDecimal("55"))
        .Potassium(new BigDecimal("337"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("20"))
        .Protein(new BigDecimal("1.6"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.05"))
        .Sugar(new BigDecimal("4.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(sweetPotatoes);
Food peas = Food.builder()
        .name("Peas")
        .calories(new BigDecimal("81"))
        .A(new BigDecimal("765"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("24"))
        .C(new BigDecimal("42"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("2.1"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("62"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("244"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("14"))
        .Protein(new BigDecimal("5"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("5.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("5.7"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(peas);
Food artichokes = Food.builder()
        .name("Artichokes")
        .calories(new BigDecimal("47"))
        .A(new BigDecimal("13"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("14"))
        .C(new BigDecimal("11"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0.1"))
        .B9(new BigDecimal("68"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("44"))
        .Phosphorus(new BigDecimal("73"))
        .Magnesium(new BigDecimal("60"))
        .Sodium(new BigDecimal("94"))
        .Potassium(new BigDecimal("370"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.3"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.03"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("11"))
        .Protein(new BigDecimal("3.3"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("8.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.6"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(artichokes);
Food leeks = Food.builder()
        .name("Leeks")
        .calories(new BigDecimal("61"))
        .A(new BigDecimal("29"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.9"))
        .K(new BigDecimal("47"))
        .C(new BigDecimal("12"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("64"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("59"))
        .Phosphorus(new BigDecimal("35"))
        .Magnesium(new BigDecimal("22"))
        .Sodium(new BigDecimal("20"))
        .Potassium(new BigDecimal("180"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.1"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("14"))
        .Protein(new BigDecimal("1.5"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("1.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(leeks);
Food celery = Food.builder()
        .name("Celery")
        .calories(new BigDecimal("16"))
        .A(new BigDecimal("22"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("29"))
        .C(new BigDecimal("3.1"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.01"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("36"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("40"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("11"))
        .Sodium(new BigDecimal("80"))
        .Potassium(new BigDecimal("260"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.1"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3"))
        .Protein(new BigDecimal("0.7"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.8"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(celery);
Food radishes = Food.builder()
        .name("Radishes")
        .calories(new BigDecimal("16"))
        .A(new BigDecimal("1"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("10"))
        .C(new BigDecimal("14.8"))
        .B1(new BigDecimal("0.01"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("20"))
        .Magnesium(new BigDecimal("10"))
        .Sodium(new BigDecimal("39"))
        .Potassium(new BigDecimal("233"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.4"))
        .Protein(new BigDecimal("0.7"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("1.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.02"))
        .Sugar(new BigDecimal("1.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(radishes);
Food beets = Food.builder()
        .name("Beets")
        .calories(new BigDecimal("43"))
        .A(new BigDecimal("2"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("8.2"))
        .B1(new BigDecimal("0.03"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("80"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("40"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("78"))
        .Potassium(new BigDecimal("325"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.8"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("9.6"))
        .Protein(new BigDecimal("1.6"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("6.8"))
        .PolyunsaturatedFat(new BigDecimal("0.07"))
        .MonounsaturatedFat(new BigDecimal("0.01"))
        .build();

foodRepository.addFood(beets);
Food pumpkin = Food.builder()
        .name("Pumpkin")
        .calories(new BigDecimal("26"))
        .A(new BigDecimal("426"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("1"))
        .C(new BigDecimal("6.5"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("16"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("21"))
        .Phosphorus(new BigDecimal("44"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("1"))
        .Potassium(new BigDecimal("340"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.8"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6.5"))
        .Protein(new BigDecimal("1"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("0.5"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("2.8"))
        .PolyunsaturatedFat(new BigDecimal("0.05"))
        .MonounsaturatedFat(new BigDecimal("0.01"))
        .build();

foodRepository.addFood(pumpkin);
Food greenPeas = Food.builder()
        .name("Green Peas")
        .calories(new BigDecimal("81"))
        .A(new BigDecimal("765"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("24"))
        .C(new BigDecimal("42"))
        .B1(new BigDecimal("0.3"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("2.1"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("25"))
        .Phosphorus(new BigDecimal("62"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("244"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("1.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("14"))
        .Protein(new BigDecimal("5"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("5.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("5.7"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(greenPeas);
Food kale = Food.builder()
        .name("Kale")
        .calories(new BigDecimal("49"))
        .A(new BigDecimal("4812"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("389"))
        .C(new BigDecimal("93"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("141"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("254"))
        .Phosphorus(new BigDecimal("55"))
        .Magnesium(new BigDecimal("47"))
        .Sodium(new BigDecimal("38"))
        .Potassium(new BigDecimal("491"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("8.8"))
        .Protein(new BigDecimal("3.3"))
        .Fat(new BigDecimal("0.9"))
        .Fiber(new BigDecimal("3.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.4"))
        .PolyunsaturatedFat(new BigDecimal("0.4"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(kale);
Food fennel = Food.builder()
        .name("Fennel")
        .calories(new BigDecimal("31"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("62"))
        .C(new BigDecimal("12"))
        .B1(new BigDecimal("0.01"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("45"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("49"))
        .Phosphorus(new BigDecimal("50"))
        .Magnesium(new BigDecimal("17"))
        .Sodium(new BigDecimal("52"))
        .Potassium(new BigDecimal("414"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.7"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.04"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7.3"))
        .Protein(new BigDecimal("1.2"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.02"))
        .Sugar(new BigDecimal("3.9"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(fennel);
Food aubergine = Food.builder()
        .name("Aubergine (Eggplant)")
        .calories(new BigDecimal("25"))
        .A(new BigDecimal("3"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("3"))
        .C(new BigDecimal("3.5"))
        .B1(new BigDecimal("0.03"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("9"))
        .Phosphorus(new BigDecimal("24"))
        .Magnesium(new BigDecimal("14"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("229"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.2"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("5.9"))
        .Protein(new BigDecimal("1"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("3.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.01"))
        .build();

foodRepository.addFood(aubergine);
Food jalapeno = Food.builder()
        .name("Jalapeño")
        .calories(new BigDecimal("29"))
        .A(new BigDecimal("570"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("259"))
        .C(new BigDecimal("118"))
        .B1(new BigDecimal("0.07"))
        .B2(new BigDecimal("0.05"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.3"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("0"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("26"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("340"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.03"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("5.7"))
        .Protein(new BigDecimal("1.2"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("2.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.2"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(jalapeno);
Food swissChard = Food.builder()
        .name("Swiss Chard")
        .calories(new BigDecimal("19"))
        .A(new BigDecimal("6117"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("1.9"))
        .K(new BigDecimal("830"))
        .C(new BigDecimal("30"))
        .B1(new BigDecimal("0.04"))
        .B2(new BigDecimal("0.05"))
        .B3(new BigDecimal("0.9"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("81"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("51"))
        .Phosphorus(new BigDecimal("46"))
        .Magnesium(new BigDecimal("81"))
        .Sodium(new BigDecimal("213"))
        .Potassium(new BigDecimal("379"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.6"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.36"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.7"))
        .Protein(new BigDecimal("1.8"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("1.1"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(swissChard);
Food bokChoy = Food.builder()
        .name("Bok Choy")
        .calories(new BigDecimal("13"))
        .A(new BigDecimal("630"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("45"))
        .C(new BigDecimal("21"))
        .B1(new BigDecimal("0.03"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("37"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("105"))
        .Phosphorus(new BigDecimal("37"))
        .Magnesium(new BigDecimal("19"))
        .Sodium(new BigDecimal("65"))
        .Potassium(new BigDecimal("252"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.8"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.03"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("2.2"))
        .Protein(new BigDecimal("1.5"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("1.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(bokChoy);
Food napaCabbage = Food.builder()
        .name("Napa Cabbage")
        .calories(new BigDecimal("12"))
        .A(new BigDecimal("446"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("38"))
        .C(new BigDecimal("36"))
        .B1(new BigDecimal("0.04"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("28"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("23"))
        .Phosphorus(new BigDecimal("16"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("8"))
        .Potassium(new BigDecimal("252"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("2.2"))
        .Protein(new BigDecimal("1.2"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("1.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.02"))
        .Sugar(new BigDecimal("1.2"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(napaCabbage);
Food edamame = Food.builder()
        .name("Edamame")
        .calories(new BigDecimal("121"))
        .A(new BigDecimal("13"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("49"))
        .C(new BigDecimal("11"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("205"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("63"))
        .Phosphorus(new BigDecimal("122"))
        .Magnesium(new BigDecimal("54"))
        .Sodium(new BigDecimal("6"))
        .Potassium(new BigDecimal("436"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("2.1"))
        .Zinc(new BigDecimal("1.6"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("1.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.010"))
        .Fluoride(new BigDecimal("0.3"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("8.7"))
        .Protein(new BigDecimal("11"))
        .Fat(new BigDecimal("5.2"))
        .Fiber(new BigDecimal("5.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.7"))
        .Sugar(new BigDecimal("3.7"))
        .PolyunsaturatedFat(new BigDecimal("2.1"))
        .MonounsaturatedFat(new BigDecimal("1.2"))
        .build();

foodRepository.addFood(edamame);
Food bambooShoots = Food.builder()
        .name("Bamboo Shoots")
        .calories(new BigDecimal("27"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.6"))
        .K(new BigDecimal("3"))
        .C(new BigDecimal("5.5"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("1.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("11"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("9"))
        .Phosphorus(new BigDecimal("27"))
        .Magnesium(new BigDecimal("8"))
        .Sodium(new BigDecimal("1"))
        .Potassium(new BigDecimal("533"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.03"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("5.2"))
        .Protein(new BigDecimal("2.6"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("2.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("3.3"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(bambooShoots);
Food waterChestnuts = Food.builder()
        .name("Water Chestnuts")
        .calories(new BigDecimal("97"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("25"))
        .C(new BigDecimal("24"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.1"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("11"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("17"))
        .Phosphorus(new BigDecimal("31"))
        .Magnesium(new BigDecimal("32"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("584"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.5"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.3"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.001"))
        .Fluoride(new BigDecimal("0.2"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("24"))
        .Protein(new BigDecimal("2"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.04"))
        .Sugar(new BigDecimal("4.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(waterChestnuts);
Food lotusRoot = Food.builder()
        .name("Lotus Root")
        .calories(new BigDecimal("74"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("6"))
        .C(new BigDecimal("9"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("26"))
        .Phosphorus(new BigDecimal("45"))
        .Magnesium(new BigDecimal("13"))
        .Sodium(new BigDecimal("44"))
        .Potassium(new BigDecimal("556"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.002"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("17"))
        .Protein(new BigDecimal("1.6"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.02"))
        .Sugar(new BigDecimal("3.4"))
        .PolyunsaturatedFat(new BigDecimal("0.05"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(lotusRoot);
Food kohlrabi = Food.builder()
        .name("Kohlrabi")
        .calories(new BigDecimal("27"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("62"))
        .B1(new BigDecimal("0.04"))
        .B2(new BigDecimal("0.02"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.15"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("25"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("24"))
        .Phosphorus(new BigDecimal("48"))
        .Magnesium(new BigDecimal("19"))
        .Sodium(new BigDecimal("20"))
        .Potassium(new BigDecimal("350"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6.2"))
        .Protein(new BigDecimal("0.9"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("3.6"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("2.6"))
        .PolyunsaturatedFat(new BigDecimal("0.05"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(kohlrabi);
Food rutabagas = Food.builder()
        .name("Rutabagas")
        .calories(new BigDecimal("38"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("0"))
        .C(new BigDecimal("25"))
        .B1(new BigDecimal("0.03"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.07"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("8"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("43"))
        .Phosphorus(new BigDecimal("61"))
        .Magnesium(new BigDecimal("20"))
        .Sodium(new BigDecimal("20"))
        .Potassium(new BigDecimal("305"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.3"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.1"))
        .Fluoride(new BigDecimal("0.03"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("8.4"))
        .Protein(new BigDecimal("1.1"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2.3"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("5.3"))
        .PolyunsaturatedFat(new BigDecimal("0.08"))
        .MonounsaturatedFat(new BigDecimal("0"))
        .build();

foodRepository.addFood(rutabagas);
Food yams = Food.builder()
        .name("Yams")
        .calories(new BigDecimal("118"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("2"))
        .C(new BigDecimal("28.9"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.4"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("11"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("17"))
        .Phosphorus(new BigDecimal("55"))
        .Magnesium(new BigDecimal("21"))
        .Sodium(new BigDecimal("9"))
        .Potassium(new BigDecimal("816"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.5"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("27.9"))
        .Protein(new BigDecimal("1.5"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("4.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("0.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.04"))
        .build();

foodRepository.addFood(yams);
Food taro = Food.builder()
        .name("Taro")
        .calories(new BigDecimal("112"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("20"))
        .C(new BigDecimal("19.7"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.2"))
        .B5(new BigDecimal("0.6"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("22"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("43"))
        .Phosphorus(new BigDecimal("48"))
        .Magnesium(new BigDecimal("33"))
        .Sodium(new BigDecimal("11"))
        .Potassium(new BigDecimal("591"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.2"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("26.5"))
        .Protein(new BigDecimal("0.5"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("4.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.04"))
        .Sugar(new BigDecimal("0.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(taro);
Food cassava = Food.builder()
        .name("Cassava")
        .calories(new BigDecimal("160"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.2"))
        .K(new BigDecimal("21"))
        .C(new BigDecimal("20.6"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.3"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("27"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("27"))
        .Magnesium(new BigDecimal("21"))
        .Sodium(new BigDecimal("14"))
        .Potassium(new BigDecimal("271"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.3"))
        .Zinc(new BigDecimal("0.3"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.4"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("38.1"))
        .Protein(new BigDecimal("1.4"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("1.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.03"))
        .build();

foodRepository.addFood(cassava);
Food okra = Food.builder()
        .name("Okra")
        .calories(new BigDecimal("33"))
        .A(new BigDecimal("621"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.3"))
        .K(new BigDecimal("31"))
        .C(new BigDecimal("23"))
        .B1(new BigDecimal("0.2"))
        .B2(new BigDecimal("0.04"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.2"))
        .B6(new BigDecimal("0.2"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("88"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("82"))
        .Phosphorus(new BigDecimal("30"))
        .Magnesium(new BigDecimal("57"))
        .Sodium(new BigDecimal("7"))
        .Potassium(new BigDecimal("299"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.8"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("7"))
        .Protein(new BigDecimal("1.9"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.1"))
        .Sugar(new BigDecimal("1.5"))
        .PolyunsaturatedFat(new BigDecimal("0.1"))
        .MonounsaturatedFat(new BigDecimal("0.1"))
        .build();

foodRepository.addFood(okra);
Food chayote = Food.builder()
        .name("Chayote")
        .calories(new BigDecimal("19"))
        .A(new BigDecimal("0"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.1"))
        .K(new BigDecimal("12"))
        .C(new BigDecimal("7.7"))
        .B1(new BigDecimal("0.02"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.03"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("21"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("16"))
        .Phosphorus(new BigDecimal("12"))
        .Magnesium(new BigDecimal("12"))
        .Sodium(new BigDecimal("2"))
        .Potassium(new BigDecimal("125"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.4"))
        .Zinc(new BigDecimal("0.1"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.1"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("4.5"))
        .Protein(new BigDecimal("0.8"))
        .Fat(new BigDecimal("0.1"))
        .Fiber(new BigDecimal("1.7"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.03"))
        .Sugar(new BigDecimal("1.4"))
        .PolyunsaturatedFat(new BigDecimal("0.04"))
        .MonounsaturatedFat(new BigDecimal("0.01"))
        .build();

foodRepository.addFood(chayote);
Food nopales = Food.builder()
        .name("Nopales")
        .calories(new BigDecimal("16"))
        .A(new BigDecimal("499"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.4"))
        .K(new BigDecimal("5"))
        .C(new BigDecimal("3.3"))
        .B1(new BigDecimal("0.05"))
        .B2(new BigDecimal("0.03"))
        .B3(new BigDecimal("0.1"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.04"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("3"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("183"))
        .Phosphorus(new BigDecimal("12"))
        .Magnesium(new BigDecimal("21"))
        .Sodium(new BigDecimal("5"))
        .Potassium(new BigDecimal("257"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.1"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.2"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.3"))
        .Protein(new BigDecimal("1.2"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.04"))
        .Sugar(new BigDecimal("0.2"))
        .PolyunsaturatedFat(new BigDecimal("0.05"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(nopales);
Food collardGreens = Food.builder()
        .name("Collard Greens")
        .calories(new BigDecimal("32"))
        .A(new BigDecimal("333"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.7"))
        .K(new BigDecimal("389"))
        .C(new BigDecimal("35"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.05"))
        .B3(new BigDecimal("0.6"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("57"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("232"))
        .Phosphorus(new BigDecimal("42"))
        .Magnesium(new BigDecimal("23"))
        .Sodium(new BigDecimal("12"))
        .Potassium(new BigDecimal("316"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.5"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0.04"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("6"))
        .Protein(new BigDecimal("2.1"))
        .Fat(new BigDecimal("0.5"))
        .Fiber(new BigDecimal("4"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.07"))
        .Sugar(new BigDecimal("0.4"))
        .PolyunsaturatedFat(new BigDecimal("0.14"))
        .MonounsaturatedFat(new BigDecimal("0.05"))
        .build();

foodRepository.addFood(collardGreens);
Food mustardGreens = Food.builder()
        .name("Mustard Greens")
        .calories(new BigDecimal("27"))
        .A(new BigDecimal("7165"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("0.5"))
        .K(new BigDecimal("497"))
        .C(new BigDecimal("70"))
        .B1(new BigDecimal("0.1"))
        .B2(new BigDecimal("0.05"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.3"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("64"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("115"))
        .Phosphorus(new BigDecimal("43"))
        .Magnesium(new BigDecimal("25"))
        .Sodium(new BigDecimal("27"))
        .Potassium(new BigDecimal("314"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("0.6"))
        .Zinc(new BigDecimal("0.4"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.9"))
        .Fluoride(new BigDecimal("0.01"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("4.7"))
        .Protein(new BigDecimal("2.9"))
        .Fat(new BigDecimal("0.3"))
        .Fiber(new BigDecimal("3.2"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.07"))
        .Sugar(new BigDecimal("1.3"))
        .PolyunsaturatedFat(new BigDecimal("0.16"))
        .MonounsaturatedFat(new BigDecimal("0.07"))
        .build();

foodRepository.addFood(mustardGreens);
Food turnipGreens = Food.builder()
        .name("Turnip Greens")
        .calories(new BigDecimal("20"))
        .A(new BigDecimal("337"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("1.5"))
        .K(new BigDecimal("592"))
        .C(new BigDecimal("39"))
        .B1(new BigDecimal("0.08"))
        .B2(new BigDecimal("0.05"))
        .B3(new BigDecimal("0.4"))
        .B5(new BigDecimal("0.1"))
        .B6(new BigDecimal("0.1"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("19"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("190"))
        .Phosphorus(new BigDecimal("42"))
        .Magnesium(new BigDecimal("32"))
        .Sodium(new BigDecimal("12"))
        .Potassium(new BigDecimal("291"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("1.5"))
        .Zinc(new BigDecimal("0.2"))
        .Copper(new BigDecimal("0.1"))
        .Manganese(new BigDecimal("0.5"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.6"))
        .Fluoride(new BigDecimal("0.02"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("3.7"))
        .Protein(new BigDecimal("1.5"))
        .Fat(new BigDecimal("0.2"))
        .Fiber(new BigDecimal("3.1"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.04"))
        .Sugar(new BigDecimal("0.9"))
        .PolyunsaturatedFat(new BigDecimal("0.08"))
        .MonounsaturatedFat(new BigDecimal("0.02"))
        .build();

foodRepository.addFood(turnipGreens);
Food fiddleheads = Food.builder()
        .name("Fiddleheads")
        .calories(new BigDecimal("34"))
        .A(new BigDecimal("1052"))
        .D(new BigDecimal("0"))
        .E(new BigDecimal("1.49"))
        .K(new BigDecimal("34"))
        .C(new BigDecimal("9.8"))
        .B1(new BigDecimal("0.31"))
        .B2(new BigDecimal("0.09"))
        .B3(new BigDecimal("1.61"))
        .B5(new BigDecimal("0.27"))
        .B6(new BigDecimal("0.24"))
        .B7(new BigDecimal("0"))
        .B9(new BigDecimal("34"))
        .B12(new BigDecimal("0"))
        .Calcium(new BigDecimal("34"))
        .Phosphorus(new BigDecimal("101"))
        .Magnesium(new BigDecimal("21"))
        .Sodium(new BigDecimal("3"))
        .Potassium(new BigDecimal("370"))
        .Chloride(new BigDecimal("0"))
        .Iron(new BigDecimal("5.4"))
        .Zinc(new BigDecimal("1"))
        .Copper(new BigDecimal("0.3"))
        .Manganese(new BigDecimal("1.6"))
        .Iodine(new BigDecimal("0"))
        .Selenium(new BigDecimal("0.7"))
        .Fluoride(new BigDecimal("0.23"))
        .Chromium(new BigDecimal("0"))
        .Molybdenum(new BigDecimal("0"))
        .Carbohydrates(new BigDecimal("5.9"))
        .Protein(new BigDecimal("3.3"))
        .Fat(new BigDecimal("0.4"))
        .Fiber(new BigDecimal("2.8"))
        .TransFat(new BigDecimal("0"))
        .SaturatedFat(new BigDecimal("0.07"))
        .Sugar(new BigDecimal("1.7"))
        .PolyunsaturatedFat(new BigDecimal("0.22"))
        .MonounsaturatedFat(new BigDecimal("0.05"))
        .build();

foodRepository.addFood(fiddleheads);

    }
}
