const vitaminD = {
    description:"Vitamin D, also known as calciferol, is a fat-soluble vitamin naturally found in select foods, added to others, and available as a dietary supplement. It is synthesized endogenously in the skin upon exposure to ultraviolet (UV) rays from sunlight.",
    functions: {
        "Bone Health":"Vitamin D promotes calcium absorption in the gut, ensuring adequate serum calcium and phosphate concentrations for normal bone mineralization. It supports bone growth and remodeling by osteoblasts and osteoclasts, preventing conditions like rickets in children and osteomalacia in adults. Together with calcium, it helps protect against osteoporosis in older adults.",
        "Reduction of Inflammation" : "Vitamin D has been linked to the reduction of inflammation in the body. This function is crucial for overall health, as chronic inflammation is associated with various diseases and conditions.",
        "Modulation of Cellular Processes" : "Vitamin D modulates processes such as cell growth, neuromuscular function, immune function, and glucose metabolism. It influences the expression of genes involved in cell proliferation, differentiation, and apoptosis, highlighting its role in maintaining cellular health and function.",
        "Immune Function" : "Vitamin D is involved in the modulation of immune function, which may contribute to reducing the risk and severity of infections. It has been associated with lower rates of respiratory diseases like pneumonia and infections such as measles and diarrhea, indicating its importance in maintaining immune health.",
    },
    sources: {
        "Food Sources":"Fatty fish such as trout, salmon, tuna, and mackerel, along with fish liver oils, are rich sources of vitamin D. Animal-based foods like beef liver, egg yolks, and cheese provide small amounts, primarily in the form of vitamin D3 and its metabolite 25(OH)D3. Mushrooms, particularly those treated with UV light, contain variable amounts of vitamin D2. Fortified foods such as milk, margarine, plant-based milk alternatives, ready-to-eat breakfast cereals, orange juice, and yogurt also contribute to vitamin D intake.",
        "Sun Exposure":"Vitamin D synthesis occurs when the skin is exposed to UVB radiation from sunlight. Factors like season, time of day, length of exposure, cloud cover, smog, skin melanin content, and sunscreen usage influence this process. UVB radiation does not penetrate glass, and some individuals, especially older people and those with dark skin, may have reduced ability to produce vitamin D from sunlight.",
        "Dietary Supplements" : "Vitamin D2 and D3 are available in dietary supplements. Vitamin D2 is synthesized using UV irradiation of ergosterol in yeast, while vitamin D3 is typically produced from lanolin obtained from sheep's wool. An animal-free option of vitamin D3 sourced from lichen is also available. Both forms are effective in raising serum 25(OH)D levels, with evidence suggesting that vitamin D3 may be more potent and longer-lasting."
    },
    dailyIntake: "The Estimated Average Requirement (EAR) for vitamin D is set at 10 mcg (400 IU) for most individuals. This recommendation aims to meet the needs of about 50% of the population. However, the Recommended Dietary Allowance (RDA) may be higher, with some studies suggesting an intake of up to 20 mcg (800 IU) or more per day for certain age groups and populations. These recommendations take into account factors such as age, sex, pregnancy, and lactation status. Additionally, factors like sun exposure and individual differences in vitamin D metabolism can influence the required intake.",
    deficiency: "Vitamin D deficiency can lead to significant health issues. In children, it causes rickets, characterized by soft, weak, deformed bones, and pain. In teens and adults, it results in osteomalacia, leading to bone pain and muscle weakness.",
    res: ["https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/" , "https://ods.od.nih.gov/factsheets/VitaminD-Consumer/#h7"]
};

export default vitaminD;