const vitaminE = {
    description: "Vitamin E is found naturally in some foods, added to others, and available as a dietary supplement. Vitamin E is the collective name for a group of fat-soluble compounds with distinctive antioxidant activities. Naturally occurring vitamin E exists in eight chemical forms (alpha-, beta-, gamma-, and delta-tocopherol and alpha-, beta-, gamma-, and delta-tocotrienol) that have varying levels of biological activity. Alpha- (or α-) tocopherol is the only form that is recognized to meet human requirements.\n" +
        "\n" +
        "Serum concentrations of vitamin E (alpha-tocopherol) depend on the liver, which takes up the nutrient after the various forms are absorbed from the small intestine. The liver preferentially resecretes only alpha-tocopherol via the hepatic alpha-tocopherol transfer protein; the liver metabolizes and excretes the other vitamin E forms. As a result, blood and cellular concentrations of other forms of vitamin E are lower than those of alpha-tocopherol and have been the subjects of less research.",
    functions: {
        "Antioxidant activity": "Vitamin E, specifically alpha-tocopherol, serves as a fat-soluble antioxidant, which helps in stopping the production of reactive oxygen species (ROS) formed during fat oxidation. This activity is crucial in protecting cells from oxidative damage caused by free radicals, potentially preventing or delaying chronic diseases associated with oxidative stress.",
        "Immune function": "Vitamin E plays a role in immune function, although the exact mechanisms are still being researched. It is involved in various metabolic processes, cell signaling, and gene expression related to immune responses.",
        "Regulation of gene expression": "Vitamin E, particularly alpha-tocopherol, is implicated in the regulation of gene expression. This function has been observed primarily in in vitro studies of cells.",
        "Inhibition of protein kinase C activity": "Alpha-tocopherol inhibits the activity of protein kinase C, an enzyme involved in cell proliferation and differentiation in smooth muscle cells, platelets, and monocytes. This inhibition may have implications for various physiological processes."
    },
    sources: {
        "Food": "Numerous foods provide vitamin E. Nuts and seeds, such as sunflower seeds and almonds, and vegetable oils like wheat germ oil, sunflower oil, and safflower oil, are among the best sources of alpha-tocopherol. Green leafy vegetables, including spinach and broccoli, and fortified cereals also contribute significant amounts. Other sources include peanut butter, peanuts, corn oil, kiwifruit, mango, and tomatoes. Most vitamin E in American diets is in the form of gamma-tocopherol from oils like soybean, canola, and corn.",
        "Dietary Supplements": "Supplements of vitamin E typically provide only alpha-tocopherol, though mixed tocopherol and tocotrienol products are available. Naturally occurring alpha-tocopherol is more biologically active than synthetic forms, which contain a mix of stereoisomers. Most vitamin-E-only supplements provide ≥67 mg (100 IU of natural vitamin E), substantially higher than the RDAs. These supplements often contain esterified forms of alpha-tocopherol to prolong shelf life and protect antioxidant properties, which are effectively hydrolyzed and absorbed by the body."
    },
    dailyIntake: "The Food and Nutrition Board recommends daily intakes of vitamin E (alpha-tocopherol) to ensure nutritional adequacy, varying by age and gender. For individuals 14 years and older, the Recommended Dietary Allowance (RDA) is 15 mg for both males and females, 15 mg for pregnant women, and 19 mg for lactating women. Vitamin E can be measured in milligrams or International Units (IU), with conversion factors of 1 mg equal to 1.49 IU for the natural form and 2.22 IU for the synthetic form.",
    deficiency: "Vitamin E deficiency is very rare in healthy individuals and usually associated with conditions that impair fat digestion or absorption, such as Crohn’s disease, cystic fibrosis, and certain genetic disorders like abetalipoproteinemia and AVED. Fat is necessary for vitamin E absorption. Deficiency can cause nerve and muscle damage, leading to symptoms like loss of feeling in limbs, loss of movement control, muscle weakness, vision problems, and a weakened immune system.",
    res: ["https://ods.od.nih.gov/factsheets/VitaminE-HealthProfessional/","https://ods.od.nih.gov/factsheets/VitaminE-Consumer/#h6"]
};

export default vitaminE;