const vitaminB2 = {
    description: "Riboflavin, also known as vitamin B2, is a water-soluble vitamin essential for various bodily functions. It is naturally present in foods, added to fortified products, and available as a dietary supplement. Riboflavin is crucial for energy production, cellular function, growth, and metabolism. It forms two major coenzymes, FMN and FAD, vital for numerous metabolic processes, including the conversion of tryptophan to niacin and vitamin B6 to pyridoxal 5’-phosphate.",
    functions: {
        "Energy Production": "Riboflavin is a critical component of two major coenzymes, flavin mononucleotide (FMN) and flavin adenine dinucleotide (FAD), which play vital roles in energy metabolism. These coenzymes are involved in the process of converting carbohydrates, fats, and proteins into energy.",
        "Cellular Function": "FMN and FAD coenzymes are essential for various cellular functions, including growth, development, and maintenance. They participate in numerous metabolic pathways that regulate cell processes and contribute to overall cellular health.",
        "Metabolism": "Riboflavin is necessary for the metabolism of fats, drugs, and steroids. It is involved in the conversion of the amino acid tryptophan to niacin (vitamin B3) and vitamin B6 to its active coenzyme form, pyridoxal 5’-phosphate.",
        "Maintenance of Homocysteine Levels": "Riboflavin helps maintain normal levels of homocysteine, an amino acid in the blood. Elevated levels of homocysteine are associated with an increased risk of cardiovascular disease, making riboflavin essential for heart health.",
    },
    sources: {
        "Food Sources": "Eggs, organ meats (such as kidneys and liver), lean meats, and milk are rich sources of riboflavin. Some vegetables contain riboflavin, while grains and cereals are often fortified with it in many countries, including the United States. Major dietary contributors to riboflavin intake in the US include milk, bread, mixed foods with meat or grains, and ready-to-eat cereals. Riboflavin in most foods exists as flavin adenine dinucleotide (FAD), except in eggs and milk, where it's primarily in the free form. Boiling foods results in the loss of about twice as much riboflavin content compared to other cooking methods due to its water solubility.",
        "Selected Foods High in Riboflavin": "Beef liver, fortified breakfast cereals, oats, yogurt, milk, beef, clams, almonds, Swiss cheese, mushrooms, chicken, eggs, quinoa, bagels, salmon, spinach, apples, kidney beans, whole wheat bread, cod, sunflower seeds, tomatoes, and rice (both white and brown) are notable sources.",
        "Dietary Supplements": "Riboflavin is available in various dietary supplements, with multivitamin/mineral supplements commonly providing 1.3 mg of riboflavin (100% of the Daily Value). Supplements may contain riboflavin alone or as part of B-complex vitamins. Riboflavin in supplements is typically in the free form, though some may include riboflavin 5’-phosphate."
    },
    dailyIntake: "The recommended intake of riboflavin varies depending on age and gender. For infants aged birth to 6 months, the recommended amount is 0.3 mg per day, while infants aged 7 to 12 months should aim for 0.4 mg. Children aged 1 to 3 years need 0.5 mg daily, and those aged 4 to 8 years should have 0.6 mg. Between the ages of 9 to 13 years, the recommended intake increases to 0.9 mg. Teenage boys aged 14 to 18 years require 1.3 mg daily, while teenage girls in the same age group need slightly less, at 1.0 mg. For adult men, the recommended daily intake is 1.3 mg, whereas for adult women, it is slightly lower at 1.1 mg. Pregnant teenagers and women have higher requirements, with recommendations set at 1.4 mg per day, and breastfeeding teenagers and women should aim for 1.6 mg daily.",
    deficiency: "Riboflavin deficiency can occur if you don't consume enough riboflavin-rich foods or if you have certain medical conditions. Symptoms may include skin disorders, sores at the corners of the mouth, swollen and cracked lips, hair loss, sore throat, liver issues, and reproductive and nervous system problems. Severe and prolonged riboflavin deficiency can lead to anemia, causing weakness and fatigue, as well as cataracts, which affect vision due to clouding of the eye lens.",
    res: ["https://ods.od.nih.gov/factsheets/Riboflavin-HealthProfessional/","https://ods.od.nih.gov/factsheets/Riboflavin-Consumer/#h6"]
};

export default vitaminB2;
