const vitaminB12 = {
    description: "Vitamin B12 is a vital nutrient responsible for maintaining the health of blood and nerve cells in the body. It plays a crucial role in DNA synthesis, the genetic material found in all cells. Additionally, vitamin B12 helps prevent megaloblastic anemia, a blood disorder characterized by fatigue and weakness.",
    functions: {
        "Vitamin B12's Role in Nervous System Function": "Vitamin B12 is essential for the development, myelination, and proper function of the central nervous system.",
        "Enzyme Cofactor Function": "Vitamin B12 serves as a cofactor for two crucial enzymes: methionine synthase and L-methylmalonyl-CoA mutase.",
        "Homocysteine Conversion": "Methionine synthase facilitates the conversion of homocysteine into methionine, an essential amino acid.",
        "Methyl Donor Formation": "Methionine, produced by methionine synthase, is crucial for the generation of S-adenosylmethionine, a universal methyl donor involved in various biological processes, including DNA, RNA, protein, and lipid methylation.",
        "Propionate Metabolism": " L-methylmalonyl-CoA mutase, activated by vitamin B12, converts L-methylmalonyl-CoA to succinyl-CoA in the metabolism of propionate, a short-chain fatty acid.",
    },
    sources: {
        "Food": "Vitamin B12 is primarily found in animal-derived foods such as fish, meat, poultry, eggs, and dairy products. Plant foods do not naturally contain vitamin B12, but fortified breakfast cereals and nutritional yeasts are good sources. The bioavailability of vitamin B12 from dairy is higher than from meat, fish, and poultry, and dietary supplements have about 50% higher bioavailability compared to food sources. High sources of vitamin B12 include beef liver, clams, oysters, and fortified nutritional yeast. Common foods such as salmon, tuna, milk, and eggs also contribute to dietary intake of vitamin B12.",
        "Dietary Supplements": "Vitamin B12 supplements are available in various forms, including multivitamin/mineral supplements, B-complex vitamins, and standalone vitamin B12 supplements. These supplements commonly contain cyanocobalamin, though other forms like adenosylcobalamin, methylcobalamin, and hydroxycobalamin are also used. Absorption rates of vitamin B12 supplements are around 50% at doses below 1-2 mcg, but significantly decrease at higher doses. Sublingual preparations are also available and are as effective as oral supplements.",
        "Prescription Medications": "Vitamin B12 can be administered parenterally (usually intramuscularly) as cyanocobalamin or hydroxycobalamin to treat deficiencies due to conditions like pernicious anemia or malabsorption issues. Additionally, vitamin B12 is available as a prescription nasal gel spray, which has similar bioavailability to oral supplements and is effective in raising blood levels of vitamin B12."
    },
    dailyIntake: "The recommended daily intake of vitamin B12 varies depending on age and life stage. For infants, it ranges from 0.4 mcg to 0.5 mcg during the first year. Children aged 1-8 years need between 0.9 mcg to 1.2 mcg per day, while those aged 9-13 require 1.8 mcg. Teens aged 14-18 should aim for 2.4 mcg daily, the same as adults. Pregnant and breastfeeding teens and women have slightly higher requirements, with recommendations of 2.6 mcg and 2.8 mcg respectively.",
    deficiency: "Vitamin B12 deficiency can have serious consequences on your health, and symptoms may not manifest for several years due to the body's significant stores of the vitamin. Common symptoms include fatigue, weakness, and megaloblastic anemia, characterized by pale skin and heart palpitations. Other signs may include loss of appetite, weight loss, infertility, numbness or tingling in the hands and feet, balance problems, and nerve-related issues. Mental health symptoms such as depression, confusion, dementia, and memory problems can also arise. In infants, symptoms may include failure to thrive, developmental delays, and anemia. Even without anemia, vitamin B12 deficiency can harm the nervous system, underlining the importance of prompt treatment.",
    res: ['https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/', 'https://ods.od.nih.gov/factsheets/VitaminB12-HealthProfessional/']
};

export default vitaminB12;
