const vitaminB3 = {
    description: "Niacin, or vitamin B3, is a vital water-soluble nutrient present in various forms such as nicotinic acid and nicotinamide. Once absorbed, it is converted into active coenzymes like nicotinamide adenine dinucleotide (NAD) and nicotinamide adenine dinucleotide phosphate (NADP), crucial for over 400 enzymatic reactions in the body. NAD facilitates energy production and essential cellular functions, while NADP supports anabolic processes and antioxidant defense.",
    functions: {
        "Conversion to Coenzymes": "Upon absorption, niacin is converted into active coenzymes such as nicotinamide adenine dinucleotide (NAD) and nicotinamide adenine dinucleotide phosphate (NADP), essential for numerous enzymatic reactions.",
        "Energy Metabolism": "NAD is primarily involved in catabolic reactions, converting the potential energy in carbohydrates, fats, and proteins into adenosine triphosphate (ATP), the cell's primary energy currency.",
        "Cellular Functions": "NAD is crucial for maintaining genome integrity, regulating gene expression, and facilitating cellular communication, indicating its involvement in critical cellular functions.",
        "Anabolic Processes": "NADP enables anabolic reactions, such as the synthesis of cholesterol and fatty acids, crucial for cellular growth and repair.",
        "Antioxidant Defense": "NADP plays a critical role in maintaining cellular antioxidant function, protecting cells from oxidative damage.",
        "Dietary Sources": "Niacin is naturally present in many foods and can be obtained from dietary supplements. Some foods contain small amounts of NAD and NADP, while tryptophan, an amino acid, can also be converted into niacin in the body.",
        "Absorption and Metabolism": "Niacin is primarily absorbed in the small intestine and is almost completely absorbed even at high doses. Excess niacin is metabolized and excreted, with urinary excretion of specific metabolites serving as a reliable indicator of niacin status.",
        "Assessment of Niacin Status": "Various measures, such as urinary excretion rates of specific metabolites and ratios of NAD to NADP concentrations in blood, are used to assess niacin status. Low excretion rates or altered ratios indicate potential deficiency or risk of developing deficiency."
    },
    sources: {
        "Food": "Niacin is naturally present in a wide variety of foods. Animal-based sources such as poultry, beef, and fish contain niacin primarily as NAD and NADP. Plant-based foods like nuts, legumes, and grains provide niacin mainly as nicotinic acid. Tryptophan, found in various foods, can also be converted to NAD in the liver, serving as another source of niacin.",
        "Dietary supplements": "Niacin is available in multivitamin/mineral products, B-complex vitamin supplements, and niacin-only supplements. Nicotinic acid and nicotinamide are common forms, with some supplements containing 500 mg or more per serving. Different formulations, such as prolonged or timed-release, aim to minimize skin flushing associated with nicotinic acid. Inositol hexanicotinate supplements, labeled as \"flush-free,\" have lower absorption rates than other forms.",
        "Medication": "Prescription medications like Niaspan provide extended-release nicotinic acid in doses of 500-1,000 mg. These medications are used to treat high blood cholesterol levels."
    },
    dailyIntake: "The amount of niacin recommended varies based on age and sex, with daily values given in milligrams of niacin equivalents (NE) to account for both dietary intake and conversion from tryptophan. For infants aged birth to 6 months, 2 mg is recommended, while infants aged 7–12 months need 4 mg NE. Children aged 1–3 years require 6 mg NE, and those aged 4–8 years need 8 mg NE. For children aged 9–13 years, the recommended amount is 12 mg NE. Teen boys aged 14–18 years require 16 mg NE, whereas teen girls of the same age need 14 mg NE. For adults aged 19 years and older, including men and women, 16 mg NE and 14 mg NE are recommended, respectively. Pregnant teens and women require a higher intake of 18 mg NE, while breastfeeding teens and women need 17 mg NE.",
    deficiency: "Niacin deficiency can lead to pellagra, a rare condition in developed countries. Symptoms include rough, discolored skin, a red tongue, gastrointestinal issues like vomiting and diarrhea, depression, headaches, fatigue, and behavioral changes such as aggression or paranoia. In severe cases, it can progress to hallucinations, memory loss, loss of appetite, and death.",
    res: ["https://ods.od.nih.gov/factsheets/Niacin-HealthProfessional/", "https://ods.od.nih.gov/factsheets/Niacin-Consumer/"]
};

export default vitaminB3;
