package org.food.repositories.fruitRepos;

import java.math.BigDecimal;

import org.food.Food;
import org.food.repositories.FoodRepository;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class FruitRepository {

    private final FoodRepository foodRepository;

    @PostConstruct
    private void initData() {
        Food apple = Food.builder()
                .name("Apple")
                .calories(new BigDecimal("52"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.18"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("0.5"))
                .B1(new BigDecimal("0.017"))
                .B2(new BigDecimal("0.026"))
                .B3(new BigDecimal("0.091"))
                .B5(new BigDecimal("0.043"))
                .B6(new BigDecimal("0.041"))
                .B7(new BigDecimal("0.009"))
                .B9(new BigDecimal("0.003"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("5"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("107"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.12"))
                .Zinc(new BigDecimal("0.05"))
                .Copper(new BigDecimal("0.05"))
                .Manganese(new BigDecimal("0.035"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14"))
                .Protein(new BigDecimal("0.3"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(apple);
        Food acai = Food.builder()
                .name("Açaí")
                .calories(new BigDecimal("70"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("1.08"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("8.83"))
                .B1(new BigDecimal("0.031"))
                .B2(new BigDecimal("0.021"))
                .B3(new BigDecimal("0.086"))
                .B5(new BigDecimal("0.407"))
                .B6(new BigDecimal("0.08"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.023"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("6"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("10"))
                .Potassium(new BigDecimal("55"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.26"))
                .Zinc(new BigDecimal("0.06"))
                .Copper(new BigDecimal("0.13"))
                .Manganese(new BigDecimal("1.03"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("4.6"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("5.4"))
                .build();

        foodRepository.addFood(acai);
        Food acerolaCherries = Food.builder()
                .name("Acerola Cherries")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("1677"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("1.4"))
                .C(new BigDecimal("1677"))
                .B1(new BigDecimal("0.009"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.009"))
                .B7(new BigDecimal("0.009"))
                .B9(new BigDecimal("0.07"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("17"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("146"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.086"))
                .Manganese(new BigDecimal("0.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("7.7"))
                .Protein(new BigDecimal("0.4"))
                .Fat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(acerolaCherries);
        Food africanBreadfruit = Food.builder()
                .name("African Breadfruit")
                .calories(new BigDecimal("123"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("6"))
                .C(new BigDecimal("25"))
                .B1(new BigDecimal("0.5"))
                .B2(new BigDecimal("0.1"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.7"))
                .B6(new BigDecimal("0.07"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("44"))
                .Phosphorus(new BigDecimal("40"))
                .Magnesium(new BigDecimal("34"))
                .Sodium(new BigDecimal("7"))
                .Potassium(new BigDecimal("490"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.7"))
                .Zinc(new BigDecimal("0.3"))
                .Copper(new BigDecimal("0.3"))
                .Manganese(new BigDecimal("0.4"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("1.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("25"))
                .Protein(new BigDecimal("2.6"))
                .Fat(new BigDecimal("0.7"))
                .build();

        foodRepository.addFood(africanBreadfruit);
        Food akebiFruit = Food.builder()
                .name("Akebi Fruit")
                .calories(new BigDecimal("25"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("14"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.01"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("110"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("6"))
                .Protein(new BigDecimal("0.5"))
                .Fat(new BigDecimal("0"))
                .build();

        foodRepository.addFood(akebiFruit);
        Food alpineStrawberry = Food.builder()
                .name("Alpine Strawberry")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("2.2"))
                .C(new BigDecimal("58.8"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("13"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("247"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("7.7"))
                .Protein(new BigDecimal("0.7"))
                .Fat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(alpineStrawberry);
        Food africanMango = Food.builder()
                .name("African Mango")
                .calories(new BigDecimal("60"))
                .A(new BigDecimal("54"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.27"))
                .K(new BigDecimal("27"))
                .C(new BigDecimal("36"))
                .B1(new BigDecimal("0.06"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.1"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.04"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.04"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("27"))
                .Phosphorus(new BigDecimal("34"))
                .Magnesium(new BigDecimal("43"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("325"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("15"))
                .Protein(new BigDecimal("1.4"))
                .Fat(new BigDecimal("0.6"))
                .build();

        foodRepository.addFood(africanMango);

        Food amanatsuOranges = Food.builder()
                .name("Amanatsu Oranges")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("120"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.2"))
                .K(new BigDecimal("0"))
                .C(new BigDecimal("54"))
                .B1(new BigDecimal("0.08"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.04"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.02"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("38"))
                .Phosphorus(new BigDecimal("15"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("225"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.3"))
                .Protein(new BigDecimal("1"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(amanatsuOranges);
        Food ambarella = Food.builder()
                .name("Ambarella")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("27"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.35"))
                .K(new BigDecimal("0.6"))
                .C(new BigDecimal("8.7"))
                .B1(new BigDecimal("0.04"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.06"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.02"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("17"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("2"))
                .Potassium(new BigDecimal("66"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.3"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(ambarella);
        Food amaouStrawberries = Food.builder()
                .name("Amaou Strawberries")
                .calories(new BigDecimal("32"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.3"))
                .K(new BigDecimal("2"))
                .C(new BigDecimal("58"))
                .B1(new BigDecimal("0.02"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.4"))
                .B5(new BigDecimal("0.3"))
                .B6(new BigDecimal("0.03"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.02"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("16"))
                .Phosphorus(new BigDecimal("24"))
                .Magnesium(new BigDecimal("13"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("247"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.6"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("7.7"))
                .Protein(new BigDecimal("0.7"))
                .Fat(new BigDecimal("0.3"))
                .build();

        foodRepository.addFood(amaouStrawberries);
        Food ambrosiaApples = Food.builder()
                .name("Ambrosia Apples")
                .calories(new BigDecimal("52"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.18"))
                .K(new BigDecimal("0.5"))
                .C(new BigDecimal("8"))
                .B1(new BigDecimal("0.017"))
                .B2(new BigDecimal("0.026"))
                .B3(new BigDecimal("0.091"))
                .B5(new BigDecimal("0.043"))
                .B6(new BigDecimal("0.041"))
                .B7(new BigDecimal("0.009"))
                .B9(new BigDecimal("0.003"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("6"))
                .Phosphorus(new BigDecimal("11"))
                .Magnesium(new BigDecimal("5"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("107"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.12"))
                .Zinc(new BigDecimal("0.05"))
                .Copper(new BigDecimal("0.05"))
                .Manganese(new BigDecimal("0.035"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("14"))
                .Protein(new BigDecimal("0.3"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(ambrosiaApples);
        Food ambrosiaMelon = Food.builder()
                .name("Ambrosia Cantaloupe")
                .calories(new BigDecimal("34"))
                .A(new BigDecimal("3382"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.08"))
                .K(new BigDecimal("267"))
                .C(new BigDecimal("36.7"))
                .B1(new BigDecimal("0.041"))
                .B2(new BigDecimal("0.041"))
                .B3(new BigDecimal("0.734"))
                .B5(new BigDecimal("0.21"))
                .B6(new BigDecimal("0.045"))
                .B7(new BigDecimal("0.073"))
                .B9(new BigDecimal("0.01"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("15"))
                .Magnesium(new BigDecimal("12"))
                .Sodium(new BigDecimal("16"))
                .Potassium(new BigDecimal("267"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.21"))
                .Zinc(new BigDecimal("0.17"))
                .Copper(new BigDecimal("0.041"))
                .Manganese(new BigDecimal("0.041"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("0.01"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.2"))
                .Protein(new BigDecimal("0.8"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(ambrosiaMelon);
        Food amla = Food.builder()
                .name("Amla (Indian Gooseberry)")
                .calories(new BigDecimal("44"))
                .A(new BigDecimal("290"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.58"))
                .K(new BigDecimal("25.5"))
                .C(new BigDecimal("27.7"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.3"))
                .B5(new BigDecimal("0.2"))
                .B6(new BigDecimal("0.08"))
                .B7(new BigDecimal("0"))
                .B9(new BigDecimal("0.05"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("25"))
                .Phosphorus(new BigDecimal("27"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("198"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.5"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("10.2"))
                .Protein(new BigDecimal("0.9"))
                .Fat(new BigDecimal("0.6"))
                .build();

        foodRepository.addFood(amla);
        Food apricots = Food.builder()
                .name("Apricots")
                .calories(new BigDecimal("50"))
                .A(new BigDecimal("96"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.89"))
                .K(new BigDecimal("3"))
                .C(new BigDecimal("3.9"))
                .B1(new BigDecimal("0.03"))
                .B2(new BigDecimal("0.04"))
                .B3(new BigDecimal("0.6"))
                .B5(new BigDecimal("0.4"))
                .B6(new BigDecimal("0.054"))
                .B7(new BigDecimal("0.027"))
                .B9(new BigDecimal("0.009"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("13"))
                .Phosphorus(new BigDecimal("23"))
                .Magnesium(new BigDecimal("10"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("259"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.4"))
                .Zinc(new BigDecimal("0.2"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("11"))
                .Protein(new BigDecimal("1.4"))
                .Fat(new BigDecimal("0.4"))
                .build();

        foodRepository.addFood(apricots);
        Food annona = Food.builder()
                .name("Annona (Custard Apple)")
                .calories(new BigDecimal("73"))
                .A(new BigDecimal("2"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.27"))
                .K(new BigDecimal("0.6"))
                .C(new BigDecimal("19.2"))
                .B1(new BigDecimal("0.11"))
                .B2(new BigDecimal("0.05"))
                .B3(new BigDecimal("0.53"))
                .B5(new BigDecimal("0.25"))
                .B6(new BigDecimal("0.13"))
                .B7(new BigDecimal("0.12"))
                .B9(new BigDecimal("0.029"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("22"))
                .Phosphorus(new BigDecimal("26"))
                .Magnesium(new BigDecimal("21"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("287"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.4"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.6"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("17.2"))
                .Protein(new BigDecimal("2.1"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(annona);
        Food asianPears = Food.builder()
                .name("Asian Pears")
                .calories(new BigDecimal("43"))
                .A(new BigDecimal("0"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("0.12"))
                .K(new BigDecimal("10"))
                .C(new BigDecimal("3.1"))
                .B1(new BigDecimal("0.01"))
                .B2(new BigDecimal("0.02"))
                .B3(new BigDecimal("0.03"))
                .B5(new BigDecimal("0.1"))
                .B6(new BigDecimal("0.02"))
                .B7(new BigDecimal("0.012"))
                .B9(new BigDecimal("0.01"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("9"))
                .Phosphorus(new BigDecimal("8"))
                .Magnesium(new BigDecimal("9"))
                .Sodium(new BigDecimal("0"))
                .Potassium(new BigDecimal("121"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.2"))
                .Zinc(new BigDecimal("0.1"))
                .Copper(new BigDecimal("0.1"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.1"))
                .Fluoride(new BigDecimal("0"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("11"))
                .Protein(new BigDecimal("0.5"))
                .Fat(new BigDecimal("0.2"))
                .build();

        foodRepository.addFood(asianPears);
        Food avocado = Food.builder()
                .name("Avocado")
                .calories(new BigDecimal("160"))
                .A(new BigDecimal("7"))
                .D(new BigDecimal("0"))
                .E(new BigDecimal("2.1"))
                .K(new BigDecimal("21"))
                .C(new BigDecimal("10"))
                .B1(new BigDecimal("0.07"))
                .B2(new BigDecimal("0.13"))
                .B3(new BigDecimal("1.7"))
                .B5(new BigDecimal("1.4"))
                .B6(new BigDecimal("0.3"))
                .B7(new BigDecimal("0.09"))
                .B9(new BigDecimal("0.08"))
                .B12(new BigDecimal("0"))
                .Calcium(new BigDecimal("12"))
                .Phosphorus(new BigDecimal("29"))
                .Magnesium(new BigDecimal("29"))
                .Sodium(new BigDecimal("1"))
                .Potassium(new BigDecimal("485"))
                .Chloride(new BigDecimal("0"))
                .Iron(new BigDecimal("0.6"))
                .Zinc(new BigDecimal("0.6"))
                .Copper(new BigDecimal("0.2"))
                .Manganese(new BigDecimal("0.1"))
                .Iodine(new BigDecimal("0"))
                .Selenium(new BigDecimal("0.4"))
                .Fluoride(new BigDecimal("0.02"))
                .Chromium(new BigDecimal("0"))
                .Molybdenum(new BigDecimal("0"))
                .Carbohydrates(new BigDecimal("8.5"))
                .Protein(new BigDecimal("2"))
                .Fat(new BigDecimal("14.7"))
                .build();

        foodRepository.addFood(avocado);

    }
}
